import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

const omniRoot = path.resolve('src/data/omnicortex');
const econPath = path.resolve('docs/operator/2.00 ECONOMATRIX.md');
const text = fs.readFileSync(econPath, 'utf8');

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function writeEntry(cat, id, data, body) {
  const dir = path.join(omniRoot, cat);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${id}.md`);
  const output = matter.stringify(body.trim(), { id, category: cat, ...data });
  fs.writeFileSync(file, output, 'utf8');
  console.log(`[+] Added ${cat}/${id}.md`);
}

// -------------------------------------------------------------
// 1. ARCHITECTURE FROM ECONOMATRIX
// -------------------------------------------------------------
const architectureEntries = [
  {
    id: 'native-longhouse-communal-shelter',
    name: 'Native Longhouse / Communal Shelter',
    style: 'Native / Survivalist',
    footprint: 'Medium',
    height_class: 'Single',
    stories: 1,
    frame: 'Standard',
    environment: 'Standard',
    tl: 0,
    ml: 0,
    cost: 1470,
    sp: 400,
    dr: 2,
    modules: 25,
    design_dc: 18,
    craft_dc: 18,
    security_level: 'Open',
    primary_purpose: 'Residential / Clan Habitation',
    description: 'A large, elongated single-story structure constructed from heavy timber ribs and tightly woven thatch or treated animal hides. Serves as the central hub for a clan or extended family unit.',
    mechanic: 'Structure Points: 400 SP. Damage Resist: 2 (Flammable). Total Modules: 25. Module Configuration: Communal Living (10), Central Hearth (5), Storage (5), Shrine (2), Elder\'s Quarters (3).'
  },
  {
    id: 'colonial-prefab-module',
    name: 'Colonial Prefab Module',
    style: 'Frontier / Modular',
    footprint: 'Small',
    height_class: 'Single',
    stories: 1,
    frame: 'Industrial',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 2560,
    sp: 500,
    dr: 12,
    modules: 10,
    design_dc: 20,
    craft_dc: 20,
    security_level: 'Open',
    primary_purpose: 'Rapid-deployment colonial habitat',
    description: 'Standardized mass-produced habitat module designed for rapid frontier deployment. Walls are made of multi-layered insulating composites.',
    mechanic: 'Structure Points: 500 SP. DR: 12 (Plasteel/Composite). Modules: 10. Life Support (2), Bunks (2), Galley/Mess (2), Comms Array (1), Airlock (1), Storage (2).'
  },
  {
    id: 'arcology-hab-block',
    name: 'Arcology Hab-Block / Megastructure',
    style: 'Urban / Megastructure',
    footprint: 'Gargantuan',
    height_class: 'Skyscraper',
    stories: 50,
    frame: 'Dynamic',
    environment: 'Standard',
    tl: 4,
    ml: 0,
    cost: 42949672960,
    sp: 7500000,
    dr: 18,
    modules: 250000,
    design_dc: 80,
    craft_dc: 80,
    security_level: 'Restricted',
    primary_purpose: 'Self-contained city-in-a-building for millions',
    description: 'A self-contained city-in-a-building designed to house millions of citizens with internal weather control, hydroponics, transit, and security.',
    mechanic: 'SP: 7,500,000. DR: 18 (Nanocarbon). Modules: 250,000+. Residential Grid (10,000 Coffin + 5,000 Family), Hydroponics, Law Enforcement, Mag-lev transit, Commercial concourse.'
  },
  {
    id: 'transit-hub-spaceport-terminal',
    name: 'Transit Hub / Spaceport Terminal',
    style: 'Commercial / Transit',
    footprint: 'Huge',
    height_class: 'Multi-Story',
    stories: 4,
    frame: 'Standard',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 10485760,
    sp: 60000,
    dr: 12,
    modules: 2000,
    design_dc: 50,
    craft_dc: 50,
    security_level: 'Restricted',
    primary_purpose: 'Commercial Spaceport & Passenger / Cargo Transit',
    description: 'Sprawling transit hub featuring central vaulted atrium, landing pads, hangars, customs gates, duty-free shopping, and automated cargo storage.',
    mechanic: 'SP: 60,000. DR: 12. Modules: 2,000. Hangar Bays (1,000), Cargo Warehousing (500), Commercial Concourse (300), Admin/Control (100), Fueling Systems (100).'
  },
  {
    id: 'black-market-bazaar',
    name: 'Black Market / Bazaar',
    style: 'Outlaw / Scavenger',
    footprint: 'Medium',
    height_class: 'Single',
    stories: 1,
    frame: 'Industrial',
    environment: 'Standard',
    tl: 2,
    ml: 0,
    cost: 10240,
    sp: 1200,
    dr: 8,
    modules: 25,
    design_dc: 25,
    craft_dc: 25,
    security_level: 'Black-Site',
    primary_purpose: 'Illicit Trade & Smuggling Outpost',
    description: 'A chaotic labyrinth of narrow passages, shipping container stalls, and hidden compartments under floorboards for illicit trade.',
    mechanic: 'SP: 1,200. DR: 8 (Patchwork Metal). Modules: 25. Vendor Stalls (15), Hidden Storage (4), Gambling Den (2), Armored Safe Room (4).'
  },
  {
    id: 'orbital-alloy-foundry',
    name: 'Orbital Alloy Foundry',
    style: 'Heavy Industry',
    footprint: 'Large',
    height_class: 'Duplex',
    stories: 2,
    frame: 'Industrial',
    environment: 'Vacuum / Toxic / Corrosive',
    tl: 4,
    ml: 0,
    cost: 167772160,
    sp: 11250,
    dr: 18,
    modules: 200,
    design_dc: 60,
    craft_dc: 60,
    security_level: 'High Security',
    primary_purpose: 'Zero-Gravity Metallurgical Smelting & Nanofabrication',
    description: 'Zero-gravity industrial orbital station equipped with magnetic containment crucibles, nano-lathes, and heavy cargo airlocks for smelting asteroid ore.',
    mechanic: 'SP: 11,250. DR: 18 (Heat Shielding). Modules: 200. Smelting Floor (100), Fabrication (50), Docking (20), Power (20), Cooling (10).'
  },
  {
    id: 'deep-core-mine-drill-site',
    name: 'Deep Core Mine / Drill Site',
    style: 'Extraction',
    footprint: 'Large',
    height_class: 'Single',
    stories: 1,
    frame: 'Subterranean',
    environment: 'High Gravity',
    tl: 3,
    ml: 0,
    cost: 163840,
    sp: 5000,
    dr: 12,
    modules: 100,
    design_dc: 35,
    craft_dc: 35,
    security_level: 'Restricted',
    primary_purpose: 'Planetary Core Extraction & Mineral Refining',
    description: 'Inverted subterranean mining architecture spiraling deep into planetary strata with a central plasma drill vaporizing rock.',
    mechanic: 'SP: 5,000. DR: 12. Modules: 100. Drilling Rig (40), Mineral Processing (30), Material Elevators (10), Power Plant (20).'
  },
  {
    id: 'forward-operating-base',
    name: 'Forward Operating Base (FOB)',
    style: 'Militaristic / Colony',
    footprint: 'Large',
    height_class: 'Single',
    stories: 1,
    frame: 'Standard',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 71316,
    sp: 6000,
    dr: 17,
    modules: 90,
    design_dc: 32,
    craft_dc: 32,
    security_level: 'High Security',
    primary_purpose: 'Military Fortification & Staging Ground',
    description: 'Heavily fortified military outpost with ferro-concrete walls, hardened armor plating, automated turret nests, and garrison barracks for 100 troops.',
    mechanic: 'SP: 6,000 (+20% Bulwark). DR: 17 (Hardened). Modules: 90. Command/CIC (10), Garrison & Armory (30), Support & Vehicle Bay (20), Defenses & Shields (30).'
  },
  {
    id: 'planetary-shield-generator',
    name: 'Planetary Shield Generator',
    style: 'Defensive',
    footprint: 'Medium',
    height_class: 'Mid-Rise',
    stories: 5,
    frame: 'Tower',
    environment: 'Standard',
    tl: 4,
    ml: 0,
    cost: 41943040,
    sp: 19200,
    dr: 50,
    modules: 250,
    design_dc: 55,
    craft_dc: 55,
    security_level: 'High Security',
    primary_purpose: 'Hemispherical Orbital Bombardment Defense',
    description: 'Geodesic emitter spire supported by heavy pylons projecting an energy barrier capable of deflecting planetary bombardment.',
    mechanic: 'SP: 19,200. DR: 50 (Active Shielding). Modules: 250. Emitter Array (150), Reactor Core (80), Cryo Cooling (20).'
  },
  {
    id: 'orbital-research-station',
    name: 'Orbital Research Station',
    style: 'Scientific / High-Tech',
    footprint: 'Small',
    height_class: 'Multi-Story',
    stories: 5,
    frame: 'Tower',
    environment: 'Vacuum / Toxic / Corrosive',
    tl: 4,
    ml: 0,
    cost: 23525,
    sp: 2250,
    dr: 18,
    modules: 40,
    design_dc: 28,
    craft_dc: 28,
    security_level: 'Restricted',
    primary_purpose: 'Zero-G Laboratory & Deep Void Scientific Research',
    description: 'Central vertical core with radiating horizontal research pods isolating hazardous experiments, containing bio-labs, AI servers, and crew quarters.',
    mechanic: 'SP: 2,250. DR: 18. Modules: 40. Labs (20), Containment (10), Server Core (5), Living Quarters (5).'
  },
  {
    id: 'cyber-clinic-street-doc',
    name: 'Cyber-Clinic / Street Doc',
    style: 'Medical / Underground',
    footprint: 'Tiny',
    height_class: 'Single',
    stories: 1,
    frame: 'Standard',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 279,
    sp: 200,
    dr: 12,
    modules: 4,
    design_dc: 12,
    craft_dc: 12,
    security_level: 'Open',
    primary_purpose: 'Black-Clinic Cyberware Installation & Emergency Surgery',
    description: 'Compact medical clinic tailored for rapid cybernetic surgery, trauma repair, and illicit biological modifications.',
    mechanic: 'SP: 200. DR: 12. Modules: 4. Surgical Chair, Autodoc Arm, Sterilization Chamber, Storage.'
  },
  {
    id: 'fusion-power-plant',
    name: 'Fusion Power Plant',
    style: 'Utility',
    footprint: 'Large',
    height_class: 'Multi-Story',
    stories: 3,
    frame: 'Industrial',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 2621440,
    sp: 15000,
    dr: 12,
    modules: 400,
    design_dc: 45,
    craft_dc: 45,
    security_level: 'High Security',
    primary_purpose: 'Metropolitan Grid Power Generation',
    description: 'Massive toroidal magnetic confinement fusion reactor flanked by cooling hypertowers delivering high-yield electrical and plasma power.',
    mechanic: 'SP: 15,000. DR: 12 (Radiation Shielded). Modules: 400. Reactor Core (200), Turbines (100), Control Room (50), Cooling Systems (50).'
  },
  {
    id: 'orbital-habitat',
    name: 'Orbital Habitat',
    style: 'Macro-Structuralism',
    footprint: 'Colossal',
    height_class: 'Skyscraper',
    stories: 100,
    frame: 'Dynamic',
    environment: 'Vacuum / Toxic / Corrosive',
    tl: 5,
    ml: 0,
    cost: 42949672960,
    sp: 1000000,
    dr: 30,
    modules: 100000,
    design_dc: 80,
    craft_dc: 80,
    security_level: 'Restricted',
    primary_purpose: 'Rotating Cylindrical Orbital City & Space Biosphere',
    description: 'Massive rotating O\'Neill cylinder generating artificial gravity, containing self-sustaining biomes, residential districts, and industrial sectors in space.',
    mechanic: 'SP: 1,000,000+. Modules: 100,000+. Internal centrifugal gravity, atmosphere cyclers, agricultural bands, and dock collars.'
  },
  {
    id: 'crystal-sanctum-floating-spire',
    name: 'Crystal Sanctum / Floating Spire',
    style: 'Alterian / Resonance',
    footprint: 'Small',
    height_class: 'Skyscraper',
    stories: 50,
    frame: 'Palatial',
    environment: 'Standard',
    tl: 5,
    ml: 3,
    cost: 167772160,
    sp: 62500,
    dr: 25,
    modules: 1000,
    design_dc: 60,
    craft_dc: 60,
    security_level: 'High Security',
    primary_purpose: 'Psionic Amplification Spire & Ancient Archives',
    description: 'Towering spire of psycho-reactive crystal floating weightlessly above ground via psionic resonance fields, housing metaphysical research sanctums.',
    mechanic: 'SP: 62,500. DR: 25 (Adaptive). Modules: 1,000. Focus Chamber (100, +4 Meta Skills), Archives (400), Training Halls (200), Levitation Core (100), Psionic Defenses (100).'
  },
  // Specialized modules
  {
    id: 'med-bay-module',
    name: 'Med-Bay Facility Module',
    style: 'Standard',
    footprint: 'Small',
    height_class: 'Single',
    stories: 1,
    frame: 'Standard',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 5000,
    sp: 100,
    dr: 10,
    modules: 1,
    design_dc: 23,
    craft_dc: 23,
    security_level: 'Open',
    primary_purpose: 'Medical installation module',
    description: 'Standardized medical facility module providing sterile triage and treatment bays.',
    mechanic: 'Counts as Sterile Environment. Grants +2 to Medical checks.'
  },
  {
    id: 'armory-module',
    name: 'Armory Facility Module',
    style: 'Standard',
    footprint: 'Small',
    height_class: 'Single',
    stories: 1,
    frame: 'Standard',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 2000,
    sp: 250,
    dr: 15,
    modules: 1,
    design_dc: 19,
    craft_dc: 19,
    security_level: 'High Security',
    primary_purpose: 'Secure weapon and ordinance storage module',
    description: 'Reinforced security vault fitted with Grade 3 biometric locks and specialized weapon racks.',
    mechanic: 'Secure storage holding 50 Slots of gear. Security Grade 3 locks.'
  },
  {
    id: 'holo-deck-module',
    name: 'Holo-Deck Simulation Module',
    style: 'Standard',
    footprint: 'Small',
    height_class: 'Single',
    stories: 1,
    frame: 'Standard',
    environment: 'Standard',
    tl: 4,
    ml: 0,
    cost: 10000,
    sp: 150,
    dr: 10,
    modules: 1,
    design_dc: 25,
    craft_dc: 25,
    security_level: 'Restricted',
    primary_purpose: 'Virtual reality environmental combat and skill simulator',
    description: 'Volumetric hard-light and sensory simulation chamber for training and recreation.',
    mechanic: 'Simulates any planetary environment. XP / Mastery gain from training here is +10%.'
  },
  {
    id: 'workshop-module',
    name: 'Workshop Facility Module',
    style: 'Standard',
    footprint: 'Small',
    height_class: 'Single',
    stories: 1,
    frame: 'Standard',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 3000,
    sp: 150,
    dr: 10,
    modules: 1,
    design_dc: 20,
    craft_dc: 20,
    security_level: 'Open',
    primary_purpose: 'Engineering & Manufacturing Workshop',
    description: 'Equipped with heavy tooling benches, diagnostic computers, and repair suites.',
    mechanic: 'Contains Engineering Tools. Reduces Crafting Time by 25%.'
  },
  {
    id: 'brig-module',
    name: 'Brig Detention Module',
    style: 'Standard',
    footprint: 'Small',
    height_class: 'Single',
    stories: 1,
    frame: 'Standard',
    environment: 'Standard',
    tl: 3,
    ml: 0,
    cost: 1500,
    sp: 300,
    dr: 20,
    modules: 1,
    design_dc: 18,
    craft_dc: 18,
    security_level: 'High Security',
    primary_purpose: 'Secure Prisoner Holding Cell',
    description: 'Heavy containment cell with forcefield bars and anti-tamper locks.',
    mechanic: 'Holding cell with Structure 30 Forcefield walls.'
  }
];

for (const arch of architectureEntries) {
  writeEntry('architecture', arch.id, arch, `${arch.description}\n\n**Mechanics:** ${arch.mechanic}`);
}

// -------------------------------------------------------------
// 2. ARMORING FROM ECONOMATRIX
// -------------------------------------------------------------
const armoringEntries = [
  {
    id: 'synth-leather-jack',
    name: 'Synth-Leather "Jack"',
    category: 'armoring',
    tl: 2,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    design_dc: 10,
    dr: 5,
    sp: 10,
    durability: 10,
    body_locations: ['Torso', 'Arms'],
    coverage: 'Partial',
    category: 'Lightweight',
    component_slots: 2,
    sockets: 2,
    description: 'A textured bodysuit or jacket made from chemically treated synthetic leather. Common among spacers and urban youth.',
    mechanic: 'Civilian Grade (Legal in all jurisdictions). DR 5, SP 10. No mobility penalties.'
  },
  {
    id: 'ballistic-mesh',
    name: 'Ballistic Mesh Suit',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    design_dc: 10,
    dr: 5,
    sp: 10,
    durability: 10,
    body_locations: ['Torso', 'Legs'],
    coverage: 'Partial',
    category: 'Lightweight',
    component_slots: 2,
    sockets: 2,
    description: 'Standard street-wear lined with a flexible network of plastic or metal alloys. Stops small arms fire while appearing as normal clothing.',
    mechanic: 'Concealable (Detectable only with physical inspection). DR 5, SP 10.'
  },
  {
    id: 'nanofiber-cloth-suit',
    name: 'Nanofiber "Cloth" Suit',
    category: 'armoring',
    tl: 4,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    design_dc: 10,
    dr: 5,
    sp: 10,
    durability: 10,
    body_locations: ['Torso', 'Arms', 'Legs'],
    coverage: 'Standard',
    category: 'Lightweight',
    component_slots: 2,
    sockets: 2,
    description: 'Tailored from advanced ballistic cloth (TL 4). Absorbs kinetic energy and spreads impact. Indistinguishable from high-end business wear.',
    mechanic: 'High Fashion (+1 to Etiquette/Style checks); Concealable. DR 5, SP 10.'
  },
  {
    id: 'security-vest-standard',
    name: 'Security Vest (Standard)',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    design_dc: 10,
    dr: 10,
    sp: 20,
    durability: 20,
    body_locations: ['Torso'],
    coverage: 'Partial',
    category: 'Mediumweight',
    component_slots: 2,
    sockets: 2,
    description: 'A semi-rigid vest made of ceramic plates over a kevlar weave. Standard issue for police and private security.',
    mechanic: 'Hardened (Immune to Critical Hits from small arms). DR 10, SP 20.'
  },
  {
    id: 'scout-suit-infiltration-coat',
    name: 'Scout Suit / Infiltration Coat',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 279,
    craft_dc: 12,
    design_dc: 12,
    dr: 10,
    sp: 20,
    durability: 20,
    body_locations: ['Torso', 'Arms', 'Legs'],
    coverage: 'Standard',
    category: 'Mediumweight',
    component_slots: 4,
    sockets: 4,
    description: 'A matte-black armored long coat or bodysuit using sound-dampening polymers. Covers vital areas while allowing free movement.',
    mechanic: 'Stealthy (+2 to Stealth checks). DR 10, SP 20.'
  },
  {
    id: 'heavy-tactical-helmet',
    name: 'Heavy Tactical Helmet',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 279,
    craft_dc: 12,
    design_dc: 12,
    dr: 15,
    sp: 15,
    durability: 15,
    body_locations: ['Head'],
    coverage: 'Partial',
    category: 'Mediumweight',
    component_slots: 1,
    sockets: 1,
    description: 'Full-face protection with integrated comms and sensor housing.',
    mechanic: 'Sensor Suite (Can house HUD/Comms). -2 Sight/Hearing without sensor link. DR 15, SP 15.'
  },
  {
    id: 'infantry-plate-trooper-armor',
    name: 'Infantry Plate (Trooper Armor)',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 1470,
    craft_dc: 18,
    design_dc: 18,
    dr: 15,
    sp: 40,
    durability: 40,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Heavyweight',
    component_slots: 6,
    sockets: 6,
    description: 'Rigid composite plating covering the entire body, mounted on a sealed bodysuit. Standard military armor for Coalition and Dynasty forces.',
    mechanic: 'Environmental Seal (6 hours air). DR 15, SP 40. No mobility penalties.'
  },
  {
    id: 'survival-hard-suit',
    name: 'Survival "Hard-Suit"',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 1470,
    craft_dc: 18,
    design_dc: 18,
    dr: 15,
    sp: 40,
    durability: 40,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Heavyweight',
    component_slots: 6,
    sockets: 6,
    description: 'Ruggedized plating over a pressurized under-suit, designed for hostile environments (vacuum, radiation, toxic atmosphere).',
    mechanic: 'Full Environmental (Immune to gas/vacuum, 24hr Life Support). DR 15, SP 40.'
  },
  {
    id: 'composite-combat-shell',
    name: 'Composite Combat Shell',
    category: 'armoring',
    tl: 4,
    ml: 0,
    cost: 4457,
    craft_dc: 22,
    design_dc: 22,
    dr: 20,
    sp: 50,
    durability: 50,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Heavyweight',
    mobility_penalty: 1,
    component_slots: 8,
    sockets: 8,
    description: 'Advanced molded ceramics that offer superior deflection. Sleek, sealed, and favored by Entari and Syndicate shock troops.',
    mechanic: 'Refractive Coating (+2 Defense vs Lasers/Beams). -1 Mobility, -5 Movement. DR 20, SP 50.'
  },
  {
    id: 'heavy-assault-plate-juggernaut',
    name: 'Heavy Assault Plate (Juggernaut)',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 10240,
    craft_dc: 25,
    design_dc: 25,
    dr: 30,
    sp: 80,
    durability: 80,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Reinforced',
    category: 'Heavyweight',
    mobility_penalty: 2,
    component_slots: 10,
    sockets: 10,
    description: 'Thick slabs of ablative armor and plasteel turning the wearer into a walking fortress.',
    mechanic: 'Anchor (Advantage on checks to resist being knocked down). -2 Mobility, -10 Movement. DR 30, SP 80.'
  },
  {
    id: 'eod-hazard-shell',
    name: 'EOD / Hazard Shell',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 10240,
    craft_dc: 25,
    design_dc: 25,
    dr: 30,
    sp: 80,
    durability: 80,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Reinforced',
    category: 'Heavyweight',
    mobility_penalty: 2,
    component_slots: 10,
    sockets: 10,
    description: 'Bulky specialized armor designed for bomb disposal, plasma containment, and extreme radiation environments.',
    mechanic: 'Blast Shielding (Explosive/Area damage reduced by 50%). -2 Mobility, -10 Movement. DR 30, SP 80.'
  },
  {
    id: 'utility-exoskeleton-loader',
    name: 'Utility Exoskeleton (Loader)',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 40960,
    craft_dc: 30,
    design_dc: 30,
    dr: 40,
    sp: 120,
    durability: 120,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Bulwark',
    category: 'Heavyweight',
    component_slots: 15,
    sockets: 15,
    description: 'An open-frame hydraulic skeleton used for heavy cargo loading and industrial assembly, amplifying physical strength.',
    mechanic: 'Hydraulic Strength (Set Strength to 18/+4, Lifting Capacity x2). DR 40, SP 120.'
  },
  {
    id: 'battle-suit-standard-pa',
    name: 'Battle Suit (Standard Power Armor)',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 40960,
    craft_dc: 30,
    design_dc: 30,
    dr: 35,
    sp: 100,
    durability: 100,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Heavyweight',
    component_slots: 12,
    sockets: 12,
    description: 'Fully motorized military battle suit combining thick ceramic-titanium armor with servo-assisted musculature and life support.',
    mechanic: 'Motorized Strength (+2 Might), Sealed Life Support (24h), Integrated HUD. DR 35, SP 100.'
  },
  {
    id: 'symbiotic-second-skin',
    name: 'Symbiotic "Second Skin"',
    category: 'armoring',
    tl: 4,
    ml: 0,
    cost: 2560,
    craft_dc: 20,
    design_dc: 20,
    dr: 12,
    sp: 30,
    durability: 30,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Lightweight',
    component_slots: 4,
    sockets: 4,
    description: 'Living Auluran bioweave suit that bonds to the wearer\'s epidermis, flexing naturally and regenerating cellular tears.',
    mechanic: 'Regenerating Bio-Armor (Regains 5 SP per hour), Zero Mobility Penalty. DR 12, SP 30.'
  },
  {
    id: 'chitinous-carapace',
    name: 'Chitinous Carapace (Warrior Strain)',
    category: 'armoring',
    tl: 3,
    ml: 0,
    cost: 2560,
    craft_dc: 20,
    design_dc: 20,
    dr: 18,
    sp: 45,
    durability: 45,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Mediumweight',
    component_slots: 6,
    sockets: 6,
    description: 'Dense, multilayered insectoid carapace grown by Kitin warriors, offering high deflection against kinetic and acid attacks.',
    mechanic: 'Acid & Kinetic Resistance (Ignore 5 Acid/Corrosive damage). DR 18, SP 45.'
  },
  {
    id: 'warded-weave-robes',
    name: 'Warded Weave Robes',
    category: 'armoring',
    tl: 3,
    ml: 2,
    cost: 640,
    craft_dc: 15,
    design_dc: 15,
    dr: 8,
    sp: 20,
    durability: 20,
    body_locations: ['Torso', 'Arms', 'Legs'],
    coverage: 'Standard',
    category: 'Lightweight',
    component_slots: 3,
    sockets: 3,
    description: 'Silken robes embroidered with conductive resonant sigils designed to disperse metaphysical and thermal energy.',
    mechanic: 'Resonance Dispersion (+2 to saves vs Metaphysical and Energy attacks). DR 8, SP 20.'
  },
  {
    id: 'runeguard-plate',
    name: 'Runeguard Plate',
    category: 'armoring',
    tl: 4,
    ml: 2,
    cost: 10240,
    craft_dc: 25,
    design_dc: 25,
    dr: 22,
    sp: 60,
    durability: 60,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Heavyweight',
    component_slots: 8,
    sockets: 8,
    description: 'Forged arcanosteel plate suit etched with warding glyphs that deflect both physical ordinance and psionic assaults.',
    mechanic: 'Psionic Warding (+3 Will Defense against Mental Disciplines). DR 22, SP 60.'
  },
  {
    id: 'crystalline-body-glove',
    name: 'Crystalline Body-Glove',
    category: 'armoring',
    tl: 4,
    ml: 1,
    cost: 4457,
    craft_dc: 22,
    design_dc: 22,
    dr: 14,
    sp: 35,
    durability: 35,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Lightweight',
    component_slots: 4,
    sockets: 4,
    description: 'Alterian flexible crystal suit that hardens instantaneously upon kinetic or thermal impact, dispersing shockwaves.',
    mechanic: 'Impact Hardening (Gain DR 20 against single highest damage attack per round). DR 14, SP 35.'
  },
  {
    id: 'inquisitor-mind-plate',
    name: 'Inquisitor\'s Mind-Plate',
    category: 'armoring',
    tl: 4,
    ml: 3,
    cost: 23525,
    craft_dc: 28,
    design_dc: 28,
    dr: 25,
    sp: 70,
    durability: 70,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Heavyweight',
    component_slots: 10,
    sockets: 10,
    description: 'Heavy armor worn by Ascendancy Inquisitors with built-in psi-amplifiers and anti-telepathic dampeners.',
    mechanic: 'Telepathic Immunity (Wearer is immune to telepathic detection and mind-reading). DR 25, SP 70.'
  },
  {
    id: 'polymatter-liquid-suit',
    name: 'Polymatter "Liquid" Suit',
    category: 'armoring',
    tl: 5,
    ml: 0,
    cost: 40960,
    craft_dc: 30,
    design_dc: 30,
    dr: 20,
    sp: 50,
    durability: 50,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Lightweight',
    component_slots: 8,
    sockets: 8,
    description: 'Nanofabricated morphic fluid suit that flows over the user\'s body in seconds, adapting to any environmental or combat threat.',
    mechanic: 'Adaptive Resistance (Switch damage type resistance as a Free Action). DR 20, SP 50.'
  },
  {
    id: 'holophotonic-emitter-harness',
    name: 'Holophotonic Emitter Harness',
    category: 'armoring',
    tl: 5,
    ml: 0,
    cost: 163840,
    craft_dc: 35,
    design_dc: 35,
    dr: 30,
    sp: 60,
    durability: 60,
    body_locations: ['Head', 'Torso', 'Arms', 'Legs'],
    coverage: 'Sealed',
    category: 'Mediumweight',
    component_slots: 10,
    sockets: 10,
    description: 'Lightweight wearable harness projecting a rigid barrier of solid hard-light around the user, absorbing high-caliber projectiles and energy beams.',
    mechanic: 'Hard-Light Barrier (Regenerates 10 SP per minute when powered). DR 30, SP 60.'
  }
];

for (const arm of armoringEntries) {
  writeEntry('armoring', arm.id, arm, `${arm.description}\n\n**Mechanics:** ${arm.mechanic}`);
}

// -------------------------------------------------------------
// 3. GEAR & EQUIPMENT FROM ECONOMATRIX
// -------------------------------------------------------------
const gearEntries = [
  {
    id: 'biotech-device-generic',
    name: 'Biotech Device (Generic Chassis)',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 2560,
    craft_dc: 20,
    size: 'Tiny',
    weight: 0.5,
    description: 'Grown rather than manufactured device with organic neural pathways.',
    mechanic: 'Regeneration trait (Regenerates 1 HP/hour). Feeding organic matter repairs 1d4 HP instantly (requires Trained Xenobiology).'
  },
  {
    id: 'programmable-matter-device',
    name: 'Programmable Matter Device (Picotech)',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 10240,
    craft_dc: 25,
    size: 'Diminutive',
    weight: 0.2,
    description: 'A canister of "smart sand" or fluid picotech metal capable of taking structural form.',
    mechanic: 'Reshapes into any Simple tool of Tiny size with Electronics check. [Morphic]: Stores up to 3 Blueprints to switch between as Free Action.'
  },
  {
    id: 'image-projector',
    name: 'Image Projector (Analog/Digital)',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 40,
    craft_dc: 5,
    size: 'Tiny',
    weight: 0.5,
    description: 'Projects a static or looped 2D image and basic audio onto flat surfaces.',
    mechanic: 'Visual projection up to 10m. Easily detected as artificial (Perception DC 10).'
  },
  {
    id: 'holo-emitter',
    name: 'Holo Emitter (Volumetric)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Tiny',
    weight: 0.5,
    description: 'Projects high-fidelity 3D holographic illusions and binaural directional audio.',
    mechanic: 'Projects volumetric image within Close (10m) range. Grants +2 to Deception checks for distractions.'
  },
  {
    id: 'holophotonic-projector',
    name: 'Holophotonic Projector (Hard Light)',
    category: 'gear',
    tl: 5,
    ml: 0,
    cost: 40960,
    craft_dc: 30,
    size: 'Small',
    weight: 2.0,
    description: 'Creates tactile, solid hard-light matter with physical mass and rigid durability.',
    mechanic: 'Creates temporary physical cover (20 HP), furniture, or bridges. Dissolves if powered down.'
  },
  {
    id: 'enviro-suit',
    name: 'Enviro Suit',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Medium',
    weight: 4.0,
    description: 'Full body containment suit protecting against vacuum and radiation hazards.',
    mechanic: 'Provides EPR 3 (Vacuum/Radiation). Uses Supply Die (d10) for Oxygen and Power.'
  },
  {
    id: 'smart-suit',
    name: 'Smart Suit (Adaptive Nanotech)',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 2560,
    craft_dc: 20,
    size: 'Medium',
    weight: 2.5,
    description: 'Nanotech weave that dynamically identifies and adapts to environmental hazards.',
    mechanic: 'As a Reaction, adapts resistance to provide EPR 4 against specific environmental threats (Heat, Cold, Acid).'
  },
  {
    id: 'backpack-storage-unit',
    name: 'Backpack / Tactical Storage Unit',
    category: 'gear',
    tl: 1,
    ml: 0,
    cost: 40,
    craft_dc: 5,
    size: 'Small',
    weight: 1.0,
    description: 'Ruggedized canvas and polymer pack for carrying personal supplies and expedition gear.',
    mechanic: 'Increases personal carrying capacity by +2 Slots / Sockets.'
  },
  {
    id: 'clothing-high-fashion',
    name: 'Clothing (High Fashion)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Medium',
    weight: 1.0,
    description: 'Designer social attire woven from luminescent and tailored prestige fabrics.',
    mechanic: 'Prestige status symbol. Grants +1 to Social & Etiquette checks in elite society.'
  },
  {
    id: 'glow-rod-flashlight',
    name: 'Glow-Rod / High-Beam Flashlight',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 10,
    craft_dc: 2,
    size: 'Diminutive',
    weight: 0.2,
    description: 'Chemical or LED high-luminescence torch providing bright illumination.',
    mechanic: 'Illuminates a 20ft radius cone/sphere for 12 hours.'
  },
  {
    id: 'restraints-zip',
    name: 'Zip Restraints (Pack of 10)',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 5,
    craft_dc: 2,
    size: 'Diminutive',
    weight: 0.1,
    description: 'High-tensile nylon locking ties for securing prisoners.',
    mechanic: 'Single use. Requires Strength DC 20 to break.'
  },
  {
    id: 'restraints-mag',
    name: 'Mag Restraints (Electronic)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Tiny',
    weight: 0.5,
    description: 'Biometric magnetic lock cuffs for high-security prisoner containment.',
    mechanic: 'Reusable. Requires Strength DC 25 to break or Hack / Electronics DC 20 to open.'
  },
  {
    id: 'datapad',
    name: 'Standard Datapad',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 40,
    craft_dc: 5,
    size: 'Tiny',
    weight: 0.3,
    computer_pr: 0,
    description: 'Personal touchscreen computing tablet for accessing maps, local data networks, and files.',
    mechanic: 'Processor Rating 0. Stores local files and connects to planetary nets.'
  },
  {
    id: 'basic-processor',
    name: 'Basic Cyberdeck Processor',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Tiny',
    weight: 0.5,
    computer_pr: 0,
    description: 'Entry-level processing unit capable of running basic software scripts.',
    mechanic: 'PR 0. Can run standard automated operations scripts.'
  },
  {
    id: 'upgraded-processor',
    name: 'Upgraded Cyberdeck Processor',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Small',
    weight: 1.0,
    computer_pr: 2,
    description: 'High-speed quantum co-processing unit capable of executing expert software programs.',
    mechanic: 'PR 2. Capable of hosting and running Expert Software algorithms.'
  },
  {
    id: 'advanced-processor',
    name: 'Advanced AI Cyberdeck Processor',
    category: 'gear',
    tl: 5,
    ml: 0,
    cost: 10240,
    craft_dc: 25,
    size: 'Small',
    weight: 1.5,
    computer_pr: 4,
    description: 'State-of-the-art neuro-synthetic crystalline processor designed to host True AI agents.',
    mechanic: 'PR 4. Capable of running full True AI and advanced intrusion suites.'
  },
  {
    id: 'auto-doc-unit',
    name: 'Auto-Doc Unit (Robotic Pod)',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 2560,
    craft_dc: 20,
    size: 'Medium',
    weight: 25.0,
    description: 'Automated surgical and trauma treatment station with micro-manipulator arms.',
    mechanic: 'Runs Operation Software (Medicine Rank 10). Stabilizes dying patients and performs surgery autonomously.'
  },
  {
    id: 'portable-nurse-drone',
    name: 'Portable Nurse Drone',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Small',
    weight: 3.0,
    description: 'Hovering triage assistant equipped with diagnostic sensors and surgical supply dispensers.',
    mechanic: 'Runs Expert Software (Medicine). Grants +2 Aid Bonus to a character making a Medicine check.'
  },
  {
    id: 'regen-tank',
    name: 'Regen-Tank (Bacta Submersion)',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 10240,
    craft_dc: 25,
    size: 'Large',
    weight: 150.0,
    description: 'Medical submersion vat filled with accelerated nutrient fluid for deep cellular regeneration.',
    mechanic: 'Heals 1 HP per hour; fully regrows lost limbs or synthetic tissues during extended rest.'
  },
  {
    id: 'trauma-patch',
    name: 'Trauma Patch (Slap-Patch)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Diminutive',
    weight: 0.1,
    description: 'Emergency adhesive dermal patch releasing clotting enzymes and stabilizers.',
    mechanic: 'Instantly stabilizes a Dying character and stops Bleeding. 1 Single Use.'
  },
  {
    id: 'med-gel',
    name: 'Med-Gel (Bio-Foam Sealant)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Diminutive',
    weight: 0.2,
    description: 'Aerosol antiseptic bio-foam that seals puncture wounds and knits torn flesh.',
    mechanic: 'Restores 1d6 HP instantly on application. 1 Single Use.'
  },
  {
    id: 'stim-shot',
    name: 'Stim-Shot (Combat Adrenaline)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 40,
    craft_dc: 5,
    size: 'Diminutive',
    weight: 0.1,
    description: 'Neural stimulant injector purging fatigue and trauma shock.',
    mechanic: 'Removes Exhausted or Dazed conditions for 1 hour. Character suffers crash (-2 to checks) afterwards.'
  },
  {
    id: 'first-aid-kit',
    name: 'First Aid Kit',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 40,
    craft_dc: 5,
    size: 'Small',
    weight: 1.0,
    description: 'Bandages, antiseptics, tourniquets, and basic splints.',
    mechanic: 'Allows Medicine checks to be made without Improvised Tool penalties.'
  },
  {
    id: 'medkit-full',
    name: 'Medkit (Full Field Kit)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Small',
    weight: 2.0,
    description: 'Comprehensive paramedic field kit with diagnostic wand, cauterizer, and stims.',
    mechanic: '+1 Bonus to Medicine checks. Contains 5 clinical uses.'
  },
  {
    id: 'hand-scanner-tricorder',
    name: 'Hand Scanner (Multispectral)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Tiny',
    weight: 0.5,
    description: 'Handheld active sensor array analyzing biological, radiation, and geological signatures.',
    mechanic: 'Active sensor scanning within 50ft radius. Identifies atmospheric toxicity and life signs.'
  },
  {
    id: 'comm-link-audio',
    name: 'Comm-Link (Subdermal / Ear-Piece)',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 40,
    craft_dc: 5,
    size: 'Diminutive',
    weight: 0.1,
    description: 'Short-range encrypted audio transceiver.',
    mechanic: '1-mile tactical line-of-sight range; global when linked to satellite or planetary grid.'
  },
  {
    id: 'comm-unit-telepathic',
    name: 'Comm Unit (Telepathic Bio-Node)',
    category: 'gear',
    tl: 5,
    ml: 2,
    cost: 10240,
    craft_dc: 25,
    size: 'Tiny',
    weight: 0.2,
    description: 'Organic psycho-resonant crystal allowing silent psychic transmission across space.',
    mechanic: 'Silent, un-jammable communication. Requires Trained Telepathy or Metafocus.'
  },
  {
    id: 'rations-dehydrated',
    name: 'Rations (Dehydrated Pack)',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 10,
    craft_dc: 0,
    size: 'Diminutive',
    weight: 0.5,
    description: 'Nutrient-dense synthetic ration blocks sustaining an operative for 1 day.',
    mechanic: 'Restores Supply Die for 1 day of survival.'
  },
  {
    id: 'water-purifier',
    name: 'Water Purifier (Portable)',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 40,
    craft_dc: 5,
    size: 'Tiny',
    weight: 0.5,
    description: 'Micro-filter and UV sterilizer converting irradiated or stagnant water to potable water.',
    mechanic: 'Filters 10 liters per hour of toxic water into safe drinking water.'
  },
  {
    id: 'thermal-blanket',
    name: 'Thermal Blanket (Reflective)',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 20,
    craft_dc: 2,
    size: 'Diminutive',
    weight: 0.2,
    description: 'High-efficiency thermal retention foil reflecting 98% of radiated body heat.',
    mechanic: 'Grants Advantage on Survival checks vs. Extreme Cold.'
  },
  {
    id: 'enviro-tent',
    name: 'Enviro-Tent (Hermetic Shelter)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Medium',
    weight: 5.0,
    description: 'Inflatable hermetically sealed shelter with air scrubbers sheltering 4 operatives.',
    mechanic: 'Provides full life support and atmospheric seal against hostile biospheres for 4 occupants.'
  },
  {
    id: 'enviro-field-generator',
    name: 'Enviro Field Generator',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Small',
    weight: 3.0,
    description: 'Deployable pylon projecting a 20ft atmospheric protection dome.',
    mechanic: 'Projects 20ft radius dome. EPR 1. Provides DR 1 against ranged kinetic fire.'
  },
  {
    id: 'rebreather-air-mask',
    name: 'Rebreather / Air Mask',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Tiny',
    weight: 0.5,
    description: 'Facial mask recycling exhaled carbon dioxide and filtering atmospheric toxins.',
    mechanic: 'Filters toxins (EPR 2). Contains 2 hours of internal emergency oxygen.'
  },
  {
    id: 'mag-boots',
    name: 'Mag-Boots',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Small',
    weight: 2.0,
    description: 'Electromagnetic clamp boots securing feet to ferrous hull surfaces.',
    mechanic: 'Enables walking on metal hulls in Zero-G at half standard movement speed.'
  },
  {
    id: 'grav-chute',
    name: 'Grav-Chute (Drop Harness)',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Small',
    weight: 3.0,
    description: 'Backpack anti-gravity emitter arresting terminal velocity for orbital or high-altitude drops.',
    mechanic: 'Completely negates falling damage upon deployment.'
  },
  {
    id: 'basic-tool-kit',
    name: 'Basic Tool Kit',
    category: 'gear',
    tl: 2,
    ml: 0,
    cost: 40,
    craft_dc: 5,
    size: 'Small',
    weight: 2.0,
    description: 'Wrenches, screwdrivers, soldering iron, and manual fabrication tools.',
    mechanic: 'Required to make Engineering and Repair checks without penalty.'
  },
  {
    id: 'mechanics-kit-powered',
    name: 'Mechanics Kit (Powered)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Small',
    weight: 3.5,
    description: 'Pneumatic drivers, laser calibrators, and sonic torque wrenches.',
    mechanic: '+1 Bonus to Engineering and Repair checks.'
  },
  {
    id: 'fusion-cutter',
    name: 'Fusion Cutter (Heavy Torch)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Small',
    weight: 4.0,
    description: 'Industrial high-temperature plasma arc cutter slicing through hardened hull plating.',
    mechanic: 'Deals 1d10 Structure Points of damage per round to barriers and armor.'
  },
  {
    id: 'multi-tool',
    name: 'Multi-Tool (Pocket Utility)',
    category: 'gear',
    tl: 3,
    ml: 0,
    cost: 160,
    craft_dc: 10,
    size: 'Diminutive',
    weight: 0.3,
    description: 'Foldable precision alloy multi-tool with wire-strippers, blades, and sensors.',
    mechanic: 'Replicates any non-powered hand tool.'
  },
  {
    id: 'omni-tool-programmable',
    name: 'Omni-Tool (Programmable Holographic)',
    category: 'gear',
    tl: 4,
    ml: 0,
    cost: 640,
    craft_dc: 15,
    size: 'Tiny',
    weight: 0.5,
    description: 'Forearm-mounted holographic and micro-fabrication apparatus replicating power tools.',
    mechanic: 'Replicates powered hand tools. Grants +2 Bonus to Engineering checks.'
  },
  {
    id: 'polymorphic-liquid-metal-tool',
    name: 'Polymorphic Liquid Metal Tool',
    category: 'gear',
    tl: 5,
    ml: 0,
    cost: 10240,
    craft_dc: 25,
    size: 'Tiny',
    weight: 0.5,
    description: 'Smart matter tool flowing instantaneously into any custom scanner, key, or precision instrument.',
    mechanic: 'Can transform into any scanner or mechanical tool. Grants +4 Bonus to Engineering/Repair checks.'
  }
];

for (const g of gearEntries) {
  writeEntry('gear', g.id, g, `${g.description}\n\n**Mechanics:** ${g.mechanic}`);
}

// -------------------------------------------------------------
// 4. MECHA & VEHICLES FROM ECONOMATRIX
// -------------------------------------------------------------
const mechaEntries = [
  // Personal mobility & light vehicles
  {
    id: 'standard-skateboard-longboard',
    name: 'Standard Skateboard / Longboard',
    domain: 'Ground',
    size: 'Tiny',
    frame: 'Personal',
    tl: 1,
    cost: 10,
    craft_dc: 1,
    sp: 10,
    dr: 2,
    mounts: 0,
    propulsion: 'Manual (Push)',
    description: 'Urban deck for quick transit on paved surfaces. Grants increased movement on smooth, flat terrain.',
    mechanic: 'Movement x1.5 on paved streets. Manual propulsion.'
  },
  {
    id: 'cycle-rugged-frame',
    name: 'Cycle (Rugged Wilderness)',
    domain: 'Ground',
    size: 'Medium',
    frame: 'Personal',
    tl: 1,
    cost: 20,
    craft_dc: 2,
    sp: 20,
    dr: 4,
    mounts: 1,
    propulsion: 'Manual (Pedal/Gear)',
    description: 'Ruggedized bicycle frame with suspension and cargo rack for wilderness traversal.',
    mechanic: 'Movement x2 on roads/trails. Includes cargo rack (holds 2 Slots).'
  },
  {
    id: 'surfboard-wave-rider',
    name: 'Surfboard / Wave-Rider',
    domain: 'Aquatic',
    size: 'Medium',
    frame: 'Personal',
    tl: 1,
    cost: 20,
    craft_dc: 2,
    sp: 15,
    dr: 2,
    mounts: 0,
    propulsion: 'Environmental (Wave/Current)',
    description: 'Composite hydrodynamic board for riding wave energy and coastal currents.',
    mechanic: 'Speed equal to current speed. Requires Athletics (Swim) to maneuver.'
  },
  {
    id: 'segway-gyro-pod',
    name: 'Segway / Gyro-Pod',
    domain: 'Ground',
    size: 'Small',
    frame: 'Personal',
    tl: 3,
    cost: 40,
    craft_dc: 3,
    sp: 25,
    dr: 5,
    mounts: 0,
    propulsion: 'Micro-Motor (Electric)',
    description: 'Self-balancing personal mover for arcology station or city concourse transit.',
    mechanic: 'Micro-motor with gyro-stabilizer. 8 hours continuous electric range.'
  },
  {
    id: 'jet-hoverboard-skimmer',
    name: 'Jet-Powered Hoverboard (Skimmer)',
    domain: 'Ground / Hover',
    size: 'Small',
    frame: 'Personal',
    tl: 3,
    cost: 160,
    craft_dc: 10,
    sp: 30,
    dr: 6,
    mounts: 1,
    propulsion: 'Vectored Thrust (Micro-Turbine)',
    description: 'Repulsor hover-board skimming 1 foot above terrain using directed micro-turbines.',
    mechanic: 'Skims over water/ground at high speed. Pilot Agility +2.'
  },
  {
    id: 'officers-hover-platform',
    name: 'Officer\'s Hover Platform',
    domain: 'Hover',
    size: 'Small',
    frame: 'Platform',
    tl: 4,
    cost: 640,
    craft_dc: 15,
    sp: 50,
    dr: 12,
    mounts: 2,
    propulsion: 'Grav-Plate (Silent)',
    description: 'Floating armored command disk keeping overseers elevated above the fray.',
    mechanic: 'Silent anti-gravity platform with tactical shield and comms array.'
  },
  {
    id: 'subcompact-commuter',
    name: 'Subcompact Electric Commuter',
    domain: 'Ground',
    size: 'Medium',
    frame: 'Personal',
    tl: 3,
    cost: 160,
    craft_dc: 10,
    sp: 40,
    dr: 8,
    mounts: 2,
    propulsion: 'Micro-Motor (Electric)',
    description: 'The ubiquitous automated pod car of futuristic metropolitan arcologies.',
    mechanic: 'Seats 2. Automated traffic grid autopilot. Printable composite hull.'
  },
  {
    id: 'personal-hover-pod-bubble',
    name: 'Personal Hover Pod (The "Bubble")',
    domain: 'Hover / Flight',
    size: 'Medium',
    frame: 'Personal',
    tl: 4,
    cost: 2560,
    craft_dc: 20,
    sp: 60,
    dr: 10,
    mounts: 3,
    propulsion: 'Grav-Drive',
    description: 'Enclosed glass-sphere transport for comfortable city or atmospheric flight.',
    mechanic: 'Full Grav-Drive flight, life support seal, autopilot, holds 50kg stowage.'
  },
  // Ground combat & vehicles
  {
    id: 'main-battle-tank-standard',
    name: 'Main Battle Tank (Standard)',
    domain: 'Ground',
    size: 'Huge',
    frame: 'Industrial',
    tl: 3,
    cost: 40960,
    craft_dc: 30,
    sp: 500,
    dr: 40,
    mounts: 10,
    propulsion: 'Heavy Treads / Multi-Fuel Turbine',
    description: 'Tracked armored combat vehicle mounting a massive kinetic cannon and heavy frontal composite plating.',
    mechanic: 'Heavy Kinetic Cannon (4d10), Coaxial Autocannon (2d8), Heavy Frontal Armor (DR 40).'
  },
  {
    id: 'advanced-grav-tank',
    name: 'Advanced Grav-Tank',
    domain: 'Hover / Ground',
    size: 'Huge',
    frame: 'Industrial',
    tl: 4,
    cost: 163840,
    craft_dc: 35,
    sp: 600,
    dr: 45,
    mounts: 12,
    propulsion: 'Anti-Gravity Repulsor Repulsion',
    description: 'Floating armored fortress moving effortlessly across water, mud, and minefields armed with particle beams.',
    mechanic: 'Particle Beam Cannon (5d10), High Mobility Strafing, Active Energy Shields (DR 45).'
  },
  {
    id: 'modular-heavy-battle-walker',
    name: 'Modular Heavy Battle Walker (Mech)',
    domain: 'Ground',
    size: 'Huge',
    frame: 'Walker',
    tl: 3,
    cost: 40960,
    craft_dc: 30,
    sp: 450,
    dr: 35,
    mounts: 8,
    propulsion: 'Bipedal Hydraulic Actuators',
    description: '10-meter tall bipedal war machine with modular weapon hardpoints for missiles, autocannons, and lasers.',
    mechanic: 'Hydraulic stride, modular weapon pods, cockpit jump-jets.'
  },
  {
    id: 'super-heavy-assault-mech',
    name: 'Super-Heavy Assault Mech (100-Ton)',
    domain: 'Ground',
    size: 'Gargantuan',
    frame: 'Walker',
    tl: 4,
    cost: 655360,
    craft_dc: 40,
    sp: 1200,
    dr: 50,
    mounts: 16,
    propulsion: 'Reinforced Bipedal Servos',
    description: '100-ton walking juggernaut designed to anchor front lines and shatter fortified garrisons.',
    mechanic: 'Ablative composite plating (DR 50), dual Heavy Plasma Cannons (6d10), missile batteries.'
  },
  {
    id: 'bipedal-recon-walker',
    name: 'Bipedal Recon Walker',
    domain: 'Ground',
    size: 'Large',
    frame: 'Walker',
    tl: 3,
    cost: 10240,
    craft_dc: 25,
    sp: 200,
    dr: 20,
    mounts: 4,
    propulsion: 'Reverse-Joint Bipedal Legs',
    description: 'Fast, agile scout walker with reverse chicken-leg joints and high-gain sensory mast.',
    mechanic: 'High-speed scouting, jump-jets, chin-mounted twin light lasers (2d6).'
  },
  {
    id: 'fast-tramp-freighter',
    name: 'Fast Tramp Freighter',
    domain: 'Space',
    size: 'Gargantuan',
    frame: 'Platform',
    tl: 3,
    cost: 655360,
    craft_dc: 40,
    sp: 2000,
    dr: 30,
    mounts: 20,
    propulsion: 'Fusion Torch & Hyperdrive',
    description: 'Modified light cargo ship with oversized sublight engines, shielded smuggling compartments, and defensive turrets.',
    mechanic: 'Holds 20 Modules of cargo. Shielded smuggler bays (Disadvantage to authority scans).'
  },
  {
    id: 'multi-role-starfighter',
    name: 'Multi-Role Starfighter',
    domain: 'Space / Atmospheric',
    size: 'Large',
    frame: 'Winged',
    tl: 4,
    cost: 163840,
    craft_dc: 35,
    sp: 300,
    dr: 25,
    mounts: 6,
    propulsion: 'Ion Drive & FTL Jump Ring',
    description: 'Single-seat space superiority fighter capable of atmospheric dogfighting and void strikes.',
    mechanic: 'Twin Lasers (3d8), Proton Torpedo Launcher, Atmospheric Flight & Void Shields.'
  }
];

for (const m of mechaEntries) {
  writeEntry('mecha', m.id, m, `${m.description}\n\n**Mechanics:** ${m.mechanic}`);
}

console.log('Ingestion of canonical items complete!');
