export const creationArticles = [
  {
    id: '1-01-character-creation-pipeline',
    name: '1.01 Character Creation Pipeline & Derivations',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 1,
    description: [
      '# 1.01 Character Creation Pipeline & Derivations',
      '',
      'Creating a character in Tangent Science Fantasy Roleplay is an additive, modular process that blends species biology, cultural upbringing, faction alignment, and professional vocation into a cohesive Persona.',
      '',
      '---',
      '',
      '## The 8-Step Character Creation Pipeline',
      '',
      '1. **Concept & Archetype:** Define your character concept (e.g. Cyber-Samurai, Psionic Diplomat, Void Scout, Alien Scholar).',
      '2. **Species Selection:** Choose a Species. Apply inherent attribute modifiers, bonus skill pools, species traits, and size/movement profiles.',
      '3. **Core Attributes:** Distribute starting Build Points (BP) across the 6 Core Attributes (*STR, AGI, STA, INT, WIS, CHA*).',
      '4. **Faction Selection (20 SP):** Choose a Faction. Allocate the **20 Faction Skill Points** and select 2 Faction Features (with 1 BP discount).',
      '5. **Origin Selection (20 SP):** Choose an Origin environment. Allocate the **20 Origin Skill Points** and choose 2 Origin Traits.',
      '6. **Occupation Selection (20 SP):** Choose an Occupation. Allocate the **20 Professional Skill Points**, choose 2 Occupational Traits, and select Recommended Features.',
      '7. **Hindrances (Up to +15 BP):** Select optional Hindrances to flesh out narrative flaws and earn bonus Build Points.',
      '8. **Gear, Tech & Derived Stats:** Calculate maximum Hit Points, Armor DR, Initiative, Saving Throws, and equip weapons/armor based on Wealth score.',
      '',
      '---',
      '',
      '## Derived Combat & Survival Statistics',
      '',
      '| Statistic | Calculation Formula | Description |',
      '| :--- | :--- | :--- |',
      '| **Max Hit Points (HP)** | $\\text{Base (10)} + (\\text{Stamina Mod} \\times 2) + \\text{Rank Multipliers}$ | Total physical trauma capacity |',
      '| **Initiative Check** |  + \\text{Reflex Save} + \\text{Agility Mod}$ | Reaction speed at start of combat |',
      '| **Might Check** |  + \\text{Strength Mod} + \\text{Athletics Rank}$ | Physical power, breaking DC, grappling |',
      '| **Fortitude Save** |  + \\text{Stamina Mod} + \\text{Survival Rank}$ | Resistance to poison, shock, radiation |',
      '| **Reflex Save** |  + \\text{Agility Mod} + \\text{Acrobatics Rank}$ | Evasion of blast radii and traps |',
      '| **Logic Check** |  + \\text{Intellect Mod} + \\text{Science/Tech Rank}$ | Deductive analysis and computation |',
      '| **Will Save** |  + \\text{Wisdom Mod} + \\text{Alertness Rank}$ | Mental grit, fear, and psionic defense |',
      '| **Etiquette Check** |  + \\text{Charisma Mod} + \\text{Culture Rank}$ | Social poise and diplomatic standing |'
    ].join('\n'),
    mechanic: 'BaseHP = 10 + (StaminaMod * 2) + (Level * ClassHealthFactor)\nInitiative = d20 + AgilityMod + ReflexSaveMod',
    guide: 'Follow steps 1 through 8 in order. Record each 20-point pool separately to ensure compliance with creation limits.',
    note: 'Architects should verify that starting skills do not exceed Rank 6 without explicit backstory justification.'
  },
  {
    id: '1-02-skill-point-economy',
    name: '1.02 Skill Point Economy & Allocation Pools',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 2,
    description: [
      '# 1.02 Skill Point Economy & Allocation Pools',
      '',
      'Skills in Tangent represent formal training, reflex conditioning, and practical experience. All skill ranks are purchased with **Skill Points (SP)** or **Build Points (BP)**.',
      '',
      '---',
      '',
      '## The Three 20-Point Pools',
      '',
      'Every starting character receives three separate, non-transferable pools of 20 Skill Points:',
      '',
      '| Pool Name | Source | Purpose | Allowable Skills |',
      '| :--- | :--- | :--- | :--- |',
      '| **Faction Pool** | Faction / Polity | Cultural, political, and doctrinal training | Listed under chosen Faction |',
      '| **Origin Pool** | Birthworld / Habitat | Survival, environmental adaptation, navigation | Listed under chosen Origin |',
      '| **Occupation Pool** | Career / Profession | Technical, combat, and vocational expertise | Listed under chosen Occupation |',
      '',
      '---',
      '',
      '## Skill Rank Limits & Creation Caps',
      '',
      '- **Cost:** **1 SP = 1 Skill Rank** (or 1 BP = 1 Skill Rank if using general Build Points).',
      '- **Recommended Creation Baseline:** No skill should exceed **Rank 6 (Trained / Professional)** at character creation.',
      '- **Maximum Creation Hard Cap:** Under no circumstance may any starting skill exceed **Rank 11 (Expert)** at character creation.',
      '- Ranks 12–30 are unlocked exclusively through in-game gameplay, progression milestones, and experience rewards.'
    ].join('\n'),
    mechanic: 'SkillRank_CreationMax = 11\nSkillRank_CreationRecommended = 6\nTotalStartingSkillPoints = 20(Faction) + 20(Origin) + 20(Occupation) = 60 SP',
    guide: 'Spend exactly 20 points within each respective category list. Do not pool points across different categories.',
    note: 'Limiting starting ranks to Rank 6 ensures characters have room for meaningful growth across multiple campaign arcs.'
  },
  {
    id: '1-03-feature-feat-acquisition',
    name: '1.03 Feature & Feat Acquisition Rules',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 3,
    description: [
      '# 1.03 Feature & Feat Acquisition Rules',
      '',
      'Features (also termed Feats or Perks) represent distinct capabilities, combat maneuvers, specialized augmentations, and metaphysical awakenings.',
      '',
      '---',
      '',
      '## Cost Structure & Discounts',
      '',
      '- **Standard Base Cost:** **3 Build Points (BP)** per Feature.',
      '- **Recommended Feature Discount:** If a Feature is listed in your **Occupation** or **Faction** recommended list, its cost is reduced by **1 BP** (Final Cost: **2 BP**).',
      '- **Minimum Cost:** A Feature can never cost less than **1 BP**, regardless of stacking discounts.',
      '',
      '---',
      '',
      '## Feature Classifications',
      '',
      '1. **Ability Features:** Enhance core physical or mental prowess (e.g. *Great Fortitude, Lightning Reflexes, Potent Might, Iron Will*).',
      '2. **Combat Features:** Unlock tactical weapon masteries, critical thresholds, and advanced maneuvers (e.g. *Point Blank Mastery, Dual Wielding, Cleave*).',
      '3. **Meta Features:** Awaken metaphysical disciplines or unlock advanced Invocations (e.g. *Awakened Discipline, Meta Resonance, Overchannel*).',
      '4. **General Features:** Broad utility perks covering wealth, connections, cybernetics, and familiars.',
      '5. **Ranked Features:** Features that can be purchased multiple times. Each purchase stacks benefits, capped by the character\'s linked Attribute or Skill Tier.'
    ].join('\n'),
    mechanic: 'Feature_BaseCost = 3 BP\nFeature_DiscountedCost = 2 BP (if Recommended)\nFeature_MinCost = 1 BP',
    guide: 'Check your Occupation and Faction sheets first to identify discounted Recommended Features before spending Build Points.',
    note: 'Ranked features should not exceed the character\'s attribute modifier or skill stage.'
  },
  {
    id: '1-04-factions-galactic-polities-codex',
    name: '1.04 Factions & Galactic Polities Codex',
    category: 'compendium',
    entry_type: 'Worldbuilding',
    parent: '1.00 CHARACTER CREATION',
    order: 4,
    description: [
      '# 1.04 Factions & Galactic Polities Codex',
      '',
      'Factions in Tangent represent the interstellar sovereign powers, megacorporate syndicates, monastic orders, and mercenary guilds that vie for control of the galaxy.',
      '',
      '---',
      '',
      '## Major Canonical Galactic Polities',
      '',
      '### 1. The Dracon Dynasty',
      '- **Archetype:** Feudal Space Monarchy / Dragon-Lord Technocracy.',
      '- **Core Philosophy:** *Protection, Patience, and Long-Term Stability.*',
      '- **Society Structure:** High Nobility (Draconic descendants) ruling over Knightly Dragoons and protected Commoners.',
      '- **Key Skills:** Politics, Piloting, Archaic Weapons, History, Etiquette.',
      '',
      '### 2. The Arcology Syndicates',
      '- **Archetype:** Hyper-Capitalist Megacorporate Coalition.',
      '- **Core Philosophy:** *Efficiency, Profitability, and Market Dominance.*',
      '- **Society Structure:** Board of Directors, Executive Officers, and Contracted Citizens.',
      '- **Key Skills:** Business, Computers, Technology, Modern Weapons, Deceit.',
      '',
      '### 3. The Cyber-Guilds of Technomancers',
      '- **Archetype:** Transhumanist Cyber-Collective.',
      '- **Core Philosophy:** *Transcendence through Synthesis of Flesh and Machine.*',
      '- **Society Structure:** Fabricators, Circuit-Monks, and Neural Enclaves.',
      '- **Key Skills:** Technology, Computers, Science, Cybernetics, Physics.',
      '',
      '### 4. The Holy Federation of Light',
      '- **Archetype:** Theocratic Galactic Concordat.',
      '- **Core Philosophy:** *Spiritual Purity, Cosmic Harmony, and Divine Law.*',
      '- **Society Structure:** Patriarchs, Inquisitors, Templars, and Faithful Laymen.',
      '- **Key Skills:** Religion, Metaphysics, Diplomacy, Fortitude, Will.',
      '',
      '---',
      '',
      '## The 25 Generic Organizational Templates',
      '',
      'Architects and Operators can utilize the **25 Generic Faction Templates** (e.g. Free Trader Consortium, Frontier Militia, Smuggler Ring, Research Institute) to rapidly construct custom organizations with ready-to-use 20 SP packages.'
    ].join('\n'),
    mechanic: 'Faction_SkillPool = 20 SP\nFaction_BonusFeatures = 2 (selected at 1 BP discount)',
    guide: 'Choose a faction that aligns with your character\'s cultural worldview, ethical code, and allegiances.',
    note: 'Faction standing affects social reaction DCs when dealing with rival or allied organizations.'
  },
  {
    id: '1-05-origins-habitats-codex',
    name: '1.05 Origins & Habitats Codex',
    category: 'compendium',
    entry_type: 'Worldbuilding',
    parent: '1.00 CHARACTER CREATION',
    order: 5,
    description: [
      '# 1.05 Origins & Habitats Codex',
      '',
      'A character\'s Origin defines their birthworld, native planetary biome, or orbital habitat. Origin environments instill instinctive survival mechanisms and physical conditioning.',
      '',
      '---',
      '',
      '## Canonical Origin Environments',
      '',
      '| Origin Name | Environment Profile | Key Society Skills | Example Origin Traits |',
      '| :--- | :--- | :--- | :--- |',
      '| **Agricultural (Agri-World)** | Low development, fertile plains, farm arcologies | Piloting, Alertness, Nature, Survival | *Green Thumb, Animal Husbandry, Farm Mech* |',
      '| **Arcology (Mega-City)** | Dense urban towers, neon corridors, artificial atmosphere | Computers, Stealth, Technology, Streetwise | *Urban Stalker, Grid Runner, Dense Crowd Evasion* |',
      '| **Asteroid Belt (Void Habitat)** | Zero-g mines, pressurized domes, cold vacuum | Piloting, Physics, Technology, Alertness | *Zero-G Acclimation, Vacuum Intuition, Seal Repair* |',
      '| **Death World (Hostile Ecology)** | Extreme predators, toxic flora, volatile tectonic cycles | Survival, Athletics, Alertness, Medicine | *Apex Predator Reflexes, Toxin Tolerance, Iron Gut* |',
      '| **High-Gravity World** | Crushing gravity, dense planetary core | Athletics, Might, Fortitude, Intimidation | *Dense Muscle Mass, Impact Resistance, Heavy Stride* |',
      '| **Low-Gravity / Void Station**| Microgravity, centrifugal rings, orbital platforms | Acrobatics, Piloting, Physics, Computers | *Light-Footed, Kinetic Drift, Micro-Thruster Mastery* |',
      '',
      '---',
      '',
      '## Origin Allotment Rules',
      '',
      '- **Origin Skill Pool:** **20 Skill Points** distributed among the origin\'s listed skills.',
      '- **Origin Traits:** Choose **Two Traits** from your native origin list at character creation.',
      '- **Secondary Origin:** An Operator may select a secondary origin to broaden trait options without receiving additional points.'
    ].join('\n'),
    mechanic: 'Origin_SkillPool = 20 SP\nOrigin_Traits = 2 (Inherent at creation)',
    guide: 'Select an origin that matches your character\'s physical conditioning and childhood background.',
    note: 'Environmental penalties (e.g. high-gravity, zero-g) do not apply to native origin characters.'
  },
  {
    id: '1-06-occupations-careers-codex',
    name: '1.06 Occupations & Careers Codex',
    category: 'compendium',
    entry_type: 'Worldbuilding',
    parent: '1.00 CHARACTER CREATION',
    order: 6,
    description: [
      '# 1.06 Occupations & Careers Codex',
      '',
      'An Occupation represents a character\'s career, formal trade, and role in society. It supplies professional skills, discounted recommended features, and career traits.',
      '',
      '---',
      '',
      '## Canonical Career Archetypes',
      '',
      '### 1. Adept (Metaphysic Specialist)',
      '- **Role:** Reality manipulation, psionic warfare, spiritual counseling.',
      '- **Professional Skills:** Attune, Known Metafocus Disciplines.',
      '- **Recommended Features:** Awakened Discipline, Meta Focus, Energy Channeling.',
      '',
      '### 2. Soldier (Tactical Combatant)',
      '- **Role:** Direct fire, heavy weapon deployment, squad coordination.',
      '- **Professional Skills:** Modern Weapons, Archaic Weapons, Tactics, Athletics, Armor.',
      '- **Recommended Features:** Toughness, Point Blank Mastery, Heavy Armor Training.',
      '',
      '### 3. Scout (Recon & Exploration)',
      '- **Role:** Pathfinding, infiltration, sniper overwatch, planetary survey.',
      '- **Professional Skills:** Stealth, Alertness, Navigation, Survival, Piloting.',
      '- **Recommended Features:** Lightning Reflexes, Camouflage Mastery, Eagle Eye.',
      '',
      '### 4. Scholar / Scientist (Research & Analysis)',
      '- **Role:** Forensics, astrophysics, xenobiology, historical deciphering.',
      '- **Professional Skills:** Academics, Science, Physics, Computers, Medicine.',
      '- **Recommended Features:** Mastermind, Fast Hacking, Analytical Deduction.',
      '',
      '### 5. Scoundrel (Subterfuge & Infiltration)',
      '- **Role:** Security bypassing, street economics, black-market procurement.',
      '- **Professional Skills:** Stealth, Deceit, Streetwise, Lockpicking, Sleight of Hand.',
      '- **Recommended Features:** Slippery, Hidden Pocket, Quick Draw.',
      '',
      '---',
      '',
      '## Occupational Rules',
      '',
      '- **Professional Skill Pool:** **20 Skill Points** allocated to occupational skills.',
      '- **Occupational Traits:** Select **Two Traits** from your career archetype.',
      '- **Cross-Training (Background Trait):** Take the *Background* trait to acquire training from a secondary occupation.'
    ].join('\n'),
    mechanic: 'Occupation_SkillPool = 20 SP\nOccupation_Traits = 2\nRecommendedFeatures_Discount = 1 BP',
    guide: 'Distribute your 20 professional SP across career skills to establish your primary in-game competencies.',
    note: 'Characters can multiclass or take on new occupations during long campaign downtime periods.'
  },
  {
    id: '1-07-master-skills-codex',
    name: '1.07 Master Skills Codex & Benchmarks',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 7,
    description: [
      '# 1.07 Master Skills Codex & Benchmarks',
      '',
      'Skills are organized into **5 Major Skill Groups**. Every rank adds a +1 bonus to task resolution checks.',
      '',
      '---',
      '',
      '## Master Skill Directory',
      '',
      '### I. Physical Skills (STR / AGI)',
      '- **Acrobatics (AGI):** Tumbling, balance, aerial maneuvers, fall mitigation.',
      '- **Athletics (STR/STA):** Sprinting, swimming, climbing, heavy lifting, physical endurance.',
      '- **Piloting (AGI/INT):** Starships, ground speeders, mecha, atmospheric craft.',
      '- **Stealth (AGI):** Hiding, silent movement, camouflage, shadow traversal.',
      '',
      '### II. Mental Skills (INT / WIS)',
      '- **Alertness (WIS):** Perception, hazard awareness, detecting hidden foes.',
      '- **Academics (INT):** Research, linguistics, humanities, ancient history.',
      '- **Computers (INT):** Cyber warfare, system intrusion, AI interaction, programming.',
      '- **Investigation (INT):** Forensics, crime scene analysis, deductive logic.',
      '- **Medicine (INT):** Combat triage, surgical intervention, pathology, cyber-surgery.',
      '- **Science (INT):** Chemistry, biology, xenology, planetary physics.',
      '- **Technology (INT):** Engineering, field repairs, weapon maintenance, fabrication.',
      '',
      '### III. Social Skills (CHA)',
      '- **Culture (CHA):** Etiquette, protocol, xenological customs.',
      '- **Deceit (CHA):** Bluffs, disguises, misdirection, undercover infiltration.',
      '- **Diplomacy (CHA):** Negotiation, treaties, conflict resolution, persuasion.',
      '- **Intimidation (STR/CHA):** Coercion, interrogation, psychological pressure.',
      '- **Streetwise (CHA/WIS):** Black market contacts, criminal underground navigation.',
      '',
      '### IV. Combat Skills (AGI / STR)',
      '- **Archaic Weapons (AGI/STR):** Swords, polearms, bows, thrown weapons.',
      '- **Modern Weapons (AGI):** Pistols, rifles, shotguns, submachine guns.',
      '- **Advanced / Heavy Weapons (STR/INT):** Plasma cannons, missile launchers, railguns.',
      '- **Unarmed Combat (STR/AGI):** Martial arts, brawling, grappling, subdual.',
      '- **Defense / Evasion (AGI):** Active dodges, parrying, kinetic deflection.',
      '',
      '### V. Metafocus Skills (INT / WIS / CHA)',
      '- **Attune (WIS/INT):** Drawing, channeling, and stabilizing metaphysical energy.',
      '- **Discipline Skills (6 Branches):** Dimension, Energy, Entropy, Illusion, Matter, Mental.'
    ].join('\n'),
    mechanic: 'SkillCheck = d20 + SkillRank + LinkedAttributeMod + SituationalModifiers\nFocusBonus: Rank 1-5 (+2), Rank 6-10 (+3), Rank 11-15 (+4), Rank 16-20 (+5), Rank 21-25 (+6), Rank 26-30 (+7)',
    guide: 'Roll d20 and add your skill rank plus the linked attribute modifier against the target DC.',
    note: 'Synergies: Having 5+ ranks in a prerequisite skill provides a +2 synergy bonus to related specialized checks.'
  },
  {
    id: '1-08-features-perks-master-codex',
    name: '1.08 Features & Perks Master Codex',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 8,
    description: [
      '# 1.08 Features & Perks Master Codex',
      '',
      'Features are modular special abilities that define unique heroic talents.',
      '',
      '---',
      '',
      '## Core Ability Features Table',
      '',
      '| Feature Name | Prerequisite | Effect & Mechanical Benefit | Category |',
      '| :--- | :--- | :--- | :--- |',
      '| **Great Fortitude** | Stamina 1+ | +2 bonus on all Fortitude saving throws | Ranked (Stamina) |',
      '| **Incredible Fortitude**| Great Fortitude | Roll all Fortitude saves with Advantage | Staged |',
      '| **Lightning Reflexes** | Agility 1+ | +2 bonus on Reflex checks and Initiative rolls | Ranked (Agility) |',
      '| **Superb Reflexes** | Lightning Reflexes | Roll all Reflex checks with Advantage | Staged |',
      '| **Potent Might** | Strength 1+ | +2 bonus on raw Might and Lift checks | Ranked (Strength) |',
      '| **Mighty Surge** | Potent Might | Roll raw Might checks with Advantage | Staged |',
      '| **Iron Will** | Wisdom 1+ | +2 bonus on Will saves and mental defense | Ranked (Wisdom) |',
      '| **Indomitable Will** | Iron Will | Roll all Will checks with Advantage | Staged |',
      '| **Insightful Reason** | Intellect 1+ | +2 bonus on Logic, Hack, and Forensic checks | Ranked (Intellect) |',
      '| **Inspiring Personality**| Charisma 1+ | +2 bonus on Etiquette and Leadership checks | Ranked (Charisma) |',
      '',
      '---',
      '',
      '## Combat & Tactical Features',
      '- **Point Blank Mastery:** Fire ranged weapons in melee reach without provoking Attacks of Opportunity; shots deal Advantage damage at point-blank range.',
      '- **Dual Weapon Mastery:** Attack with two weapons in a single action at a reduced -2 offhand penalty.',
      '- **Sniper Focus:** Take an aiming action to double the weapon\'s effective short range and ignore partial cover.'
    ].join('\n'),
    mechanic: 'Feature_Cost = 3 BP (2 BP if Recommended)\nRankedFeature_Cap = LinkedAttributeScore',
    guide: 'Choose features that complement your primary weapon systems, tactical roles, and attribute strengths.',
    note: 'Advantage granted by features does not stack; rolling twice is the maximum benefit.'
  },
  {
    id: '1-09-hindrances-karmic-debt-codex',
    name: '1.09 Hindrances & Karmic Debt Codex',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 9,
    description: [
      '# 1.09 Hindrances & Karmic Debt Codex',
      '',
      'Hindrances are character flaws, phobias, debts, and physical disabilities that grant bonus **Build Points (BP)** at character creation.',
      '',
      '---',
      '',
      '## Master Hindrance Value Directory',
      '',
      '| Hindrance | Bonus BP | Severity & Description |',
      '| :--- | :---: | :--- |',
      '| **Addiction** | 3 / 6 / 9 | Minor (3), Moderate (6), or Severe/Crippling (9) chemical dependency |',
      '| **Adversary / Nemesis**| 1 – 10 | Individual stalker (1–5) or powerful interstellar Syndicate (5–10) |',
      '| **Bodily Age (Child/Venerable)**| 5 / 10 | Physical penalties to STR/AGI/STA in exchange for social/knowledge perks |',
      '| **Covetous / Greed** | 3 / 6 / 9 | Compulsive greed, ambition, or treasure obsession |',
      '| **Dependent / Ward** | 3 / 6 / 9 | Innocent family member, AI core, or pet requiring constant protection |',
      '| **Disability (Limb)** | 3 / 6 / 9 / 18| Lost Hand/Foot (3), Full Limb (6), Multiple Limbs (9), Quadriplegic (18) |',
      '| **Distinctive Features** | 3 / 6 / 9 | Cybernetic scars, mutant pigmentation, or glowing biometric implants |',
      '| **Extreme Morality** | 4 / 8 / 12 | Rigid ethical code (Good, Lawful, Evil, Chaotic) that cannot be breached |',
      '| **Impaired / Lost Sense**| 3 / 6 / 9 | Lost Smell/Taste (3), Lost Touch/Hearing (6), Total Blindness (9) |',
      '| **Poor / Severe Debt** | 3 / 6 / 9 | -4 / -8 / -12 to starting Wealth; negative scores represent bounty debt |',
      '| **Unlucky (Karmic Debt)**| 3 / 6 / 9 | -2 / -4 / -6 penalty to maximum Karma pool |',
      '',
      '---',
      '',
      '## Rules on Hindrances',
      '',
      '- **Recommended Limit:** No character should take more than **15 BP** of Hindrances.',
      '- **Overcoming Hindrances:** A character may buy off a Hindrance during a campaign by paying its BP cost in experience points and completing a relevant story arc.'
    ].join('\n'),
    mechanic: 'Hindrance_MaxBonusBP = 15 BP\nWealthScore_Minimum = Can be negative (indicating syndicate debt/bounty)',
    guide: 'Select hindrances that spark compelling roleplay and dramatic tension during adventures.',
    note: 'Architects should actively integrate player hindrances into plot hooks and complication encounters.'
  }
];
