export const creationArticles = [
  {
    id: '1-01-character-creation-pipeline',
    name: '1.01 Character Creation System & Walkthrough',
    category: 'compendium',
    entry_type: 'Operator Rule',
    parent: '1.00 CHARACTER CREATION & ECONOMY',
    order: 1,
    description: [
      '# 1.01 Character Creation System & Walkthrough',
      '',
      'Players embark on a thrilling adventure where they hold the power to shape their character\'s destiny. This customization system grants players the freedom to craft unique and unforgettable characters that resonate with their playstyles and preferences.',
      '',
      'A diverse range of species awaits players, each possessing distinct attributes and abilities that influence the course of their journey. From Humans, known for their adaptability and resilience, to mystical Elves with an affinity for magic, the choice of species sets the foundation for a character\'s strengths and weaknesses.',
      '',
      'Furthermore, players can delve into a rich array of origins, uncovering the profound impact of their character\'s past on their present and guiding their future. Whether raised in a bustling metropolis, a serene village, or a nomadic tribe, each origin bestows unique advantages, disadvantages, features, and skills that shape a character\'s journey.',
      '',
      'The game further immerses players in a vibrant world populated by various factions and occupations. Aligning with a faction grants access to exclusive resources, training, and missions, allowing players to forge alliances and shape the political landscape. Additionally, choosing an occupation provides specialized skills and abilities tailored to specific playstyles. From skilled warriors to cunning rogues and wise scholars, each occupation offers a distinct path towards character development.',
      '',
      'Players have the ability to create characters that are not only powerful and effective but also possess intriguing personalities and captivating backstories. Every decision made during character creation has a lasting impact, ensuring that each character is truly unique and memorable. Every character is a reflection of the player\'s creativity and strategic thinking, making the journey through this immersive world a truly personal and unforgettable experience.',
      '',
      '---',
      '',
      '## CONCEPT',
      '',
      'To start the character creation process, players should first envision a general concept for their character. This involves thinking about several key aspects that will shape their character\'s identity and role in the game:',
      '',
      '### Background',
      'What is the character\'s background and upbringing? This includes their family, social status, education, and life experiences. Background will shape the character\'s personality, skills, and worldview.',
      '',
      '### Personality',
      'What kind of person is the character? Are they brave, cunning, compassionate, or something else entirely? Personality traits will guide the character\'s decisions and interactions with others.',
      '',
      '### Role',
      'What role will the character play in the game world? Will they be a hero, a villain, a supporting character, or something else? This will influence the character\'s goals, motivations, and the types of challenges they will face.',
      '',
      '> [!TIP]',
      '> **Example (Concept):**  ',
      '> *Xy\'larra is from a merchant clan of Alterian Elves, she is a seasoned diplomat with a thirst for exploration. She\'s driven by a deep curiosity about the vastness of the galaxy and a desire to forge connections with new cultures.*',
      '',
      '---',
      '',
      '## BUILD POINTS',
      '',
      '**Build Points (BP):** Players are given **150 Build Points** at the start of character creation. In addition to skill ranks and features gained from the character\'s Species, Faction, Origin or Occupation. These points are used to purchase various aspects of their character from any section they choose, including:',
      '',
      '- **Ability Scores:** The six basic ability scores, averages of 0. Ability Scores cost **5 BP** per +1.',
      '- **Species Package:** This includes the base species and any associated abilities or traits. BP Cost of Species package is variable.',
      '- **Faction, Origin and Profession:** These do not cost build points but will grant skills, features and traits. In total granting **60 skill ranks, 4 features and 4 traits** to ground the character with baseline traits, these are not ‘bonus’ but are foundational traits the character will likely need or have gained from being established.',
      '- **Technology:** No BP cost at Tech 3, costs to be more advanced (+10 BP for TL4, +20 BP for TL5 or -10 per TL under 3).',
      '- **Skills:** These represent a character\'s learned abilities and expertise. Skills cost **1 BP per rank**.',
      '- **Features:** These are special abilities or enhancements that can be acquired through various means. Features have a base cost of **3 BP** and adjusted by recommendations (minimum cost of 1 BP per feature).',
      '- **Hindrances:** Flaws and Drawbacks of a character to gain BP.',
      '- **Augmentations:** Enhanced with permanent cybernetic or bio-modifications. The Augmented feature (Augmented, Heavy, Severe) is required depending on stage of augmentation AND each augmentation costs **1 BP** as well.',
      '- **Meta Discipline:** Developing metaphysical capabilities, such as magic or psychic powers. The Awakened feature is required to access the metafocus disciplines and the special ability feature is to use specific evocation effects without deep training (regardless of the source).',
      '- **Property:** Equipped with essential tools and belongings. Property is obtained via the WEALTH score (secured transaction against the character\'s worth), CREDIT/cash/markers/etc in-game liquid currency for specific transactions, CRAFTING the items with the character or allies\' skills and materials, CONJURATION is using metafocus arts to create a temporary or permanent item (difference being if it is temporary there is no cost and it fades away after the scene or sooner. Permanent items will require BP purchase to be kept on the folio with other gear).',
      '',
      '> [!TIP]',
      '> **Example (Build Points):**  ',
      '> *Xy\'larra will have 150 BP to spend throughout the character creation.*',
      '',
      '---',
      '',
      '## ABILITY SCORES',
      '',
      'Every character is defined by six fundamental attributes. The standard baseline for an ordinary human is **+0**. During character creation, no raw attribute score may exceed **+4** before species adjustments or mechanical augmentations are applied.',
      '',
      '| Attribute | Attribute Check | Core Areas of Mechanical Influence |',
      '| :--- | :--- | :--- |',
      '| **Strength (STR)** | Might Check | Carrying/Lifting Capacity, Melee Damage, Raw Physical Force |',
      '| **Agility (AGI)** | Reflex Check | Ranged Weapon Accuracy, Evasion, Balance, Initiative |',
      '| **Stamina (STA)** | Fortitude Check | Toxic/Disease Resistance, Base Toughness, Vitality Buffer |',
      '| **Intellect (INT)** | Reason Check | Pure Logic, Technical Crafting, Scientific / Academic Knowledge |',
      '| **Wisdom (WIS)** | Willpower Check | Deception Detection, Focus, Fear Resistance, Intuition |',
      '| **Charisma (CHA)** | Etiquette Check | Leadership, Complex Negotiation, Social Magnetism, Karma Bounds |',
      '',
      '---',
      '',
      '## SPECIES',
      '',
      'The first step in character creation for the Tangent SFF RPG is to choose a **Species**.',
      '',
      '- **BP Cost:** Each species has a BP cost deducted from the starting pool of 150 BP.',
      '- **Ability Modifiers:** Each species has specific ability modifiers (positive or negative) that affect a character\'s base stats.',
      '- **Skill Ranks:** A species may be granted ranks in certain specific skills or skills chosen from a category, indicating the species focus in certain training.',
      '- **Racial Traits & Special Features:** Certain species may have access to unique racial traits or special features.',
      '- **Recommended Features:** Players can select from this list of features with a 1 BP reduction in cost (minimum of 1 BP for any feature).',
      '',
      '> [!TIP]',
      '> **Example (Species):**  ',
      '> *Xy\'larra is an Alterian (17 BP package - covering all traits of the species) and she will have the following modifiers:*  ',
      '> *Gain +1 Agility and +1 Intellect (Elven types are typically quite quick and intelligent). She is Awakened (her species specifically studies the Arcane with an Intellect basis and will gain a discipline and its skills) and also gains +10 Skill points for discipline related skills. Alterians are Humanoid with a Minor Xeno Stigma (humans will comparatively have a slightly different cultural view, -2 penalty on certain social interactions).*  ',
      '> - *Awakened in Mental with 5 points to Focus and 5 points to the Sensory Discipline (for meta enhanced perception and awareness).*',
      '',
      '---',
      '',
      '## FACTION',
      '',
      'The **Faction stage** of character creation in Tangent involves choosing a faction with which your character is affiliated. Each faction represents a distinct group or organization within the game world, with its own unique culture, goals, and resources.',
      '',
      '- **Faction Skill Points:** Each faction provides **20 Faction Skill Ranks** that can be allocated to specific skills relevant to that faction. This allows players to further specialize their character\'s abilities and tailor them to the faction\'s focus.',
      '- **Faction Features:** Factions can also offer a selection of **2 Recommended Features** that characters can choose from. These features represent special abilities, training, or equipment that are prominent to that faction.',
      '- **Faction Affiliation Benefits:** Aligning with a particular faction can provide various benefits, such as access to exclusive resources, support from other faction members, and opportunities for advancement within the faction\'s hierarchy.',
      '- **Faction Affiliation Drawbacks:** However, faction affiliation can also have drawbacks, such as conflicts with rival factions, obligations to the faction\'s leadership, and restrictions on certain actions or choices.',
      '',
      '> [!TIP]',
      '> **Example (Faction):**  ',
      '> *The Alterian Enclave, typical for most Alterians, is focused on diplomacy and exploration. Xy\'larra will gain the following options:*  ',
      '> *Technology is Spacefaring (Tech Level 3) with a Meta Level of 4 (focus of Arcane Enhancements). Her recommended skills (20 points allotment) are from Academics and the categories of Knowledges, Vocations and Disciplines. She will also gain 2 Features from the Discipline Category.*  ',
      '> - *She gains the skills of Academics 5, Culture 5 (Know), Ambassador 5 (Voc) and another 5 to her Sensory Discipline skill raising it to 10.*  ',
      '> - *She will also gain Awakened (for Both Dimensional and Entropy) with the 2 features gained in the Discipline category.*',
      '',
      '---',
      '',
      '## ORIGIN',
      '',
      'The **Origin stage** of character creation in Tangent involves selecting an origin that reflects the character\'s upbringing and background. This choice will influence their skills, traits, and overall worldview. Players can choose from a variety of origins, such as Colony, Leisure, or Militant, each with its own unique set of benefits and drawbacks.',
      '',
      '- **Skill Points:** Each origin comes with **20 Origin Skill Ranks** that can be distributed among a specific set of skills relevant to that origin. This allows players to tailor their character\'s abilities to their chosen background.',
      '- **Origin Traits:** Additionally, players can choose **2 Origin Traits** from a list of options associated with their selected origin. These traits represent specific characteristics or abilities that reflect the character\'s upbringing and experiences. (Traits from Origin and Occupation are interchangeable if befitting the character.)',
      '- **Additional Traits:** Players have the option to select additional traits beyond the initial two, but these come at a cost of **1 Build Point (BP) each**. This allows for further customization but requires careful consideration of the character\'s overall build and BP budget.',
      '',
      '> [!TIP]',
      '> **Example (Origin):**  ',
      '> *Xy\'larra is from a family of merchants and has been travelling the stars since she was young. Spacer origins fitting but due to the fact that she was raised in an Alterian Clan with traditional teachings she will gain Enlightened as a secondary origin (she will not gain any extra points but will gain access to the secondary list of suggested skills and traits to choose from).*  ',
      '> *She will gain 20 Skill Points to spend on any skills (with her Spacer origin having a better selection of skills than her Enlightened origin).*  ',
      '> *She will also gain 2 Traits total to choose from either origin (with her combined list of options being Combat Training, Independence, Leadership Skills, Pilot Skills, Resourcefulness, Smooth Talking, Technical Skills, Toughness, Empathy, Intellectual Curiosity, Mentorship, Open-Mindedness, Peaceful Nature, Problem-Solving Skills, Shared Wisdom and Spiritual Awareness).*  ',
      '> - *Wanting to be mobile she takes skills in Piloting 5, Navigation 5 (Know) and wanting to take care of herself she learns Defense 5 and Melee 5.*  ',
      '> - *The Traits of Open-Mindedness and Empathy are fitting traits from her compiled list. Any additional Origin traits desired will cost 1 BP each.*',
      '',
      '---',
      '',
      '## OCCUPATION',
      '',
      'The **Occupation stage** of character creation in Tangent involves selecting an occupation that reflects your character\'s profession and area of expertise. This choice not only adds flavor and depth to their identity but also grants them specific skills and abilities that reflect their training and experience.',
      '',
      '- **Skill Points:** Each occupation comes with **20 Occupational Skill Ranks** that can be allocated to a specific set of skills relevant to that occupation. This allows players to further customize their character\'s capabilities and specialize in their chosen profession.',
      '- **Occupational Traits:** Players can choose **2 Occupational Traits** from a list of options associated with their selected occupation. These traits represent specific characteristics or abilities that are common among members of that profession. (Traits from Origin and Occupation are interchangeable if befitting the character.)',
      '- **Recommended Features:** Occupations may also suggest certain features that complement the character\'s skills and abilities. These features can provide additional benefits or open up new opportunities for roleplaying and advancement.',
      '- **Additional Traits:** Players have the option to select additional traits and features beyond the free ones provided by their occupation, but these come at a cost of **1 Build Point (BP) each**. This allows for further customization but requires careful consideration of the character\'s overall build and BP budget.',
      '',
      '> [!TIP]',
      '> **Example (Occupation):**  ',
      '> *Xy\'larra will fit well in the Representative Occupation, focusing on her diplomatic endeavors. Again gaining 20 Skill ranks and 2 features, now chosen from the Representative Occupation - May choose from any Manipulation Skills and traits available are Analytical, Conflict Resolution, Creativity, Emotional Intelligence, Flexibility, Integrity, Languages, Negotiation, Networking, and Time Management. The Skill Feature category is recommended for Representatives (reducing the cost of such Features by 1 BP, to 1 BP minimum cost of any feature).*  ',
      '> - *Her skills gained will be Insight 10 (near expert at reading other people), Bluff 5 and Diplomacy 5.*  ',
      '> - *Traits chosen are Conflict Resolution (+2 training bonus to Diplomacy) and Emotional Empathy (+2 training bonus to Insight). Any additional occupational traits she would like will have a cost 1 BP each.*  ',
      '> - *During her training for her occupation she developed the Attractive (+2 appearance bonus to certain social checks) and Educated features (+2 trained bonus to Academics skill and +1 trained bonus to all Knowledge checks). Any additional features chosen from the Skill category will cost her 1 BP less.*',
      '',
      '---',
      '',
      '## TECHNOLOGY',
      '',
      'The **Technology Level stage** of character creation in Tangent involves determining your character\'s access to and understanding of technology. This is influenced by their species and faction and has significant impacts on their skills, wealth, and available equipment.',
      '',
      '- **Skill Bonuses:** Characters gain specific bonuses to certain skills based on their technology level, reflecting the knowledge and expertise associated with that level of technological advancement.',
      '- **Wealth Bonus:** Technology level also provides a wealth bonus, representing the increased access to resources and opportunities that come with advanced technology.',
      '- **Equipment and Improvements:** The availability of equipment, augmentations, and other technological enhancements is directly tied to a character\'s technology level. Higher technology levels unlock more advanced and powerful options.',
      '- **Skill Access:** The character\'s technology level may also limit their access to certain skills that require specific technological knowledge or training.',
      '',
      '> [!TIP]',
      '> **Example (Technology):**  ',
      '> *Being an Alterian from the Alterian Combine Xy\'larra is both tech-savvy and magic-adept, seamlessly blending futuristic tools with arcane arts. Alterians are known for grace, agility, and magical talent, living in a Space Age society that values both innovation and tradition. She gains a +25 Skills Points for skills of choice and has access to a full range of Meta training from her people due to its widespread use in Elven society.*  ',
      '> - *Good time to pick up some other skills such as Alertness 5 and Unarmed 5, and she’ll add another 5 to Academics, Bluff and Diplomacy.*',
      '',
      '---',
      '',
      '## HINDRANCES',
      '',
      'Players have the option to select **Hindrances** for their characters, such as quirks, flaws, or disabilities. These Hindrances add depth and realism to the character, making them more relatable and nuanced. However, they also come with drawbacks that can hinder the character\'s abilities or create challenges in certain situations. In exchange for taking on these Hindrances, players are rewarded with **additional Build Points (BP)** that can be used to purchase other aspects of their character, such as skills, features, or equipment.',
      '',
      '> [!TIP]',
      '> **Example (Hindrances):**  ',
      '> *Although she didn’t have tedious background but during her travels Xy\'larra has gained a Dependent - Marla a young cousin who she is responsible for but who happens to be somewhat capable so gains 3 BP to add to the characters total (less capable dependent would garner more points) - The Marla dependent may evolve into the companion feature or an entirely separate character in time, but for now she’s an Elven teenager running around with all the possible implications of such.*',
      '',
      '---',
      '',
      '## FEATURES',
      '',
      'The **Features stage** of character creation in Tangent allows you to further customize your character by selecting features that enhance their capabilities. These features can represent a wide range of abilities, from innate talents and learned techniques to technological or magical enhancements.',
      '',
      '- **BP Cost:** The default cost for a feature is **3 Build Points (BP)**, but this cost can be reduced if the feature is recommended by the character\'s species, origin, faction, or occupation. This encourages players to consider features that complement their character\'s background and role in the game world.',
      '- **Variety of Options:** Features can provide a variety of options, such as increased resilience; improved skills or proficiencies; or even unique abilities that set the character apart from others.',
      '- **Strategic Choices:** Choosing features requires careful consideration, as players must balance the benefits of each feature against its BP cost and its relevance to the character\'s overall concept and playstyle.',
      '',
      '> [!TIP]',
      '> **Example (Features):**  ',
      '> *In addition to the Attractive and Educated features gained from her occupation package Xy\'larra will want more features to focus and expand on her concept. Features cost 3 BP each unless recommended from a character’s aspect (such as occupation and at a minimum cost of 1 BP after all reductions). In Xy\'larra’s case Skill Features are recommended, reducing the costs of all Skill Features to 2 BP - guiding her to be more skill intensive coupling with many of the features granting bonuses and modifiers to skill checks.*  ',
      '> *Currently she has the following Features:*  ',
      '> - *Attractive*  ',
      '> - *Educated*  ',
      '> - *Awakened x3 to open the skills for the Mental, Entropy and Dimensional Disciplines*',
      '',
      '---',
      '',
      '## SKILLS',
      '',
      'The **Skills stage** of character creation in Tangent involves allocating Build Points (BP) to enhance your character\'s various skills. Each rank of a skill costs **1 BP**, allowing you to improve your character\'s competencies in different areas. Skills are categorized into five groups:',
      '',
      '1. **Physical:** These skills govern physical actions and attributes, such as athletics, acrobatics, and stealth.',
      '2. **Mental:** These skills pertain to intellectual pursuits and knowledge, including technology, medicine, and science.',
      '3. **Social:** These skills focus on interaction and communication with others, encompassing skills like persuasion, deception, and leadership.',
      '4. **Discipline:** These skills represent specialized training and focus often associated with specific professions or various Metaphysical practices.',
      '5. **Combat:** These skills determine a character\'s effectiveness in combat situations, including melee combat, ranged combat, and tactics.',
      '',
      '> [!TIP]',
      '> **Example (Skills):**  ',
      '> *Xy\'larra wants to be capable in a wide range of skills with a focus on being an Explorative Ambassador. She currently has the following from her character aspects so far:*  ',
      '> - *Piloting 5*  ',
      '> - *Alertness 5*  ',
      '> - *Academics 10*  ',
      '> - *Culture 5 (Know)*  ',
      '> - *Navigation 5 (Know)*  ',
      '> - *Ambassador 5 (Voc)*  ',
      '> - *Insight 10*  ',
      '> - *Bluff 10*  ',
      '> - *Diplomacy 10*  ',
      '> - *Defense 5*  ',
      '> - *Melee 5*  ',
      '> - *Unarmed 5*  ',
      '> - *Attune 5 (Metaphysic Skill)*  ',
      '> - *Sensory 10 (Mental Discipline - Metaphysic Skill)*',
      '',
      '---',
      '',
      '## AUGMENTATIONS',
      '',
      'The **Augmentations stage** of character creation in Tangent is optional and allows players to enhance their characters with permanent augmentations, such as cybernetics or bio-modifications. These augmentations can offer significant advantages, such as increased strength, enhanced senses, or unique abilities. However, they may also come with drawbacks or limitations, and they require Build Points (BP) to acquire.',
      '',
      '> [!TIP]',
      '> **Example (Augmentations):**  ',
      '> *Not feeling a lot of Augmentations she ends up with a subdermal Comm Implant and ID Chip (for convenience wise and negligible invasiveness).*',
      '',
      '---',
      '',
      '## PROPERTY',
      '',
      'The **Property stage** of character creation in Tangent involves equipping your character with the necessary tools and belongings for their adventures. This includes:',
      '',
      '- **Weapons:** Choose weapons that suit your character\'s combat style and preferences, considering factors such as their skill proficiencies, available funds, and the technology level of the setting.',
      '- **Armor:** Select armor that provides adequate protection without hindering your character\'s movement or abilities. Consider the character\'s occupation and the types of threats they are likely to face.',
      '- **Gear:** Acquire gear that supports your character\'s occupation and lifestyle. This could include tools, supplies, communication devices, or other equipment that aids them in their endeavors.',
      '- **Mecha or Mounts:** Depending on the setting and your character\'s background, they may have access to vehicles or mounts that facilitate travel and exploration.',
      '',
      'Characters begin with simple possessions appropriate for their skills, abilities, background, and tech level. This includes basic personal items and tools needed for any applicable skills. A character\'s access to and the quality of their possessions is affected by their technology level. For example, a character from a low-tech background may only have access to simple tools and weapons, while a character from a high-tech faction could have advanced weaponry and equipment.',
      '',
      'If a character wants additional or special equipment, weapons, armor, mecha, or mounts, there are two options:',
      '1. **Increase their Wealth score** to buy the items.',
      '2. **Acquire the Benefit Feature** - This will give them access to replaceable equipment, which can range from enhanced gear to a starship.',
      '',
      '> [!TIP]',
      '> **Example (Property):**  ',
      '> *As a diplomat and explorer, Xy\'larra carries equipment tailored to her professional needs and nomadic lifestyle. She utilizes a secure, long-range Diplomatic Comm-Link, wears a stylish, light-weave armored garment that provides subtle protection, and carries a versatile morphic multi-device used for data analysis and field repairs (personal Wealth used for typical needs). Additionally, she has been granted access to a sleek, scout-class star yacht for her diplomatic missions and explorations (Benefit Feature).*',
      '',
      '---',
      '',
      '## META',
      '',
      'The **Meta stage** of character creation in Tangent focuses on developing the metaphysical capabilities of characters who have access to magic, psychic powers, or other supernatural abilities.',
      '',
      '- **Awakened Feature:** This feature is a prerequisite for accessing Discipline skills, which govern the use of metaphysical abilities.',
      '- **Discipline Skills:** These skills represent specific areas of expertise within the metaphysical realm, such as Alteration, Conjuration, or Divination.',
      '- **Invocations:** These are specific skills or abilities within a chosen Discipline, representing spells, psychic techniques, or other supernatural manifestations. Invocations are treated as separate skills and can be improved independently.',
      '- **Specialization or Special Ability:** Invocations can be learned either as a Specialization within a Discipline skill or separate as a Special Ability Feature, with each rank costing 1 Character Point (CP).',
      '',
      '> [!TIP]',
      '> **Example (Meta):**  ',
      '> *Meta Features and Discipline Skills already known as listed above:*  ',
      '> - *Discipline Feature of Awakened taken 3 times (for the Mental, Entropy and Dimensional Disciplines)*  ',
      '> - *Has access to the Discipline skills of Summoning, Teleport (Dimensional); Projection, Sense (Mental); Chaos, Order (Entropy) and Attune (the activation skill for Meta Disciplines).*  ',
      '> - *Current skills of Attune 5 and Sensory 10 (Mental Discipline)*',
      '',
      '---',
      '',
      '## DERIVED COMBAT & SURVIVAL STATISTICS',
      '',
      '| Statistic | Calculation Formula | Description |',
      '| :--- | :--- | :--- |',
      '| **Max Hit Points (HP)** | Base (10) + (Stamina Mod * 2) + Rank Multipliers | Total physical trauma capacity |',
      '| **Initiative Check** | d20 + Reflex Save + Agility Mod | Reaction speed at start of combat |',
      '| **Might Check** | d20 + Strength Mod + Athletics Rank | Physical power, breaking DC, grappling |',
      '| **Fortitude Save** | d20 + Stamina Mod + Survival Rank | Resistance to poison, shock, radiation |',
      '| **Reflex Save** | d20 + Agility Mod + Acrobatics Rank | Evasion of blast radii and traps |',
      '| **Logic Check** | d20 + Intellect Mod + Science/Tech Rank | Deductive analysis and computation |',
      '| **Will Save** | d20 + Wisdom Mod + Alertness Rank | Mental grit, fear, and psionic defense |',
      '| **Etiquette Check** | d20 + Charisma Mod + Culture Rank | Social poise and diplomatic standing |'
    ].join('\n'),
    mechanic: 'BaseBP = 150\nAttributeCost = 5 BP per +1 (Max +4 raw at creation)\nSkillRankCost = 1 BP per rank\nFeatureBaseCost = 3 BP (2 BP if Recommended, 1 BP Minimum)\nTotalFoundationalGrants = 60 Skill Ranks + 4 Features + 4 Traits (From Faction, Origin, Occupation)',
    guide: '1. Define concept, background, and persona goals.\n2. Deduct Species BP cost from the 150 BP pool; apply species ability modifiers and inherent traits.\n3. Allocate remaining BP to Attributes (5 BP each, max +4), Skills (1 BP each), and Features (3 BP / 2 BP).\n4. Allocate 20 Faction SP, 20 Origin SP, and 20 Occupation SP from background pools.\n5. Select 2 Origin Traits and 2 Occupation Traits.\n6. Calculate derived Hit Points, Toughness, Initiative, and Saving Throws.',
    note: 'Remember, character creation in Tangent is designed to be highly flexible, and these steps can be adapted to fit your preferences and the GM\'s guidelines.'
  },
  {
    id: '1-01-01-core-attributes-checks',
    name: '1.01.01 Core Attributes, Checks & Derived Perception',
    category: 'compendium',
    entry_type: 'Operator Rule',
    parent: '1.00 CHARACTER CREATION & ECONOMY',
    order: 2,
    description: [
      '# 1.01.01 Core Attributes, Checks & Derived Perception',
      '',
      'Attributes are a crucial aspect of character creation and gameplay. They represent a character\'s natural aptitudes and talents, influencing their success in various tasks and challenges. The six core attributes are **Strength, Agility, Stamina, Intellect, Wisdom, and Charisma**.',
      '',
      '---',
      '',
      '## 1. Cost & Starting Maximums',
      '',
      '- **Cost:** **5 BP per +1 increase** in an attribute score.',
      '- **Baseline:** The average score for an ordinary human is **+0**.',
      '- **Creation Maximum:** During Character Creation, no raw attribute score may exceed **+4** before species adjustments or mechanical augmentations are applied.',
      '- **Paragon Tier (+5):** A score of +5 indicates exceptional mastery and peak genetic or species capability.',
      '- **Non-Attribute Flaw (-25 BP):** A character lacking an attribute completely (e.g. an AI construct lacking physical attributes) automatically fails all checks with it.',
      '',
      '---',
      '',
      '## 2. Attribute Checks & Saving Throws',
      '',
      'Attribute checks act as a fallback for actions not covered by specific skills and serve as saving throws against hazards.',
      '',
      '### How Attribute Checks are Calculated',
      '`Base Check Score = 2 + (Attribute Score * 2)`  ',
      '`Roll = d20 + Base Check Score + Modifiers`',
      '',
      '| Attribute | Derived Check | Core Mechanical Influence |',
      '| :--- | :--- | :--- |',
      '| **Strength (STR)** | **Might Check** | Carrying/lifting capacity, melee weapon damage, breaking doors and bending bars |',
      '| **Agility (AGI)** | **Reflex Check** | Dodging attacks, acrobatics, ranged weapon accuracy, initiative |',
      '| **Stamina (STA)** | **Fortitude Check** | Toxic/disease resistance, base toughness, enduring extreme weather |',
      '| **Intellect (INT)** | **Reason Check** | Deductive logic, technical crafting, decoding ciphers, forensic knowledge |',
      '| **Wisdom (WIS)** | **Willpower Check** | Sensing deception, resisting fear, mental defenses against psionics |',
      '| **Charisma (CHA)** | **Etiquette Check** | Leadership, complex negotiation, social navigation, bartering |',
      '',
      '---',
      '',
      '## 3. Derived Perception',
      '',
      '**Perception** is a sub-ability derived by combining Intellect and Wisdom scores:',
      '`Perception Base = Intellect + Wisdom`',
      '',
      '### Focused Perception Types',
      '- **Default Awareness (Alertness):** Perception Base + Alertness skill (spotting hazards, ambushes, visual cues).',
      '- **Meta Sensory (Attune):** Perception Base + Attune skill (detecting subtle magical or psionic aura signatures).',
      '- **Social Insight (Insight):** Perception Base + Insight skill (reading facial cues, body language, emotional deception).',
      '- **Technical Analysis (Technology):** Perception Base + Technology skill (evaluating hardware vulnerabilities, sensor scans).'
    ].join('\n'),
    mechanic: 'BaseAttributeScore = 0 (Standard Human)\nAttributeCheck_Base = 2 + (AttributeScore * 2)\nPerceptionBase = Intellect + Wisdom\nAttributeCheck_Roll = d20 + AttributeCheck_Base + Modifiers',
    guide: 'Use Attribute Checks primarily for saving throws and fallback situations not covered by specific learned skills.',
    note: 'Attribute checks are not a replacement for trained skills; unassisted raw checks lack focus strike and specialization bonuses.'
  },
  {
    id: '1-01-02-vitality-health-structure',
    name: '1.01.02 Vitality, Health, Structure & Toughness',
    category: 'compendium',
    entry_type: 'Operator Rule',
    parent: '1.00 CHARACTER CREATION & ECONOMY',
    order: 3,
    description: [
      '# 1.01.02 Vitality, Health, Structure & Toughness',
      '',
      'In Tangent, a character\'s ability to endure and recover from damage is represented by **Vitality**, **Health**, and **Structure** (for Synthetics and non-biological entities).',
      '',
      '---',
      '',
      '## 1. Vitality vs. Health Breakdown',
      '',
      '- **Vitality (Starting Base: 30):** Represents energy, stamina, physical resilience, and luck. Non-lethal damage, fatigue, and minor scrapes deplete Vitality first.',
      '- **Health (Starting Base: 30):** Represents biological life force and anatomical integrity. Severe weapon trauma, critical hits, and deep wounds damage Health after Vitality is exhausted.',
      '- **Structure (Combined Pool):** For Synthetics, Golems, Mecha, and Undead lacking biological buffers, Vitality and Health are combined into a single unified **Structure** pool.',
      '',
      '---',
      '',
      '## 2. Increasing Pools with Build Points',
      '',
      '- **Cost:** **1 BP = +5 Vitality** or **+5 Health** during character creation.',
      '- **Suggested Soft Cap:** 60 points in each pool at character creation.',
      '',
      '---',
      '',
      '## 3. Toughness & Damage Reduction',
      '',
      '- **Toughness:** A character\'s Stamina score provides base **Toughness**, reducing incoming kinetic and physical trauma on a point-for-point basis before Armor DR.',
      '',
      '---',
      '',
      '## 4. Concussive Damage, Explosions & Falls',
      '',
      'Concussive and blast damage is dispersed over the entire body:',
      '- If a character attempts a defensive reaction (Reflex save), blast damage is **divided equally between Vitality and Health**.'
    ].join('\n'),
    mechanic: 'StartingVitality = 30 + (PurchasedBP * 5)\nStartingHealth = 30 + (PurchasedBP * 5)\nStructure = Vitality + Health (for Synthetics/Objects)\nDamageSoak = IncomingDamage - Toughness - ArmorDR',
    guide: 'Deplete Vitality first when taking damage from standard attacks; apply damage to Health once Vitality reaches 0.',
    note: 'Critical hits bypass the Vitality buffer and inflict direct Health damage.'
  },
  {
    id: '1-01-03-karma-fate-economy',
    name: '1.01.03 Karma, Fate Points & Narrative Powers',
    category: 'compendium',
    entry_type: 'Operator Rule',
    parent: '1.00 CHARACTER CREATION & ECONOMY',
    order: 4,
    description: [
      '# 1.01.03 Karma, Fate Points & Narrative Powers',
      '',
      '**Karma** is an essential aspect of the Tangent RPG system that provides players with a limited resource they can strategically use to influence various aspects of the game. It serves as a pool of points that can be spent to affect dice rolls, modify character actions, and even shape narrative outcomes.',
      '',
      '---',
      '',
      '## 1. Karma Pool Basics',
      '',
      'Characters have **3 Karma Points** by default.',
      '',
      '- **Session Reset:** Karma resets to max (Default 3) at the start of every session. It does not regenerate via rest.',
      '- **Heroic Gain:** The GM / Architect may award 1 Karma Point immediately for "Heroic" or "Awesome" actions.',
      '- **Restoration:** All Karma Points are fully restored at the start of each game session, or regained through significant story moments (chapters) or by performing \'heroic\' or awesome actions. Karma Points are **not recovered by rest**.',
      '- **Increasing the Pool:** The *Karmic Blessing* feature allows characters to increase their maximum Karma Pool by **+1 point per rank** of the feature. Otherwise, the pool will be increased by possible storyline milestones and GM prerogative.',
      '',
      '---',
      '',
      '## 2. Using Karma Points',
      '',
      'Karma Points can be spent to activate various effects, but they will not guarantee a success. These effects are in addition to any other modifiers and will stack accordingly. Critical failures and successes may be adjusted as any other rolls following the listed mechanics.',
      '',
      '| Expenditure Option | Timing | Cost | Scope & Effect |',
      '| :--- | :--- | :---: | :--- |',
      '| **"I Got This"** | Declare *before* making the roll | 1 KP | **Advantage on Any Single Roll:** Roll twice, keep higher result. Usable on ability checks, skill checks, attacks, saves, and damage rolls. |',
      '| **"Not What I Meant"** | Declare *immediately after* initial roll | 1 KP | **Reroll Ability / Non-Combat Skill Check:** Discard roll and reroll. Must accept 2nd result even if worse. Cannot be used on combat/attack rolls. |',
      '| **"Shake it Off"** | Declare anytime suffering temporary condition | 1 KP | **Reduce Condition Severity by 1 Stage:** Lowers conditions like Poisoned, Stunned, or Blinded by one level (e.g. Major to Minor). |',
      '| **"Second Wind"** | Spend 1 full minute of internal focus | 1 KP | **Replaces Light Rest:** Bypasses downtime to instantly refresh daily limited-use abilities, special attacks, traits, or features. |',
      '| **"So Mote it Be"** | Declare *simultaneously* with metaphysical skill/feat | 1 KP | **Metaphysical Potency:** Boosts metaphysical check potency (range, duration, magnitude) or activates a specialized discipline Karma Feat. |',
      '| **"By Will Alone"** | Declare action with GM approval | 1 KP | **Push Limits / Narrative Agency:** Attempt impossible or unlisted actions, emulate a basic feature for a scene, or nudge a rule in character\'s favor. |',
      '',
      '### The 6 Core Karma Actions Explained',
      '',
      '#### "I Got This"',
      'This Karma Point expenditure option allows players to gain an advantage on any single roll.',
      '- **Declaration:** The player must declare they are using "I Got This" before making the roll.',
      '- **Any Single Roll:** It can be used on any dice roll, including ability checks, skill checks, attack rolls, saving throws, and even damage rolls. This versatility makes it a valuable tool in various situations.',
      '- **Advantage:** Gaining advantage means rolling the die twice and taking the higher result. This significantly increases the character\'s chance of success.',
      '',
      '#### "Not What I Meant"',
      'This option of the Karma mechanic allows a player to reroll an Ability Check or a non-combat Skill Check.',
      '- **Timing:** The player must declare they are using "Not What I Meant" immediately after the initial roll.',
      '- **Scope:** It applies to Ability Checks (Strength, Agility, etc.) and non-combat Skill Checks (Technology, Medicine, etc.). This excludes attack rolls, damage rolls, and other combat-specific rolls.',
      '- **Acceptance:** The second roll\'s result must be accepted, even if it\'s worse than the first.',
      '',
      '#### "Shake it Off"',
      'This Karma Point expenditure option allows characters to reduce the severity of temporary conditions affecting them.',
      '- **Temporary Conditions:** These are short-term effects that hinder a character\'s abilities or actions. Examples include being Poisoned, Stunned, or Blinded.',
      '- **Severity Stages:** Many conditions have severity levels, such as Poisoned (Minor, Major, Critical).',
      '- **One Stage Reduction:** Spending a Karma Point allows the character to reduce the condition\'s severity by one stage. For example, a character suffering from Major Poisoning could reduce it to Minor Poisoning.',
      '- **Timing:** This can be used anytime the character is suffering from a temporary condition.',
      '',
      '#### "Second Wind"',
      'This Karma Point expenditure option allows a character to quickly refresh their abilities and resources, bypassing the need for a Light Rest.',
      '- **Replaces Light Rest:** A Light Rest is a short period of downtime during which characters can recover some spent abilities or regain limited uses of certain features. "Second Wind" allows a character to achieve the same benefits without needing to take a Light Rest.',
      '- **1 Full Minute:** Using "Second Wind" requires the character to spend 1 full minute focusing on themselves and their inner reserves. This represents the character drawing upon their willpower and determination to push through fatigue and replenish their energy.',
      '- **Specific Benefits:** The exact benefits of using "Second Wind" depend on the character\'s traits, abilities, and features. Generally, it can be used to refresh abilities that have a limited number of uses per day, such as special attacks, traits or features.',
      '',
      '#### "So Mote it Be"',
      'This Karma Point expenditure option interacts with a character\'s metaphysical abilities, enhancing their power or enabling special feats.',
      '- **Metaphysics Users:** This option is available to characters who have access to metaphysical abilities, such as magic, psychic powers, or other supernatural forces.',
      '- **Karma Feat Activation:** A Karma Point can be spent to activate a Karma Feat, which is a special ability or enhancement tied to the character\'s metaphysical disciplines. These feats might grant temporary bonuses, unique effects, or powerful attacks.',
      '- **Skill Boost:** Alternatively, a Karma Point can be used to boost the effectiveness of a metaphysical skill check. This could increase the power of a spell, the range of a psychic ability, or the duration of a supernatural effect.',
      '- **Simultaneous Use:** The Karma Point expenditure must be declared along with the use of the metaphysical skill or feat. This means the player decides to use "So Mote it Be" at the same time they declare they are using the skill or feat, not after the roll is made.',
      '',
      '#### "By Will Alone"',
      'This is a unique Karma Point expenditure, allowing characters to attempt actions that push the boundaries of their normal capabilities.',
      '- **GM Discretion:** The core of "By Will Alone" is the GM\'s judgment. Players propose an action, and the GM decides if it\'s possible within the game world and the character\'s potential.',
      '- **Possible but Challenging:** The action must be something that\'s not explicitly covered by the character\'s skills or abilities, but is theoretically achievable with extreme effort, luck, or a narrative justification. The effect could involve a nudge of a rule for one action or event in the character’s favor, the emulation of a basic feature for the event or scene and similar low-end temporary game tweaks for character agency (within GM’s approval for the ongoing story).',
      '- **Karma Point Cost:** Attempting the action requires spending a Karma Point, regardless of success or failure. This represents the character tapping into their inner reserves or pushing their luck.',
      '- **No Guarantee:** Even with a Karma Point spent, success is not guaranteed. The GM may call for an ability check, a skill check, or a unique challenge to resolve the action\'s outcome.',
      '',
      '---',
      '',
      '## 3. Plot Points',
      '',
      'Plot Points are a special resource in Tangent RPG, awarded by the GM to players who actively engage with the story and its challenges.',
      '',
      '- **Separate from Karma Pool:** Plot Points function similarly to Karma Points, allowing players to influence rolls and actions. However, they are a separate resource and do not count towards the character\'s Karma Pool maximum.',
      '- **Temporary and Specific:** Plot Points are temporary and must be used within the specific scenario or story arc they were awarded in. This encourages players to use them strategically and think about how they can best contribute to the unfolding narrative.',
      '- **Compensation and Balance:** Plot Points are often granted to characters who find themselves in situations beyond their control, as a form of compensation or to help balance the challenges they face. This can help ensure that all players have a meaningful impact on the story, even if their characters are not the most powerful or skilled.',
      '',
      '---',
      '',
      '## 4. Negative Karma (Karmic Debt)',
      '',
      'Negative Karma allows characters to push their luck and potentially face consequences for their actions.',
      '',
      '- **GM\'s Discretion:** The allowance of Negative Karma is entirely at the GM\'s discretion who will decide when and how to apply its effects, tailoring it to the specific situation and the character\'s actions. Incurring Negative Karma points are up to the players themselves.',
      '- **Spending Karma into the Negatives:** Characters can choose to spend Karma Points even when they have none left, effectively going into "Karmic debt." This debt is limited to the character\'s **Charisma score + 1** (e.g. Charisma 3 permits spending down to -4 Karma).',
      '- **Karmic Effects:** Negative Karma Points allow the GM to introduce various effects that hinder the character or benefit their opponents. These effects are typically narrative in nature, reflecting the character\'s misfortune or the universe balancing the scales:',
      '  - **Disadvantage on Rolls:** A common Karmic effect is imposing disadvantage on the character\'s rolls. This means they roll twice and take the lower result, significantly reducing their chances of success.',
      '  - **Forced Rerolls:** The GM might also force the character to reroll successful rolls, introducing uncertainty and potentially turning a victory into a failure.',
      '  - **NPC Benefits:** Negative Karma can also positively affect NPCs who are directly opposing the character. This could manifest as increased luck, improved skills, or unexpected advantages that help them overcome the character\'s efforts.'
    ].join('\n'),
    mechanic: 'BaseKarma = 3\nMaxKarmaDebt = Charisma + 1\nAdvantage = Roll 2d20, Take Highest Result\nDisadvantage = Roll 2d20, Take Lowest Result\nConditionReduction = -1 Severity Stage (Major -> Minor -> Cleared)\nSecondWind = 1 Min Focus, Replaces Light Rest',
    guide: 'Spend Karma points during critical encounters to gain Advantage, reroll non-combat failures, reduce debuffs, or bend reality. Track Plot Points separately for arc-specific narrative boosts.',
    note: 'Negative Karma must never exceed Charisma + 1 and grants the GM narrative complication triggers until resolved.'
  },
  {
    id: '1-01-04-rest-recovery-cycles',
    name: '1.01.04 Rest, Recovery & Biological Cycles',
    category: 'compendium',
    entry_type: 'Operator Rule',
    parent: '1.00 CHARACTER CREATION & ECONOMY',
    order: 5,
    description: [
      '# 1.01.04 Rest, Recovery & Biological Cycles',
      '',
      'Rest mechanics govern how characters recover spent abilities, heal Vitality, and reset traits between hazardous encounters.',
      '',
      '---',
      '',
      '## 1. Full Rest (6 to 8 Hours)',
      '',
      '- **Standard Species:** 6 to 8 hours of uninterrupted sleep restores all lost Vitality and resets daily features.',
      '- **Synthetic & Insectoid Races:** Do not sleep in the traditional biological sense; require only a brief diagnostic cycle or Light Rest.',
      '- **Alterians & Mondi:** Engage in deep contemplative meditations (counted as Light Rest) rather than biological unconsciousness.',
      '',
      '---',
      '',
      '## 2. Light Rest (Naps & Meditation)',
      '',
      'A Light Rest is a short rest period (up to **4 times per day**) that resets minor features and recharges stamina:',
      '',
      '- **Nap or Meditation (1 Hour):** The most restful period; complete downtime with zero activity.',
      '- **Lounging (2 Hours):** Casual conversation, reading, and light observation.',
      '- **Light Duty (3 Hours):** Minimal labor, weapon maintenance, or monitoring starship sensors.',
      '- *Interruption:* Any strenuous activity during a rest period degrades the rest tier by one stage.'
    ].join('\n'),
    mechanic: 'FullRest_Duration = 6-8 Hours (Restores 100% Vitality, Resets Daily Traits)\nLightRest_MaxPerDay = 4\nNapDuration = 1 Hour',
    guide: 'Declare Light Rests during transit or post-combat triage to reset short-rest abilities.',
    note: 'Architects should enforce environmental threats if characters attempt to rest in unsecured hostile zones.'
  },
  {
    id: '1-01-05-death-dying-revivification',
    name: '1.01.05 Death, Dying & Revivification',
    category: 'compendium',
    entry_type: 'Operator Rule',
    parent: '1.00 CHARACTER CREATION & ECONOMY',
    order: 6,
    description: [
      '# 1.01.05 Death, Dying & Revivification',
      '',
      'In Tangent, characters are protected by a two-tiered health buffer, but lethal trauma requires swift medical intervention.',
      '',
      '---',
      '',
      '## 1. The Threshold of Death',
      '',
      'When a character\'s Health drops to **0 HP**:',
      '1. **Incapacitation:** The character immediately falls unconscious, drops held items, and gains the **Prone** condition.',
      '2. **Death\'s Door:** If both Health and Vitality are at 0, the character is dying and enters a comatose state.',
      '3. **The Death Clock:** The character has a number of rounds equal to their **Stamina Score** (Minimum 1 round) to receive medical aid.',
      '4. **Stabilization:** A successful **Medicine check (DC 15)** or trauma nanite injection halts the death clock.',
      '5. **Massive Damage:** Taking damage equal to or exceeding their Stamina score in a single hit while at Death\'s Door causes instant death.',
      '',
      '---',
      '',
      '## 2. Revivification ("The High Cost of Dying")',
      '',
      'Returning a character from the dead requires advanced TL5 medical clone synthesis or high-tier ML5 Metaphysics:',
      '- **Penalties:** The revived character loses all remaining Karma Points and incurs a **-5 Experience Debt** until repaid through heroic gameplay.'
    ].join('\n'),
    mechanic: 'DeathClock_Rounds = max(1, StaminaScore)\nStabilization_DC = Medicine DC 15\nRevive_Penalty = Lose All Karma + 5 XP Debt',
    guide: 'Allies should prioritize stabilizing downed teammates within their Stamina round window.',
    note: 'Revivification should be a rare, momentous narrative arc rather than a routine transaction.'
  },
  {
    id: '1-01-06-experience-award-points',
    name: '1.01.06 Experience, Award Points (AP) & Advancement',
    category: 'compendium',
    entry_type: 'Operator Rule',
    parent: '1.00 CHARACTER CREATION & ECONOMY',
    order: 7,
    description: [
      '# 1.01.06 Experience, Award Points (AP) & Advancement',
      '',
      'Character advancement in Tangent is measured through **Award Points (AP)** granted for completing story chapters, overcoming formidable adversaries, and immersive roleplay.',
      '',
      '---',
      '',
      '## 1. Spending Award Points',
      '',
      '- **Conversion:** **1 AP = 1 BP** for purchasing new skills, attributes, features, or augmentations.',
      '- **Advancement Pacing:** Abilities and skills may only be increased by **+1 rank per experience award**, representing progressive natural training.',
      '',
      '---',
      '',
      '## 2. Story & Session Awards',
      '',
      '| Award Type | AP Granted | Criteria & Trigger |',
      '| :--- | :---: | :--- |',
      '| **Chapter Completion** | **5 – 10 AP** | Awarded upon completing a major narrative storyline or planetary arc. |',
      '| **Defeating Major Villain / Goal**| **1 – 3 AP** | Awarded for overcoming critical campaign obstacles or arch-villains. |',
      '| **Session Participation** | **0 – 2 AP** | Awarded for tactical focus, mission engagement, and teamwork. |',
      '| **In-Character Roleplaying** | **0 – 2 AP** | Awarded for dramatic dialogue, embodying flaws, and creative solutions. |'
    ].join('\n'),
    mechanic: '1 AP = 1 BP for Character Folio Advancements\nMaxSingleStatIncrease_PerAward = +1 Rank',
    guide: 'Spend AP between gaming sessions to advance your Persona Folio capabilities.',
    note: 'Architects should distribute AP at the end of each session or chapter downtime.'
  },
  {
    id: '1-02-skill-point-economy',
    name: '1.02 Skill Point Economy & Allocation Pools',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 2,
    description: [
      '# 1.02 Skill Point Economy & Allocation Pools',
      '',
      'Skills in Tangent represent formal training, reflex conditioning, and practical experience. All skill ranks are purchased with **Skill Points (SP)** or **Build Points (BP)**.',
      '',
      '---',
      '',
      '## The Three 20-Point Pools',
      '',
      'Every starting character receives three separate, non-transferable pools of 20 Skill Points:',
      '',
      '| Pool Name | Source | Purpose | Allowable Skills |',
      '| :--- | :--- | :--- | :--- |',
      '| **Faction Pool** | Faction / Polity | Cultural, political, and doctrinal training | Listed under chosen Faction |',
      '| **Origin Pool** | Birthworld / Habitat | Survival, environmental adaptation, navigation | Listed under chosen Origin |',
      '| **Occupation Pool** | Career / Profession | Technical, combat, and vocational expertise | Listed under chosen Occupation |',
      '',
      '---',
      '',
      '## Skill Rank Limits & Creation Caps',
      '',
      '- **Cost:** **1 SP = 1 Skill Rank** (or 1 BP = 1 Skill Rank if using general Build Points).',
      '- **Recommended Creation Baseline:** No skill should exceed **Rank 6 (Trained / Professional)** at character creation.',
      '- **Maximum Creation Hard Cap:** Under no circumstance may any starting skill exceed **Rank 11 (Expert)** at character creation.',
      '- Ranks 12–30 are unlocked exclusively through in-game gameplay, progression milestones, and experience rewards.'
    ].join('\n'),
    mechanic: 'SkillRank_CreationMax = 11\nSkillRank_CreationRecommended = 6\nTotalStartingSkillPoints = 20(Faction) + 20(Origin) + 20(Occupation) = 60 SP',
    guide: 'Spend exactly 20 points within each respective category list. Do not pool points across different categories.',
    note: 'Limiting starting ranks to Rank 6 ensures characters have room for meaningful growth across multiple campaign arcs.'
  },
  {
    id: '1-03-feature-feat-acquisition',
    name: '1.03 Feature & Feat Acquisition Rules',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 3,
    description: [
      '# 1.03 Feature & Feat Acquisition Rules',
      '',
      'Features (also termed Feats or Perks) represent distinct capabilities, combat maneuvers, specialized augmentations, and metaphysical awakenings.',
      '',
      '---',
      '',
      '## Cost Structure & Discounts',
      '',
      '- **Standard Base Cost:** **3 Build Points (BP)** per Feature.',
      '- **Recommended Feature Discount:** If a Feature is listed in your **Occupation** or **Faction** recommended list, its cost is reduced by **1 BP** (Final Cost: **2 BP**).',
      '- **Minimum Cost:** A Feature can never cost less than **1 BP**, regardless of stacking discounts.',
      '',
      '---',
      '',
      '## Feature Classifications',
      '',
      '1. **Ability Features:** Enhance core physical or mental prowess (e.g. *Great Fortitude, Lightning Reflexes, Potent Might, Iron Will*).',
      '2. **Combat Features:** Unlock tactical weapon masteries, critical thresholds, and advanced maneuvers (e.g. *Point Blank Mastery, Dual Wielding, Cleave*).',
      '3. **Meta Features:** Awaken metaphysical disciplines or unlock advanced Invocations (e.g. *Awakened Discipline, Meta Resonance, Overchannel*).',
      '4. **General Features:** Broad utility perks covering wealth, connections, cybernetics, and familiars.',
      '5. **Ranked Features:** Features that can be purchased multiple times. Each purchase stacks benefits, capped by the character\'s linked Attribute or Skill Tier.'
    ].join('\n'),
    mechanic: 'Feature_BaseCost = 3 BP\nFeature_DiscountedCost = 2 BP (if Recommended)\nFeature_MinCost = 1 BP',
    guide: 'Check your Occupation and Faction sheets first to identify discounted Recommended Features before spending Build Points.',
    note: 'Ranked features should not exceed the character\'s attribute modifier or skill stage.'
  },
  {
    id: '1-04-factions-galactic-polities-codex',
    name: '1.04 Factions & Galactic Polities Codex',
    category: 'compendium',
    entry_type: 'Worldbuilding',
    parent: '1.00 CHARACTER CREATION',
    order: 4,
    description: [
      '# 1.04 Factions & Galactic Polities Codex',
      '',
      'Factions in Tangent represent the interstellar sovereign powers, megacorporate syndicates, monastic orders, and mercenary guilds that vie for control of the galaxy.',
      '',
      '---',
      '',
      '## Major Canonical Galactic Polities',
      '',
      '### 1. The Dracon Dynasty',
      '- **Archetype:** Feudal Space Monarchy / Dragon-Lord Technocracy.',
      '- **Core Philosophy:** *Protection, Patience, and Long-Term Stability.*',
      '- **Society Structure:** High Nobility (Draconic descendants) ruling over Knightly Dragoons and protected Commoners.',
      '- **Key Skills:** Politics, Piloting, Archaic Weapons, History, Etiquette.',
      '',
      '### 2. The Arcology Syndicates',
      '- **Archetype:** Hyper-Capitalist Megacorporate Coalition.',
      '- **Core Philosophy:** *Efficiency, Profitability, and Market Dominance.*',
      '- **Society Structure:** Board of Directors, Executive Officers, and Contracted Citizens.',
      '- **Key Skills:** Business, Computers, Technology, Modern Weapons, Deceit.',
      '',
      '### 3. The Cyber-Guilds of Technomancers',
      '- **Archetype:** Transhumanist Cyber-Collective.',
      '- **Core Philosophy:** *Transcendence through Synthesis of Flesh and Machine.*',
      '- **Society Structure:** Fabricators, Circuit-Monks, and Neural Enclaves.',
      '- **Key Skills:** Technology, Computers, Science, Cybernetics, Physics.',
      '',
      '### 4. The Holy Federation of Light',
      '- **Archetype:** Theocratic Galactic Concordat.',
      '- **Core Philosophy:** *Spiritual Purity, Cosmic Harmony, and Divine Law.*',
      '- **Society Structure:** Patriarchs, Inquisitors, Templars, and Faithful Laymen.',
      '- **Key Skills:** Religion, Metaphysics, Diplomacy, Fortitude, Will.',
      '',
      '---',
      '',
      '## The 25 Generic Organizational Templates',
      '',
      'Architects and Operators can utilize the **25 Generic Faction Templates** (e.g. Free Trader Consortium, Frontier Militia, Smuggler Ring, Research Institute) to rapidly construct custom organizations with ready-to-use 20 SP packages.'
    ].join('\n'),
    mechanic: 'Faction_SkillPool = 20 SP\nFaction_BonusFeatures = 2 (selected at 1 BP discount)',
    guide: 'Choose a faction that aligns with your character\'s cultural worldview, ethical code, and allegiances.',
    note: 'Faction standing affects social reaction DCs when dealing with rival or allied organizations.'
  },
  {
    id: '1-05-origins-habitats-codex',
    name: '1.05 Origins & Habitats Codex',
    category: 'compendium',
    entry_type: 'Worldbuilding',
    parent: '1.00 CHARACTER CREATION',
    order: 5,
    description: [
      '# 1.05 Origins & Habitats Codex',
      '',
      'A character\'s Origin defines their birthworld, native planetary biome, or orbital habitat. Origin environments instill instinctive survival mechanisms and physical conditioning.',
      '',
      '---',
      '',
      '## Canonical Origin Environments',
      '',
      '| Origin Name | Environment Profile | Key Society Skills | Example Origin Traits |',
      '| :--- | :--- | :--- | :--- |',
      '| **Agricultural (Agri-World)** | Low development, fertile plains, farm arcologies | Piloting, Alertness, Nature, Survival | *Green Thumb, Animal Husbandry, Farm Mech* |',
      '| **Arcology (Mega-City)** | Dense urban towers, neon corridors, artificial atmosphere | Computers, Stealth, Technology, Streetwise | *Urban Stalker, Grid Runner, Dense Crowd Evasion* |',
      '| **Asteroid Belt (Void Habitat)** | Zero-g mines, pressurized domes, cold vacuum | Piloting, Physics, Technology, Alertness | *Zero-G Acclimation, Vacuum Intuition, Seal Repair* |',
      '| **Death World (Hostile Ecology)** | Extreme predators, toxic flora, volatile tectonic cycles | Survival, Athletics, Alertness, Medicine | *Apex Predator Reflexes, Toxin Tolerance, Iron Gut* |',
      '| **High-Gravity World** | Crushing gravity, dense planetary core | Athletics, Might, Fortitude, Intimidation | *Dense Muscle Mass, Impact Resistance, Heavy Stride* |',
      '| **Low-Gravity / Void Station**| Microgravity, centrifugal rings, orbital platforms | Acrobatics, Piloting, Physics, Computers | *Light-Footed, Kinetic Drift, Micro-Thruster Mastery* |',
      '',
      '---',
      '',
      '## Origin Allotment Rules',
      '',
      '- **Origin Skill Pool:** **20 Skill Points** distributed among the origin\'s listed skills.',
      '- **Origin Traits:** Choose **Two Traits** from your native origin list at character creation.',
      '- **Secondary Origin:** An Operator may select a secondary origin to broaden trait options without receiving additional points.'
    ].join('\n'),
    mechanic: 'Origin_SkillPool = 20 SP\nOrigin_Traits = 2 (Inherent at creation)',
    guide: 'Select an origin that matches your character\'s physical conditioning and childhood background.',
    note: 'Environmental penalties (e.g. high-gravity, zero-g) do not apply to native origin characters.'
  },
  {
    id: '1-06-occupations-careers-codex',
    name: '1.06 Occupations & Careers Codex',
    category: 'compendium',
    entry_type: 'Worldbuilding',
    parent: '1.00 CHARACTER CREATION',
    order: 6,
    description: [
      '# 1.06 Occupations & Careers Codex',
      '',
      'An Occupation represents a character\'s career, formal trade, and role in society. It supplies professional skills, discounted recommended features, and career traits.',
      '',
      '---',
      '',
      '## Canonical Career Archetypes',
      '',
      '### 1. Adept (Metaphysic Specialist)',
      '- **Role:** Reality manipulation, psionic warfare, spiritual counseling.',
      '- **Professional Skills:** Attune, Known Metafocus Disciplines.',
      '- **Recommended Features:** Awakened Discipline, Meta Focus, Energy Channeling.',
      '',
      '### 2. Soldier (Tactical Combatant)',
      '- **Role:** Direct fire, heavy weapon deployment, squad coordination.',
      '- **Professional Skills:** Modern Weapons, Archaic Weapons, Tactics, Athletics, Armor.',
      '- **Recommended Features:** Toughness, Point Blank Mastery, Heavy Armor Training.',
      '',
      '### 3. Scout (Recon & Exploration)',
      '- **Role:** Pathfinding, infiltration, sniper overwatch, planetary survey.',
      '- **Professional Skills:** Stealth, Alertness, Navigation, Survival, Piloting.',
      '- **Recommended Features:** Lightning Reflexes, Camouflage Mastery, Eagle Eye.',
      '',
      '### 4. Scholar / Scientist (Research & Analysis)',
      '- **Role:** Forensics, astrophysics, xenobiology, historical deciphering.',
      '- **Professional Skills:** Academics, Science, Physics, Computers, Medicine.',
      '- **Recommended Features:** Mastermind, Fast Hacking, Analytical Deduction.',
      '',
      '### 5. Scoundrel (Subterfuge & Infiltration)',
      '- **Role:** Security bypassing, street economics, black-market procurement.',
      '- **Professional Skills:** Stealth, Deceit, Streetwise, Lockpicking, Sleight of Hand.',
      '- **Recommended Features:** Slippery, Hidden Pocket, Quick Draw.',
      '',
      '---',
      '',
      '## Occupational Rules',
      '',
      '- **Professional Skill Pool:** **20 Skill Points** allocated to occupational skills.',
      '- **Occupational Traits:** Select **Two Traits** from your career archetype.',
      '- **Cross-Training (Background Trait):** Take the *Background* trait to acquire training from a secondary occupation.'
    ].join('\n'),
    mechanic: 'Occupation_SkillPool = 20 SP\nOccupation_Traits = 2\nRecommendedFeatures_Discount = 1 BP',
    guide: 'Distribute your 20 professional SP across career skills to establish your primary in-game competencies.',
    note: 'Characters can multiclass or take on new occupations during long campaign downtime periods.'
  },
  {
    id: '1-07-master-skills-codex',
    name: '1.07 Master Skills Codex & Benchmarks',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 7,
    description: [
      '# 1.07 Master Skills Codex & Benchmarks',
      '',
      'Skills are organized into **5 Major Skill Groups**. Every rank adds a +1 bonus to task resolution checks.',
      '',
      '---',
      '',
      '## Master Skill Directory',
      '',
      '### I. Physical Skills (STR / AGI)',
      '- **Acrobatics (AGI):** Tumbling, balance, aerial maneuvers, fall mitigation.',
      '- **Athletics (STR/STA):** Sprinting, swimming, climbing, heavy lifting, physical endurance.',
      '- **Piloting (AGI/INT):** Starships, ground speeders, mecha, atmospheric craft.',
      '- **Stealth (AGI):** Hiding, silent movement, camouflage, shadow traversal.',
      '',
      '### II. Mental Skills (INT / WIS)',
      '- **Alertness (WIS):** Perception, hazard awareness, detecting hidden foes.',
      '- **Academics (INT):** Research, linguistics, humanities, ancient history.',
      '- **Computers (INT):** Cyber warfare, system intrusion, AI interaction, programming.',
      '- **Investigation (INT):** Forensics, crime scene analysis, deductive logic.',
      '- **Medicine (INT):** Combat triage, surgical intervention, pathology, cyber-surgery.',
      '- **Science (INT):** Chemistry, biology, xenology, planetary physics.',
      '- **Technology (INT):** Engineering, field repairs, weapon maintenance, fabrication.',
      '',
      '### III. Social Skills (CHA)',
      '- **Culture (CHA):** Etiquette, protocol, xenological customs.',
      '- **Deceit (CHA):** Bluffs, disguises, misdirection, undercover infiltration.',
      '- **Diplomacy (CHA):** Negotiation, treaties, conflict resolution, persuasion.',
      '- **Intimidation (STR/CHA):** Coercion, interrogation, psychological pressure.',
      '- **Streetwise (CHA/WIS):** Black market contacts, criminal underground navigation.',
      '',
      '### IV. Combat Skills (AGI / STR)',
      '- **Archaic Weapons (AGI/STR):** Swords, polearms, bows, thrown weapons.',
      '- **Modern Weapons (AGI):** Pistols, rifles, shotguns, submachine guns.',
      '- **Advanced / Heavy Weapons (STR/INT):** Plasma cannons, missile launchers, railguns.',
      '- **Unarmed Combat (STR/AGI):** Martial arts, brawling, grappling, subdual.',
      '- **Defense / Evasion (AGI):** Active dodges, parrying, kinetic deflection.',
      '',
      '### V. Metafocus Skills (INT / WIS / CHA)',
      '- **Attune (WIS/INT):** Drawing, channeling, and stabilizing metaphysical energy.',
      '- **Discipline Skills (6 Branches):** Dimension, Energy, Entropy, Illusion, Matter, Mental.'
    ].join('\n'),
    mechanic: 'SkillCheck = d20 + SkillRank + LinkedAttributeMod + SituationalModifiers\nFocusBonus: Rank 1-5 (+2), Rank 6-10 (+3), Rank 11-15 (+4), Rank 16-20 (+5), Rank 21-25 (+6), Rank 26-30 (+7)',
    guide: 'Roll d20 and add your skill rank plus the linked attribute modifier against the target DC.',
    note: 'Synergies: Having 5+ ranks in a prerequisite skill provides a +2 synergy bonus to related specialized checks.'
  },
  {
    id: '1-08-features-perks-master-codex',
    name: '1.08 Features & Perks Master Codex',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 8,
    description: [
      '# 1.08 Features & Perks Master Codex',
      '',
      'Features are modular special abilities that define unique heroic talents.',
      '',
      '---',
      '',
      '## Core Ability Features Table',
      '',
      '| Feature Name | Prerequisite | Effect & Mechanical Benefit | Category |',
      '| :--- | :--- | :--- | :--- |',
      '| **Great Fortitude** | Stamina 1+ | +2 bonus on all Fortitude saving throws | Ranked (Stamina) |',
      '| **Incredible Fortitude**| Great Fortitude | Roll all Fortitude saves with Advantage | Staged |',
      '| **Lightning Reflexes** | Agility 1+ | +2 bonus on Reflex checks and Initiative rolls | Ranked (Agility) |',
      '| **Superb Reflexes** | Lightning Reflexes | Roll all Reflex checks with Advantage | Staged |',
      '| **Potent Might** | Strength 1+ | +2 bonus on raw Might and Lift checks | Ranked (Strength) |',
      '| **Mighty Surge** | Potent Might | Roll raw Might checks with Advantage | Staged |',
      '| **Iron Will** | Wisdom 1+ | +2 bonus on Will saves and mental defense | Ranked (Wisdom) |',
      '| **Indomitable Will** | Iron Will | Roll all Will checks with Advantage | Staged |',
      '| **Insightful Reason** | Intellect 1+ | +2 bonus on Logic, Hack, and Forensic checks | Ranked (Intellect) |',
      '| **Inspiring Personality**| Charisma 1+ | +2 bonus on Etiquette and Leadership checks | Ranked (Charisma) |',
      '',
      '---',
      '',
      '## Combat & Tactical Features',
      '- **Point Blank Mastery:** Fire ranged weapons in melee reach without provoking Attacks of Opportunity; shots deal Advantage damage at point-blank range.',
      '- **Dual Weapon Mastery:** Attack with two weapons in a single action at a reduced -2 offhand penalty.',
      '- **Sniper Focus:** Take an aiming action to double the weapon\'s effective short range and ignore partial cover.'
    ].join('\n'),
    mechanic: 'Feature_Cost = 3 BP (2 BP if Recommended)\nRankedFeature_Cap = LinkedAttributeScore',
    guide: 'Choose features that complement your primary weapon systems, tactical roles, and attribute strengths.',
    note: 'Advantage granted by features does not stack; rolling twice is the maximum benefit.'
  },
  {
    id: '1-09-hindrances-karmic-debt-codex',
    name: '1.09 Hindrances & Karmic Debt Codex',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '1.00 CHARACTER CREATION',
    order: 9,
    description: [
      '# 1.09 Hindrances & Karmic Debt Codex',
      '',
      'Hindrances are character flaws, phobias, debts, and physical disabilities that grant bonus **Build Points (BP)** at character creation.',
      '',
      '---',
      '',
      '## Master Hindrance Value Directory',
      '',
      '| Hindrance | Bonus BP | Severity & Description |',
      '| :--- | :---: | :--- |',
      '| **Addiction** | 3 / 6 / 9 | Minor (3), Moderate (6), or Severe/Crippling (9) chemical dependency |',
      '| **Adversary / Nemesis**| 1 – 10 | Individual stalker (1–5) or powerful interstellar Syndicate (5–10) |',
      '| **Bodily Age (Child/Venerable)**| 5 / 10 | Physical penalties to STR/AGI/STA in exchange for social/knowledge perks |',
      '| **Covetous / Greed** | 3 / 6 / 9 | Compulsive greed, ambition, or treasure obsession |',
      '| **Dependent / Ward** | 3 / 6 / 9 | Innocent family member, AI core, or pet requiring constant protection |',
      '| **Disability (Limb)** | 3 / 6 / 9 / 18| Lost Hand/Foot (3), Full Limb (6), Multiple Limbs (9), Quadriplegic (18) |',
      '| **Distinctive Features** | 3 / 6 / 9 | Cybernetic scars, mutant pigmentation, or glowing biometric implants |',
      '| **Extreme Morality** | 4 / 8 / 12 | Rigid ethical code (Good, Lawful, Evil, Chaotic) that cannot be breached |',
      '| **Impaired / Lost Sense**| 3 / 6 / 9 | Lost Smell/Taste (3), Lost Touch/Hearing (6), Total Blindness (9) |',
      '| **Poor / Severe Debt** | 3 / 6 / 9 | -4 / -8 / -12 to starting Wealth; negative scores represent bounty debt |',
      '| **Unlucky (Karmic Debt)**| 3 / 6 / 9 | -2 / -4 / -6 penalty to maximum Karma pool |',
      '',
      '---',
      '',
      '## Rules on Hindrances',
      '',
      '- **Recommended Limit:** No character should take more than **15 BP** of Hindrances.',
      '- **Overcoming Hindrances:** A character may buy off a Hindrance during a campaign by paying its BP cost in experience points and completing a relevant story arc.'
    ].join('\n'),
    mechanic: 'Hindrance_MaxBonusBP = 15 BP\nWealthScore_Minimum = Can be negative (indicating syndicate debt/bounty)',
    guide: 'Select hindrances that spark compelling roleplay and dramatic tension during adventures.',
    note: 'Architects should actively integrate player hindrances into plot hooks and complication encounters.'
  }
];
