export const resolutionArticles = [
  {
    id: '2-01-d20-universal-resolution-engine',
    name: '2.01 The d20 Universal Resolution Engine',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '2.00 CORE RESOLUTION',
    order: 1,
    description: [
      '# 2.01 The d20 Universal Resolution Engine',
      '',
      'The Tangent Roleplaying System is driven by a unified **twenty-sided die (d20)** mechanic for resolving all uncertain actions, combat strikes, social interactions, and environmental hazards.',
      '',
      '---',
      '',
      '## The Core Resolution Formula',
      '',
      '\\text{Check Result} = d20 + \\text{Skill Rank} + \\text{Linked Attribute Modifier} + \\text{Situational Modifiers}',
      '',
      '- **Success:** If the total meets or exceeds the Target Difficulty Class (**DC**) or Opposed Defense score, the action succeeds.',
      '- **Failure:** If the total is less than the DC or Opposed Defense score, the action fails or introduces a narrative complication.',
      '',
      '---',
      '',
      '## Opposed vs. Unopposed Checks',
      '',
      '### 1. Opposed Checks (Contested Actions)',
      'When an action is actively resisted by another conscious entity (e.g. Melee Strike vs. Active Dodge, Bluff vs. Insight, Stealth vs. Perception):',
      '- **Attacker Rolls:**  + \\text{Attacking Skill} + \\text{Attribute Mod}$',
      '- **Defender Rolls:**  + \\text{Defending Skill} + \\text{Attribute Mod}$',
      '- **The Tie-Breaker Rule:** **DEFENDER WINS ALL TIES**.',
      '',
      '### 2. Unopposed Checks (Static Environmental Tasks)',
      'When a character interacts with a static object, bypasses security, or targets a stationary or surprised foe:',
      '- Attacker rolls against a fixed **Difficulty Class (DC)** set by the Architect or determined by standard benchmarks.'
    ].join('\n'),
    mechanic: 'Check = d20 + SkillRank + AttrMod + MiscMod\nOpposed: AttackerRoll > DefenderRoll (Defender wins on equal scores)',
    guide: 'Roll d20, add your skill rank and attribute modifier, and report the total to the Architect.',
    note: 'Critical Success (Natural 20) automatically succeeds in combat and adds bonus effect; Natural 1 is a critical complication.'
  },
  {
    id: '2-02-difficulty-classes-challenge-ratings',
    name: '2.02 Difficulty Classes & Challenge Ratings',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '2.00 CORE RESOLUTION',
    order: 2,
    description: [
      '# 2.02 Difficulty Classes & Challenge Ratings',
      '',
      'Difficulty Classes (**DCs**) define the difficulty of tasks across the galaxy, ranging from routine maintenance to deific reality-shaping.',
      '',
      '---',
      '',
      '## Standard Benchmark DC Table',
      '',
      '| DC | Difficulty Rating | Required Skill Level | Example Task |',
      '| :---: | :--- | :--- | :--- |',
      '| **5** | Very Easy / Routine | Untrained | Climbing a sturdy ladder, driving in clear weather |',
      '| **10** | Easy / Standard | Novice (Rank 1–5) | Picking a basic padlock, basic computer file search |',
      '| **15** | Moderate / Challenging | Trained (Rank 6–10) | Splicing an energized wire, first aid under fire, base un-opposed shot |',
      '| **20** | Hard / Professional | Expert (Rank 11–15) | Cracking military encryption, field-repairing a hyperdrive core |',
      '| **25** | Very Hard / Master | Master (Rank 16–20) | Disarming an active fusion warhead, tracking in vacuum |',
      '| **30** | Extreme / Heroic | Grand Master (Rank 21–25)| Subverting an AI dreadnought core, performing micro-surgery in zero-g |',
      '| **35+**| Near Impossible / Deific| Pinnacle (Rank 26–30) | Tearing open a localized spatial rift with pure metaphysical force |',
      '',
      '---',
      '',
      '## Challenge Ratings (CR) for Encounters',
      '',
      '- **CR equal to Party Level:** Standard, balanced combat encounter.',
      '- **CR = Party Level + 2:** Challenging encounter requiring tactical coordination.',
      '- **CR = Party Level + 4:** Deadly boss encounter; risk of character mortality is high.'
    ].join('\n'),
    mechanic: 'StandardDC = 15 (Base for typical unopposed check)\nModifierScale = +/- 5 for each tier of difficulty',
    guide: 'Compare your total roll against the DC announced by the Architect.',
    note: 'Architects can set partial success thresholds (e.g. succeeding at a cost if within 2 points of the DC).'
  },
  {
    id: '2-03-advantage-disadvantage-mechanics',
    name: '2.03 Advantage & Disadvantage Mechanics',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '2.00 CORE RESOLUTION',
    order: 3,
    description: [
      '# 2.03 Advantage & Disadvantage Mechanics',
      '',
      'Circumstances in Tangent can grant significant situational leverage (**Advantage**) or severe impairment (**Disadvantage**).',
      '',
      '---',
      '',
      '## Core Rules of Advantage & Disadvantage',
      '',
      '- **Advantage:** Roll **two twenty-sided dice ($)** and take the **higher result**. Add your standard skill and attribute modifiers.',
      '- **Disadvantage:** Roll **two twenty-sided dice ($)** and take the **lower result**. Add your standard skill and attribute modifiers.',
      '',
      '---',
      '',
      '## Common Sources',
      '',
      '### Gaining Advantage:',
      '- Attacking an unsuspecting or blinded target.',
      '- Firing a ballistic/energy weapon at **Point Blank Range** (within melee reach).',
      '- Possessing specialized sensory augmentations in favorable environments.',
      '- Flanking an enemy in close combat alongside an ally.',
      '',
      '### Suffering Disadvantage:',
      '- Attacking while prone, restrained, or concussed.',
      '- Firing ranged weapons into extreme darkness or heavy smoke without thermal sensors.',
      '- Attempting delicate technical repairs during severe planetary seismic tremors.',
      '',
      '---',
      '',
      '## Stacking Rules',
      '',
      'Advantage and Disadvantage **do not stack**. If multiple sources grant Advantage, you still roll only two dice. If a character has both Advantage and Disadvantage simultaneously from different sources, they **cancel each other out completely**, resulting in a standard single die roll.'
    ].join('\n'),
    mechanic: 'Advantage = max(d20_1, d20_2) + Modifiers\nDisadvantage = min(d20_1, d20_2) + Modifiers\nAdvantage + Disadvantage = 1d20 + Modifiers',
    guide: 'When Advantage is declared, roll two d20s simultaneously and choose the higher number before adding modifiers.',
    note: 'Advantage also applies to damage rolls when specified by special weapon properties (e.g. Point Blank shots).'
  },
  {
    id: '2-04-karma-points-fate-modification',
    name: '2.04 Karma Points & Fate Modification',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '2.00 CORE RESOLUTION',
    order: 4,
    description: [
      '# 2.04 Karma Points & Fate Modification',
      '',
      '**Karma** is an essential aspect of the Tangent RPG system that provides players with a limited resource they can strategically use to influence various aspects of the game. It serves as a pool of points that can be spent to affect dice rolls, modify character actions, and even shape narrative outcomes.',
      '',
      '---',
      '',
      '## 1. Karma Pool Basics',
      '',
      'Characters have **3 Karma Points** by default.',
      '',
      '- **Session Reset:** Karma resets to max (Default 3) at the start of every session. It does not regenerate via rest.',
      '- **Heroic Gain:** The GM / Architect may award 1 Karma Point immediately for "Heroic" or "Awesome" actions.',
      '- **Restoration:** All Karma Points are fully restored at the start of each game session, or regained through significant story moments (chapters) or by performing \'heroic\' or awesome actions. Karma Points are **not recovered by rest**.',
      '- **Increasing the Pool:** The *Karmic Blessing* feature allows characters to increase their maximum Karma Pool by **+1 point per rank** of the feature. Otherwise, the pool will be increased by possible storyline milestones and GM prerogative.',
      '',
      '---',
      '',
      '## 2. Using Karma Points (The 6 Actions)',
      '',
      '| Expenditure Option | Timing | Cost | Scope & Effect |',
      '| :--- | :--- | :---: | :--- |',
      '| **"I Got This"** | Declare *before* making the roll | 1 KP | **Advantage on Any Single Roll:** Roll twice, keep higher result. Usable on ability checks, skill checks, attacks, saves, and damage rolls. |',
      '| **"Not What I Meant"** | Declare *immediately after* initial roll | 1 KP | **Reroll Ability / Non-Combat Skill Check:** Discard roll and reroll. Must accept 2nd result even if worse. Cannot be used on combat/attack rolls. |',
      '| **"Shake it Off"** | Declare anytime suffering temporary condition | 1 KP | **Reduce Condition Severity by 1 Stage:** Lowers conditions like Poisoned, Stunned, or Blinded by one level (e.g. Major to Minor). |',
      '| **"Second Wind"** | Spend 1 full minute of internal focus | 1 KP | **Replaces Light Rest:** Bypasses downtime to instantly refresh daily limited-use abilities, special attacks, traits, or features. |',
      '| **"So Mote it Be"** | Declare *simultaneously* with metaphysical skill/feat | 1 KP | **Metaphysical Potency:** Boosts metaphysical check potency (range, duration, magnitude) or activates a specialized discipline Karma Feat. |',
      '| **"By Will Alone"** | Declare action with GM approval | 1 KP | **Push Limits / Narrative Agency:** Attempt impossible or unlisted actions, emulate a basic feature for a scene, or nudge a rule in character\'s favor. |',
      '',
      '### Detailed Action Rules',
      '',
      '#### "I Got This"',
      'Gains **Advantage** (roll twice, take higher result) on any single dice roll, including ability checks, skill checks, attack rolls, saving throws, and damage rolls. Must be declared **before** rolling.',
      '',
      '#### "Not What I Meant"',
      'Rerolls an Ability Check or a non-combat Skill Check. Declared **immediately after** the initial roll. Attack and combat rolls are excluded. The 2nd roll must be accepted even if worse.',
      '',
      '#### "Shake it Off"',
      'Reduces the severity stage of a temporary condition (Poisoned, Stunned, Blinded) by **one stage** (e.g., Major to Minor). Usable anytime while afflicted.',
      '',
      '#### "Second Wind"',
      'Takes **1 full minute** of deep focus to achieve the complete benefits of a Light Rest without requiring normal downtime, recharging limited-use daily abilities, special attacks, and traits.',
      '',
      '#### "So Mote it Be"',
      'Available to metaphysics users. Declared **simultaneously** with the skill/feat to boost potency (power, range, duration) or activate a unique discipline Karma Feat.',
      '',
      '#### "By Will Alone"',
      'Push past normal boundaries with GM approval. Costs 1 Karma Point regardless of outcome. Success is not guaranteed; GM determines appropriate challenge roll.',
      '',
      '---',
      '',
      '## 3. Plot Points',
      '',
      'Plot Points are a special resource awarded by the GM to players actively engaging with the story and its challenges.',
      '- **Separate Resource:** Operates like Karma, but is separate and does not count against the character\'s Karma Pool maximum.',
      '- **Temporary & Specific:** Tied to the scenario or story arc in which they were awarded.',
      '- **Compensation & Balance:** Granted when characters face adversity beyond their control, balancing challenges and enhancing narrative agency.',
      '',
      '---',
      '',
      '## 4. Negative Karma (Karmic Debt)',
      '',
      'Characters may spend Karma into the negatives when out of points, entering "Karmic debt".',
      '- **Debt Limit:** Capped at **Charisma score + 1** (e.g. Charisma 3 allows down to -4 Karma).',
      '- **GM Discretion:** Allowance and triggering of Karmic Debt effects is at the GM\'s discretion.',
      '- **Karmic Effects:** GM may impose **Disadvantage on rolls** (roll twice, take lower), force **Rerolls** on successful checks, or grant **NPC Benefits** (increased luck/skills to opponents).'
    ].join('\n'),
    mechanic: 'BaseKarma = 3\nMaxKarmaDebt = Charisma + 1\nAdvantage = Roll 2d20, Take Highest Result\nDisadvantage = Roll 2d20, Take Lowest Result\nConditionReduction = -1 Severity Stage (Major -> Minor -> Cleared)\nSecondWind = 1 Min Focus, Replaces Light Rest',
    guide: 'Declare "I Got This" before rolling; declare "Not What I Meant" immediately after rolling. Spend into Karmic Debt only during life-or-death emergencies.',
    note: 'Negative Karma grants the Architect dramatic complication triggers until the debt is worked off or reset.'
  }
];
