export const combatArticles = [
  {
    id: '3-01-combat-action-economy',
    name: '3.01 Combat Action Economy & Skill Tier Progression',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 1,
    description: [
      '# 3.01 Combat Action Economy & Skill Tier Progression',
      '',
      'Combat in Tangent is fast-paced and tactical. The number of actions a character can perform in a single 6-second round is governed by their **Skill Tier** in the relevant combat discipline.',
      '',
      '---',
      '',
      '## Action Unlocks by Skill Tier',
      '',
      '| Rank Range | Title / Benchmark | Actions per Round | Focus Strike Bonus | Cumulative Penalty |',
      '| :--- | :--- | :--- | :---: | :--- |',
      '| **0** | Untrained | Full Round Action (1 basic move/attack) | — | Base score |',
      '| **1 – 5** | Novice / Studied | **1st Action** | **+2** | Base score |',
      '| **6 – 10** | Trained / Professional | **2nd Action** | **+3** | 2nd attack at base **-5** |',
      '| **11 – 15** | Expert | **3rd Action** | **+4** | 3rd attack at base **-10** |',
      '| **16 – 20** | Master | **4th Action** | **+5** | 4th attack at base **-15** |',
      '| **21 – 25** | Grand Master | **5th Action** | **+6** | 5th attack at base **-20** |',
      '| **26 – 30** | Pinnacle | **6th Action** | **+7** | 6th attack at base **-25** |',
      '',
      '---',
      '',
      '## Multiple Active Defenses',
      '',
      'Characters may execute multiple active defense reactions (Dodge, Parry, Kinetic Block) in response to incoming attacks within a single round. Each consecutive defense roll after the first suffers a cumulative **-5 penalty** (1st defense: base; 2nd defense: -5; 3rd defense: -10; 4th defense: -15).'
    ].join('\n'),
    mechanic: 'ActionCount = floor((SkillRank - 1) / 5) + 1 (for Rank >= 1)\nActionPenalty = (ActionIndex - 1) * -5\nActiveDefensePenalty = (DefenseCount - 1) * -5',
    guide: 'Declare all actions at the start of your turn. Apply the cumulative -5 modifier to subsequent attacks.',
    note: 'Focus bonus is added to all strike rolls made with the dedicated weapon category.'
  },
  {
    id: '3-02-initiative-turn-sequence',
    name: '3.02 Initiative & Turn Sequence',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 2,
    description: [
      '# 3.02 Initiative & Turn Sequence',
      '',
      'At the onset of combat, all combatants roll for **Initiative** to establish the chronological turn order.',
      '',
      '---',
      '',
      '## The Initiative Formula',
      '',
      '$$\\text{Initiative Roll} = 2d10 + \\text{Reflex Save} + \\text{Agility Modifier} + \\text{Situational Modifiers}$$',
      '',
      '- **High Roll Goes First:** Combatants act in descending order of initiative totals.',
      '- **Ties:** Broken first by higher Agility score, then by higher Alertness skill rank.',
      '',
      '---',
      '',
      '## Ambushes & Surprise Rounds',
      '',
      '- If an attacking group successfully ambushes unaware targets (via Stealth vs. Alertness check):',
      '  - The attackers gain a **Surprise Round**, during which they may take a full turn of actions.',
      '  - Unaware targets cannot take active defense actions during the surprise round and are treated as having an **Unopposed Defense DC (Base 15)**.'
    ].join('\n'),
    mechanic: 'Initiative = 2d10 + ReflexMod + AgilityMod + SensoryAugmentBonus\nSurprise = Defender Flatfooted (Defense = 15 modified by size/cover)',
    guide: 'Roll initiative once at the beginning of an encounter. Turn order remains fixed until combat concludes.',
    note: 'Characters with the Lightning Reflexes feature add +2 to all initiative rolls.'
  },
  {
    id: '3-03-attack-defense-resolution',
    name: '3.03 Attack & Defense Resolution (Opposed & Unopposed)',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 3,
    description: [
      '# 3.03 Attack & Defense Resolution (Opposed & Unopposed)',
      '',
      'Combat interactions are categorized into two core resolutions using the **2d10 system**:',
      '',
      '---',
      '',
      '## 1. Opposed Resolution (Active Defense)',
      '',
      'When targeting an active, aware opponent:',
      '- **Attacker Rolls:** $2d10 + \\text{Combat Skill Rank} + \\text{Attribute Mod} + \\text{Situational Modifiers}$',
      '- **Defender Rolls:** $\\text{Defender\'s Agility} + \\text{Defense Skill Rank} + \\text{Shield/Dodge Mod}$',
      '- **Outcome:**',
      '  - Attacker > Defender: **Hit / Strike Success**.',
      '  - Defender $\\ge$ Attacker: **Miss / Evaded**. *(Defender wins all ties)*.',
      '',
      '---',
      '',
      '## 2. Unopposed Resolution (Stationary / Surprised Target)',
      '',
      'When targeting an inanimate object, a disabled vehicle, or a surprised foe:',
      '- Attacker rolls vs. a static **Base CR 15 (Average Medium Target at Short Range)**.',
      '- Modified by Target Size, Range Brackets, and Movement penalties.'
    ].join('\n'),
    mechanic: 'Opposed: Attacker (2d10 + Skill + Attr + Mod) vs Defender (Agility + Defense Skill + Mod) [Defender wins ties]\nUnopposed: AttackCheck vs (15 + SizeMod + RangeMod + MoveMod)',
    guide: 'Declare your target, roll attack check, and compare against opposed defense roll or target DC.',
    note: 'Point blank shots against unopposed targets deal Advantage damage automatically.'
  },
  {
    id: '3-04-size-range-modifiers-matrix',
    name: '3.04 Size & Range Modifiers Matrix',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 4,
    description: [
      '# 3.04 Size & Range Modifiers Matrix',
      '',
      'Target scale and physical distance substantially modify attack rolls and un-opposed target DCs.',
      '',
      '---',
      '',
      '## Target Size Modifiers Matrix',
      '',
      '| Size Category | Scale Example | Attack / DC Modifier | Melee Reach |',
      '| :--- | :--- | :---: | :---: |',
      '| **Miniscule** | Micro-drone, cyber-insect | **-32** | 0 ft |',
      '| **Fine** | Small rodent, tracking beacon | **-16** | 0.5 ft |',
      '| **Diminutive** | Cat, sidearm drone | **-8** | 1 ft |',
      '| **Tiny** | Small pet, recon turret | **-4** | 2 ft |',
      '| **Small** | Halfling, combat dog, goblin | **-2** | 5 ft |',
      '| **Medium (Standard)**| Human, Elf, Cyber-Trooper | **0** | **5 ft** |',
      '| **Large** | War horse, light speeder, ogre | **+2** | 10 ft |',
      '| **Huge** | Heavy combat mecha, APC | **+4** | 15 ft |',
      '| **Gargantuan** | Dropship, titan walker | **+8** | 20 ft |',
      '| **Colossal** | Star cruiser, orbital station | **+16** | 30+ ft |',
      '',
      '---',
      '',
      '## Range Brackets Matrix',
      '',
      '| Range Category | Distance Modifier | Effective Range Bracket | Special Combat Rule |',
      '| :--- | :---: | :--- | :--- |',
      '| **Point Blank** | **+5 (DC 10)** | Within Melee Reach (5 ft) | **Roll Damage with Advantage** |',
      '| **Short** | **0 (DC 15)** | Listed Base Range | Standard strike |',
      '| **Medium** | **-5 (DC 20)** | Up to \\times$ Base Range | Long-range aim required |',
      '| **Long** | **-10 (DC 25)**| Up to \\times$ Base Range | Severe trajectory drop |',
      '| **Extreme** | **-15 (DC 30)**| Up to \\times$ Base Range | Requires sniper optics |'
    ].join('\n'),
    mechanic: 'EffectiveDC = 15 + SizeModifier + RangeModifier\nPointBlankDamage = max(DamageRoll1, DamageRoll2) + Bonus',
    guide: 'Check weapon base range and target size to determine applicable modifiers to your attack roll.',
    note: 'Point blank shots with long rifles in melee reach provoke attacks of opportunity unless the user has Point Blank Mastery.'
  },
  {
    id: '3-05-movement-target-modifiers',
    name: '3.05 Movement & Target Situational Modifiers',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 5,
    description: [
      '# 3.05 Movement & Target Situational Modifiers',
      '',
      'Physical motion and battlefield positioning dynamically affect targeting accuracy and defensive evasion.',
      '',
      '---',
      '',
      '## Movement Modifiers Matrix',
      '',
      '| Movement Context | Scenario / Rule | Defender Bonus | Attacker Penalty | Tactical Notes |',
      '| :--- | :--- | :---: | :---: | :--- |',
      '| **Moving Targets** | Target Running | — | **-2 Attack** | Target is sprinting across terrain |',
      '| | Distance Moved (20+ ft) | **+2 Defense** | — | Evasive zig-zag movement |',
      '| | Distance Moved (40+ ft) | **+4 Defense** | — | High-speed dash |',
      '| | Total Defense / Full Dodge | **+4 Defense** | — | Dedicates entire turn to evasion |',
      '| | Opportunity Attacks | Provokes AoO | Free Attack | Moving out of melee reach |',
      '| **Moving Attackers** | Ranged Shot while Running | — | **-2 Attack** | Fire on the move |',
      '| | Mounted / Vehicle (Double Move)| — | **-4 Attack** | Firing from moving platform |',
      '| | Mounted / Vehicle (Quad Speed) | — | **-8 Attack** | Firing from high-speed pursuit |'
    ].join('\n'),
    mechanic: 'TargetMoveBonus = (MovedFeet >= 40) ? 4 : ((MovedFeet >= 20) ? 2 : 0)\nRunningShooterPenalty = -2',
    guide: 'Keep track of your movement distance each round to apply the +2 or +4 defense bonus.',
    note: 'The Total Defense action prevents all offensive actions for that turn.'
  },
  {
    id: '3-06-cover-concealment-modifiers',
    name: '3.06 Cover, Concealment & Environmental Modifiers',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 6,
    description: [
      '# 3.06 Cover, Concealment & Environmental Modifiers',
      '',
      'Cover physically stops incoming kinetic and energy projectiles, while concealment obscures the target\'s visual profile.',
      '',
      '---',
      '',
      '## Cover & Concealment Rules',
      '',
      '| Protection Type | Environmental Example | Defense / DC Bonus | Special Effect |',
      '| :--- | :--- | :---: | :--- |',
      '| **Light Cover (1/4)** | Low barricade, tree trunk | **+2 Defense** | Protects legs and lower torso |',
      '| **Medium Cover (1/2)** | Sandbags, steel barrier, vehicle hull | **+4 Defense** | Protects 50% of body profile |',
      '| **Heavy Cover (3/4)** | Bunker slit, fortified firing port | **+6 Defense** | Protects 75% of body; grant Fortitude bonus |',
      '| **Full / Total Cover** | Solid reinforced blast door | **Cannot Target** | Requires indirect or penetrative fire |',
      '| **Light Concealment** | Light fog, haze, dim lighting | **-2 to Attacker** | Obscures fine detail |',
      '| **Heavy Concealment** | Dense smoke, total darkness, active camo | **-4 to Attacker** | Attacker must guess grid square without thermal optics |'
    ].join('\n'),
    mechanic: 'CoverBonus = +2 (Light), +4 (Medium), +6 (Heavy)\nConcealmentPenalty = -2 (Light), -4 (Heavy)',
    guide: 'Position your character behind barriers at the end of movement to gain defensive cover bonuses.',
    note: 'Weapons with high Armor Piercing (AP) ratings can shoot directly through light and medium cover.'
  },
  {
    id: '3-07-armor-dr-damage-calculation',
    name: '3.07 Master Damage Calculation, Metafocus & Precision Resolution',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 7,
    description: [
      '# 3.07 Master Damage Calculation, Metafocus & Precision Resolution',
      '',
      'Damage in Tangent is resolved through a unified formula incorporating weapon force, relevant abilities, precision bonuses, target armor protection, and natural resilience.',
      '',
      '---',
      '',
      '## The Master Damage Formula',
      '',
      '$$\\text{Total Damage} = (\\text{Weapon Dice} + \\text{Relevant Ability Mod} + \\text{Precision Damage}) - (\\text{Target Armor DR} + \\text{Target CON Mod})$$',
      '',
      '### Core Calculation Components',
      '- **Weapon Die Damage:** Base rolled damage from the physical weapon or metaphysical invocation tier.',
      '- **Relevant Ability Modifier:** Applied according to the combat vector:',
      '  - **Strength:** Melee attacks, brawling strikes, and throwing heavy objects.',
      '  - **Agility:** Finesse of light or natural weapons and most ranged physical attacks.',
      '  - **Intelligence:** Directly weaving and calculating magical or technological effects.',
      '  - **Charisma:** Subtle, emotional, and controlling metaphysical factors.',
      '  - **Stamina & Wisdom (Defensive):** Guard the body (**Fortitude**) and mind (**Willpower**) defensively. *Wisdom may substitute for Int/Cha in Metaphysic Skill checks for faith-based casters.*',
      '- **Precision Damage:** Bonus directly from the attacker\'s skill level (relative Combat or Focus Skill Rank).',
      '- **Active Defense Counter:** A defender who is actively defending reduces incoming damage by their **Defense score** (acting as a direct reduction against precision bonuses).',
      '- **Target\'s Armor DR:** Subtracted based on armor resistance against the specific damage type.',
      '- **Target\'s CON Mod:** Innate physiological resilience mitigating harm.',
      '- **Sneak Attack Activation:** Added **only if at least 1 point of damage penetrates target Armor DR** (determined after Armor DR but before Stamina/CON modifier).',
      '',
      '---',
      '',
      '## Metafocus (Metaphysical Attacks)',
      '- **Invocation as Weapon:** An Invocation is treated as the weapon with damage dice and type determined accordingly.',
      '- **Attack Roll:** Rolled with the **Attune Skill** (Strike roll, opposed by target Defense score or setting the saving throw CR).',
      '- **Damage & Magnitude:** Potency is determined by the **Invocation Tier and Discipline Skill Level**.',
      '- **Spontaneous Casting:** Fully supported, using the relevant **Discipline\'s Skill Rank**.'
    ].join('\n'),
    mechanic: 'TotalDamage = (WeaponDice + AbilityMod + PrecisionDamage) - (ArmorDR + TargetCONMod)\nActiveDefense: Deducts Defender Defense Score from incoming damage in counter to Precision\nSneakAttack: Adds bonus damage only if >= 1 pt penetrates Armor DR (before CON Mod)\nMetafocus: Attune Skill vs Defense/CR; Damage set by Invocation Tier + Discipline Level',
    guide: 'Subtract target Armor DR and CON Mod from incoming damage. If defender is actively defending, subtract Defense score from precision damage.',
    note: 'Dual 10s (Natural 20) doubles weapon damage dice and adds +30 to base attack score. Dual 1s (Natural 2) subtracts 10 from attack score.'
  },
  {
    id: '3-08-damage-types-energy-resistances',
    name: '3.08 Master Damage Types Directory & Energy Profiles',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 8,
    description: [
      '# 3.08 Master Damage Types Directory & Energy Profiles',
      '',
      'Tangent features a rich ecosystem of damage types categorized into Kinetic, Energy, and Variative/Elemental profiles across Archaic, Modern, Advanced Tech, and Metaphysical vectors.',
      '',
      '---',
      '',
      '## Master Damage Types Directory',
      '',
      '| Damage Type | Category | Primary Mechanical Effect | Common Vector / Weaponry |',
      '| :--- | :--- | :--- | :--- |',
      '| **Blunt** | Kinetic | Crushing trauma, bone fractures | Clubs, maces, hammers, power gauntlets |',
      '| **Slashing** | Kinetic | Deep lacerations; crits inflict **Bleeding** | Swords, axes, vibroblades, monomolecular edges |',
      '| **Piercing** | Kinetic | Pinpoint organ penetration; crits inflict **Bleeding** | Spears, daggers, AP rounds, railguns, flechettes |',
      '| **Force** | Kinetic Subtype | **Ignores 1/2 of Target Armor DR** | Concussive kinetic fields, gravitic crushers |',
      '| **Concussive / Impact**| Kinetic | Dispersed whole-body trauma; **50/50 Vitality/Health split** | Falls, crashes, explosives, siege engines |',
      '| **Bleed** | Kinetic Effect | **1d4 damage/turn, ignores Armor DR** | Slashing/piercing critical wounds |',
      '| **Pyro / Fire** | Energy | Burns and incinerates; inflicts **Burning** (1d6/round) | Flamethrowers, incendiary ammo, plasma, pyrokinesis |',
      '| **Cryo / Cold** | Energy | Thermal drain slowing speed; inflicts **Freeze** (Speed 0) | Cryo-guns, cryo-lasers, liquid nitrogen, cryokinesis |',
      '| **Spectral / Phase** | Energy | **Ignores physical Armor DR entirely** to disrupt essence | Phase rifles, ghost touch, spirit weapons |',
      '| **Sonic / Sound** | Energy | **Ignores most physical armor** via vibrational acoustic shock | Sonic cannons, saser beams, flash-crackers, sonokinesis |',
      '| **Voltic / Electrical**| Energy | Stuns nervous systems, overloads robotics and electronics | Tasers, arc cannons, EMP devices, electrokinesis |',
      '| **Corrosive / Disintegration** | Energy | **Permanently degrades Armor DR**; dissolves materials | Alchemical vitriol, acid sprayers, nanite swarms |',
      '| **Ra-D / Radiation** | Energy | Cellular necrosis, mutation, and radiation sickness | Dirty bombs, neutron cannons, grasers, radiokinesis |',
      '| **Force Pulse / Disruption** | Energy | Destabilizes molecular bonds; disintegrates targets on crits | Disruptor pistols/cannons, molecular disruptors |',
      '| **Air Elemental** | Variative | Atmospheric gales knocking foes **Prone** and suffocating | Compressed air cannons, vortex generators, aerokinesis |',
      '| **Fire Elemental** | Variative | Primal volcanic flames scorching terrain and applying Burning | Fire evocation, incendiary saturation |',
      '| **Earth Elemental** | Variative | Crushing lithic weight and tremors knocking foes Prone | Seismic cannons, rockfalls, geokinesis |',
      '| **Water Elemental** | Variative | Hydraulic pressure and drowning trauma | High-pressure waterjets, vortex emitters, hydrokinesis |',
      '| **Radiant / Light** | Variative | Pure solar photons inflicting the **Blinded** condition | Flashbangs, coherent lasers, photokinesis |',
      '| **Umbral / Shadow** | Variative | Void darkness draining vitality and inflicting Exhaustion | Dark energy projectors, shadow evocation, umbrokinesis |',
      '| **Celestial** | Variative | Transcendent sacred energy smiting fiends and undead | Consecrated weapons, holy water, celestial evocation |',
      '| **Infernal** | Variative | Corrupting hellfire and Stygian soul-taint | Infernal relics, hellfire curses, infernal evocation |',
      '| **Dimensional** | Variative | Reality tearing that **completely bypasses Armor DR** | Phase rifts, spatial cannons, pocket dimension collapses |',
      '| **Psyche / Mental** | Variative | Direct psionic neural trauma **ignoring physical Armor DR** | Neural disruptors, psychic assaults, telepathy |'
    ].join('\n'),
    mechanic: 'Concussive: 50/50 Vitality/Health split on attempted reduction; 1/2 Hard Armor DR; Falling ignores DR\nForce: Ignores 1/2 Armor DR\nPhase, Dimensional, Mental: Ignore physical Armor DR\nCorrosive: Degrades 1 DR per 5 unsoaked damage\nBurning: 1d6/round (Will DC 12 panic)\nFreeze: Speed 0, Vulnerable to Physical & Sonic',
    guide: 'Match weapon damage types to enemy vulnerabilities. Apply appropriate status effects on critical wounds.',
    note: 'Spectral, Dimensional, and Mental attacks bypass physical armor entirely and are resisted only by Willpower, Reason, or active energy fields.'
  },
  {
    id: '3-09-health-vitality-mortality-trauma',
    name: '3.09 Health, Vitality, Limb Trauma & Mortality State (0 HP Rules)',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 9,
    description: [
      '# 3.09 Health, Vitality, Limb Trauma & Mortality State (0 HP Rules)',
      '',
      'Combat lethality in Tangent tracks vital hit points, limb damage thresholds, and the **Mortality State (0 HP)**.',
      '',
      '---',
      '',
      '## 1. Limb Damage Thresholds: Disabled vs. Destroyed',
      '',
      '### Disabled (1/3rd Health in Damage to a Limb)',
      '- Taking **1/3rd of Health Score** in damage to a limb disables it (or causes Unconsciousness if dealt to the Head).',
      '- **Stamina Check:** Pass a **Stamina Check with CR = 10 + Damage Taken** to keep using the limb.',
      '- **Penalties:**',
      '  - **Head:** **-4 on all actions**.',
      '  - **Arm:** **-4 Strength and Agility** for actions using that arm.',
      '  - **Leg:** **Half Ground Speed** and **no Rush Maneuver**.',
      '- Requires medical attention or Metaphysics to properly restore function.',
      '',
      '### Destroyed (2/3rds Health in Damage to an Area)',
      '- Taking **2/3rds of Health Score** in damage to an area damages it **beyond ANY further use** (Brain Death** if Head).',
      '- **NO Check:** It is mangled beyond repair. Traumatic Damage Control is immediately required for shock, blood loss, and vital collapse.',
      '- \\*\\* *Brain death is at GM discretion. If the character survives, they remain permanently disabled and require surgery and intense downtime.*',
      '',
      '---',
      '',
      '## 2. Technology Level 3+ Limb Replacements & Cybernetics',
      '- **Surgery & Recovery:** A replacement limb requires **1 day of surgery and recovery** whether Biological or Synthetic.',
      '  - **Biological Limb:** Must be tissue-matched (**+1 day**) or lab-grown (**+2d4 days**).',
      '  - **Synthetic Cyber-Limb:** Available stock can be prepped for installation during surgery time.',
      '- **Body Replacement:** Tech 4 Tran-Cerebral Venture; Tech 5 Consciousness Transfer.',
      '- **Durability:** Biological limbs have baseline capacity. Synthetic limbs take **50% more damage** before reaching Disabled or Destroyed, but **may NOT get the Stamina check** to remain functional once reaching Disabled.',
      '',
      '---',
      '',
      '## 3. The Mortality State (0 Hit Points)',
      'When a character\'s Health Points reach 0, they immediately enter the **Mortality State**:',
      '1. **Unconscious and Incapacitated:** The character immediately falls Prone and is Incapacitated.',
      '2. **Bleeding Out:** At the beginning of the character\'s turn, they suffer **1 point of Stability Damage**.',
      '3. **Stability Threshold:** A character has a Stability Points total equal to their **Constitution Score + 5**.',
      '4. **Death:** If Stability Points reach 0, the character expires.',
      '5. **Stabilization:** First aid via Medicine Check (DC 15) or metaphysical healing stabilizes the character.'
    ].join('\n'),
    mechanic: 'Disabled: 1/3 Health -> Sta check CR 10+dmg (-4 actions head, -4 Str/Agi arm, 1/2 speed leg)\nDestroyed: 2/3 Health -> Mangled, no check, brain death GM discretion\nSynthLimbs: +50% damage threshold before Disabled/Destroyed (no Sta check)\nMortality: 0 HP -> Prone, Incapacitated, Bleeding Out (-1 Stability/rnd), Stability Pool = CON + 5',
    guide: 'When a limb takes 1/3 Health, roll Stamina check CR 10 + damage to maintain function. At 0 HP, track Stability Points each round.',
    note: 'Synthetic limbs take 50% more damage before disabling than biological equivalents.'
  },
  {
    id: '3-10-hit-locations-called-shots-matrix',
    name: '3.10 Hit Locations & Called Shots (d10 Table)',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 10,
    description: [
      '# 3.10 Hit Locations & Called Shots (d10 Table)',
      '',
      'Combatants can attempt precise **Called Shots** or roll for random hit locations on critical strikes using a **d10** (or **1d6 in Melee/Unarmed** unless a Leg attack/maneuver is declared).',
      '',
      '---',
      '',
      '## Called Shot Modifiers',
      '- **Torso or Leg:** **-2 Strike Penalty**',
      '- **Head or Arm:** **-4 Strike Penalty**',
      '',
      '---',
      '',
      '## Locations & Trauma Saves Table',
      '',
      '| Roll (d10) | Location | Trauma Effect | Save & Failure Severity |',
      '| :---: | :--- | :--- | :--- |',
      '| **1** | **HEAD** | **KO** | **Reason Save** or Stunned for 1+ rounds*; failure by 10+ = **Unconscious**. |',
      '| **2, 3, 4** | **TORSO** | **Winded** | **Fortitude Save** or cumulative -2 on actions for 1+ rounds*; failure by 10+ = **Gasping / Incapacitated**. |',
      '| **5 (R) or 6 (L)** | **ARM** | **Disarmed** | **Reflex Save** or drop held item; failure by 10+ = **Arm Crippled / Non-Functional**. |',
      '| **7, 8 (R) or 9, 0 (L)**| **LEG** | **Hobbled** | **Might Save** or half speed for 1+ rounds*; failure by 10+ = **Leg Crippled / Non-Functional**. |',
      '',
      '\\* **Duration of Impediment:** 1 round per point rolled under the save CR (where CR is based directly on the damage dealt).'
    ].join('\n'),
    mechanic: 'HitLocation: 1d10 (1 Head, 2-4 Torso, 5-6 Arm, 7-0 Leg; 1d6 melee)\nCalledShots: -2 Torso/Leg, -4 Head/Arm\nTraumaSaves: Head (Reason), Torso (Fort), Arm (Ref), Leg (Might)\nDuration: 1 round per point rolled under save CR (CR = damage dealt)',
    guide: 'Roll 1d10 on critical hit or called shot. Target rolls indicated save against damage CR; failure induces trauma for 1 round per point under CR.',
    note: 'In Melee and Unarmed combat, roll 1d6 unless a specific leg attack or trip maneuver is declared.'
  },
  {
    id: '3-11-combat-maneuvers-guide',
    name: '3.11 Combat Maneuvers & EDGE Tactical Modifiers Guide',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 11,
    description: [
      '# 3.11 Combat Maneuvers & EDGE Tactical Modifiers Guide',
      '',
      '**Edge** refers to tactical advantage modifiers that characters can gain or lose based on their movements, positions, and the environment during combat.',
      '',
      '---',
      '',
      '## Master EDGE Modifiers Catalog',
      '',
      '- **Aiming:** Having target in sights to steady and lead shot; gain **+2 to Strike per round of Aiming** (up to 1/2 attacker\'s Skill Level). Attacker cannot move before shooting.',
      '- **Flanking:** Advantage gained when attacker has allies positioned on multiple sides of the target; grants **+2 bonus to hit**.',
      '- **Advancing Target:** Target approaching without Cover or Evasion. Grants an **Extra Attack on target at -5 to Strike** and re-roll Initiative if successfully moved into Melee.',
      '- **Retreating Target:** Target quickly leaving area without evasion/cover at Jog/Run/Sprint Speed. Grants an **Extra Attack on target at -5 to Strike** and reroll Initiative.',
      '- **High Ground:** **+2 to Strike** and **+2 to Critical Damage Range**.',
      '- **Prone:** On the ground:',
      '  - Vs. opponent in Melee/Point Blank Range: Opponent gains **High Ground Bonus**.',
      '  - Vs. Ranged opponent: Receive **+2 Defense Bonus** for each Range Category after Point Blank for ground cover (High Ground at Range reduces accordingly).',
      '  - Successful Defense check allows taking **full cover** from Ranged Attacks.',
      '- **Braced:** Set to receive a Charge or stay in place. Block usable as counter attack on hit (or readied weapon), bonus gained for Advancing Target, negates heavy recoil, grants Advantage vs trip/shove.',
      '- **Charge:** On successful strike add **+1d to Attack Damage**, **-1 to strike per stage of speed** (walk, jog, run, sprint), plus **+1 Point of Impact Damage per 10 ft of Speed** (up to max +100% damage increase). -2 Def, -2 Atk.',
      '- **Close In:** Guarded approach, defensive advancement at base speed. **NO Modifiers** and not counted as an Advancing Target.',
      '- **Withdraw:** Pulling back defensively at base speed. **NO Modifiers** and not counted as a Retreating Target.',
      '- **Evasive Movement:** Fully defensive while moving quickly: **+1 Defense** and another **+1 per 10ft Movement Speed**.',
      '- **Subtle:** Quiet, sneaky, low-key condition avoiding attention; required for availability of stealth-based Skill Actions.',
      '- **Feint:** Bluff check (vs Sense Motive) leads target into False Defense, allowing a **Sneak Attack at -5 to Strike** (Target has **NO Defense**).',
      '- **Surprise / Sneak Attack:** Target is unaware and has **NO Defense**. Attack at **-5 to hit**, Damage rolled at **Advantage**. Danger Sense allows Advantage check to be aware.'
    ].join('\n'),
    mechanic: 'Aiming: +2 Strike/rnd (up to 1/2 Skill)\nFlanking: +2 Hit\nHigh Ground: +2 Strike, +2 Crit Range\nFeint: Bluff vs Sense Motive -> Sneak Attack at -5 vs 0 Def\nCharge: -2 Def/-2 Atk, +1d Dmg, -1 Atk/stage, +1 Impact/10ft',
    guide: 'Choose a maneuver as an action on your turn to manipulate enemy positioning and leverage Edge modifiers.',
    note: 'Close In and Withdraw prevent provoking defensive Advancing/Retreating counter-attacks.'
  },
  {
    id: '3-12-status-conditions-effects',
    name: '3.12 Canonical Status Effects & Conditions Matrix',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 12,
    description: [
      '# 3.12 Canonical Status Effects & Conditions Matrix',
      '',
      'Complete reference matrix of all 10 tactical combat status effects, mechanical penalties, and cures/removals.',
      '',
      '---',
      '',
      '## Master Status Effects Table',
      '',
      '| Status | Mechanical Effect | Cure / Removal |',
      '| :--- | :--- | :--- |',
      '| **Bleeding** | Target takes 1d4 Damage at start of their turn. Ignores Armor/DR. | Medicine Check (DC 10) or any Healing ability/item. |',
      '| **Blinded** | -5 Penalty to Attack/Defense. Visual Perception fails automatically. | Medical intervention or Time (Temporary: 1d4 rounds). |',
      '| **Burning** | Takes 1d6 Fire Damage per round. Panic Check (Will DC 12) or flail/flee. | Full Action to extinguish (Stop, Drop, Roll). |',
      '| **Dazed** | Mentally reeling. Only 1 Action per turn (Move OR Standard). No Reactions. | Ends automatically at the end of the creature\'s next turn. |',
      '| **Entangled** | Movement = 0. -2 Penalty to Attack/Defense. No Dodge/Evasion. | Strength Check (DC 15) or Cutting free (Structure damage). |',
      '| **Exhausted** | -2 Penalty to Physical Checks (Str/Agi/Sta). Speed -50%. No Run/Charge. | Requires 8 Hours of Rest with food/water. |',
      '| **Freeze** | Target is encased/chilled. Speed = 0. Target gains Vulnerability to Physical & Sonic Dmg. | Strength Check (DC 20) to shatter ice or Fire Dmg to melt. |',
      '| **Prone** | Lying on ground. Ranged Attacks vs. Target: Disadvantage. Melee vs. Target: Advantage. | Move Action to stand up. |',
      '| **Stunned** | Incapacitated. Lose all Actions. Drop items. Defense = Base (No Dex/Skill). | Constitution Save (DC 15) at end of turn to recover. |',
      '| **Suppressed** | Pinned by fire. Leaving cover triggers immediate Attack of Opportunity. | Enemy stops firing, reloads, or is neutralized. |'
    ].join('\n'),
    mechanic: 'Bleeding: 1d4 dmg/turn ignores DR (Medicine DC 10)\nBurning: 1d6 fire/rnd + Will DC 12 panic (Full Action Stop/Drop/Roll)\nFreeze: Speed 0, Vulnerable Phys/Sonic (Str DC 20 or Fire)\nStunned: 0 Actions, Drop items, Base Defense (Con DC 15)',
    guide: 'Track active conditions on character tokens and folios to apply correct situational modifiers.',
    note: 'Prone provides +2 Defense per range category after Point Blank vs. ranged attacks.'
  },
  {
    id: '3-13-ranged-burst-automatic-fire',
    name: '3.13 Ranged, Burst & Automatic Fire',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 13,
    description: [
      '# 3.13 Ranged, Burst & Automatic Fire',
      '',
      'Modern ballistic and energy firearms feature selective firing modes with distinct tactical tradeoffs. All Range penalties are **Doubled** during automatic fire.',
      '',
      '---',
      '',
      '## Fire Modes & Ballistics Matrix',
      '',
      '| Firing Mode | Ammo Expended | Attack Modifier | Damage / Area Effect |',
      '| :--- | :---: | :---: | :--- |',
      '| **Single Shot (Semi-Auto)**| 1 Round | Base Strike Score | Standard weapon damage |',
      '| **3-Round Burst** | 3 Rounds | **+1 Strike** | Standard damage |',
      '| **Full Auto (Long Burst)**| 10+ Rounds | **-1 Recoil per 10 rds** | **Extra hits** for every point over Defense DC (+1d damage per hit) |',
      '| **Area Suppression (General)**| 20 Rounds | Targets Grid Area | Targets take **+2 Damage Dice** for every 5 points over DC 10 |',
      '| **Focused Blast Zone** | 30 Rounds | Concentrated Zone | Targets take **+100% Damage Dice** for every 10 points over DC 15 |'
    ].join('\n'),
    mechanic: 'FullAutoHits = min(AmmoFired, max(1, AttackRoll - DefenseDC))\nExtraDamagePerHit = +1d weapon damage dice',
    guide: 'Declare your weapon\'s firing mode before rolling your attack. Check your ammo counter.',
    note: 'Firing burst or full-auto without high Strength or a weapon bipod increases recoil penalties by -2.'
  },
  {
    id: '3-14-scale-multipliers-vehicle-mecha',
    name: '3.14 Scale Multipliers & Vehicle/Mecha Combat',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 14,
    description: [
      '# 3.14 Scale Multipliers & Vehicle/Mecha Combat',
      '',
      'When personnel-scale firearms interact with armored mecha or starships, **Scale Multipliers** ensure realistic armor protection and destructive force.',
      '',
      '---',
      '',
      '## Combat Scale Hierarchy',
      '',
      '| Scale Tier | Typical Entity | Scale Multiplier vs Personnel | Damage Resistance Multiplier |',
      '| :--- | :--- | :---: | :---: |',
      '| **Personnel (1x)** | Humans, cyborgs, beasts, light drones | **$\\times 1$** | **$\\times 1$** |',
      '| **Vehicle / Light Mecha (5x)**| APCs, gunships, combat walkers | **$\\times 5$** | **$\\times 5$** |',
      '| **Heavy Mecha / Tank (10x)**| Battle tanks, siege titans | **$\\times 10$** | **$\\times 10$** |',
      '| **Starship / Dropship (50x)**| Corvettes, frigates, shuttles | **$\\times 50$** | **$\\times 50$** |',
      '| **Capital / Orbital (100x)**| Dreadnoughts, orbital battle stations| **$\\times 100$** | **$\\times 100$** |',
      '',
      '---',
      '',
      '## Scale Damage Calculation Rules',
      '- When a personnel weapon strikes a **Vehicle-Scale (5x)** target: Personnel damage is divided by 5 before applying vehicle Armor DR.',
      '- When a **Vehicle-Scale (5x)** weapon strikes a Personnel target: Damage is multiplied by 5, almost always resulting in instant vaporization.'
    ].join('\n'),
    mechanic: 'DamageToHigherScale = RawDamage / ScaleRatio\nDamageToLowerScale = RawDamage * ScaleRatio',
    guide: 'Use heavy anti-armor ordnance (missiles, railguns) when engaging higher-scale military targets.',
    note: 'Energy shields protect against all scales equally up to their rated capacity.'
  },
  {
    id: '3-15-vehicle-chases-dogfights',
    name: '3.15 Vehicular Combat, Dogfights & System Failures',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 15,
    description: [
      '# 3.15 Vehicular Combat, Dogfights & System Failures',
      '',
      'Vehicular combat escalates the core 2d10 rules across 4 Domains of War (*Land, Nautical, Atmospheric, Interstellar*).',
      '',
      '---',
      '',
      '## 1. Initiative & The Crew Turn',
      '- **Initiative Formula:** $2\\text{d}10 + \\text{Agility Mod} + \\text{Alertness} + \\text{Handling Modifier}$.',
      '- **Pilot:** Controls Movement, Evasion (Defense), and Fixed Forward Weapons (45° arc).',
      '- **Gunner(s):** Control Turrets and Pintle mounts (360° arc); track independent actions.',
      '- **Engineer / System Operator:** Manages Shields, Sensors, EW, and Field Repairs.',
      '',
      '---',
      '',
      '## 2. Tactical Dogfights & Stalling',
      '- **The Dogfight:** Opposed Pilot checks at start of round.',
      '  - *Winner:* Gains **Advantage** on attack rolls this round and chooses positioning (**Tail / Flank**).',
      '  - *Loser:* Considered **Flat-Footed** against the winner.',
      '- **Stalling:** Flying slower than Stall Speed forces a **Pilot Check (DC 20)** or craft enters a terminal fall.',
      '',
      '---',
      '',
      '## 3. System Failure Table (d6)',
      'Rolled when a vehicle suffers a Critical Hit (Natural 20 or exceed Defense by 10+) or reaches **50% SP**:',
      '',
      '| d6 Roll | System Failure | Mechanical Effect |',
      '| :---: | :--- | :--- |',
      '| **1** | **Motive System** | Speed reduced by **50%** (treads thrown, wing clipped). |',
      '| **2** | **Weapon System** | One random weapon disabled or jammed. |',
      '| **3** | **Sensor / Comms** | Blinded or silenced; **Disadvantage on all targeting**. |',
      '| **4** | **Crew Compartment** | Cockpit breached; crew takes **half the damage** dealt to vehicle. |',
      '| **5** | **Power Plant** | Smoke and internal fire; vehicle takes **1d6 Burn damage per turn**. |',
      '| **6** | **Catastrophic Leak** | Fuel/reactor unstable; **explodes in 1d4 rounds** unless repaired. |',
      '',
      '---',
      '',
      '## 4. Vehicle Destruction & Explosion',
      '- **0 SP (Disabled):** Vehicle stops. Systems offline. Can be repaired.',
      '- **Negative SP > 50% Max (Destroyed):** Total loss, scrap wreck only.',
      '- **Catastrophic Explosion:** Detonates if destroyed by Fire or Explosive damage.',
      '  - *Radius:* **10 feet per Size Category**.',
      '  - *Damage:* **1d6 per 10 SP** of the vehicle\'s maximum structure.'
    ].join('\n'),
    mechanic: 'VehicleInitiative = 2d10 + AgilityMod + Alertness + HandlingMod\nDogfight = Opposed Pilot Check (Advantage + Tail/Flank vs Flat-Footed)\nSystemFailure = Rolled at 50% SP or on Critical Hit\nCatastrophicExplosion = 10ft/Size Cat radius, 1d6 per 10 max SP',
    guide: 'Roll opposed Pilot checks for dogfights. Apply d6 System Failure Table when a vehicle takes critical damage or hits 50% SP.',
    note: 'Infantry called shots against vehicle weak points (-5 Strike) ignore 50% of Armor DR.'
  },
  {
    id: '3-16-zero-g-vacuum-combat-rules',
    name: '3.16 Zero-G & Vacuum Combat Rules',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 16,
    description: [
      '# 3.16 Zero-G & Vacuum Combat Rules',
      '',
      'Fighting in the cold silence of outer space introduces recoil inertia, 3D vector movement, and explosive decompression hazards.',
      '',
      '---',
      '',
      '## Core Zero-G Rules',
      '',
      '1. **Recoil Inertia (Newton\'s Third Law):** Firing a ballistic or heavy weapon without magnetic boot locks or micro-thruster anchors pushes the shooter backward 10 feet in the opposite direction.',
      '2. **3D Tactical Movement:** Combatants can move in all three dimensions. Cover can be attacked from above or below.',
      '3. **Suit Breaches:** Any penetrating kinetic or energy hit on a pressurized environment suit forces an immediate **Suit Seal Check (DC 15)**:',
      '   - **Failure:** Rapid decompression; character suffers $ cold/hypoxia damage per round until patched.',
      '4. **Silent Battlefield:** Sound does not propagate in vacuum. All verbal communication requires encrypted radio frequencies or laser-comms.'
    ].join('\n'),
    mechanic: 'ZeroGRecoilDrift = 10 ft backward on ballistic fire (unless anchored)\nSuitBreachDC = 15 (Medicine or Technology check to patch)',
    guide: 'Equip mag-boots or maneuvering thrusters before entering depressurized hull breaches.',
    note: 'Laser and energy weapons generate zero recoil drift in microgravity.'
  },
  {
    id: '3-17-movement-rules-paces-fatigue',
    name: '3.17 Movement Modes, Tactical Paces & Fatigue Rules',
    category: 'compendium',
    entry_type: 'Core Rule',
    parent: '3.00 COMBAT',
    order: 17,
    description: [
      '# 3.17 Movement Modes, Tactical Paces & Fatigue Rules',
      '',
      'Locomotion across planetary battlefields, void stations, and alien biospheres is categorized into **5 Primary Movement Modes**: Ground, Flying, Swimming, Climbing, and Burrowing.',
      '',
      '---',
      '',
      '## 1. Ground Movement Matrix',
      '',
      '| Pace | Speed Multiplier | Medium Speed (30 ft base) | Action Modifiers (Stealth/Subtlety/Precision) | Fatigue & Skill Check |',
      '| :--- | :---: | :---: | :---: | :--- |',
      '| **Walk** | **1x (Base)** | 30 ft / 6s (6 kph) | Standard baseline | None |',
      '| **Jog** | **2x** | 60 ft / 6s | **-2 penalty** | None |',
      '| **Running** | **4x** *(5x with Runner)* | 120 ft *(150 ft)* | **-4 penalty** | **Athletics DC 10+** (every min, cum. -1) |',
      '| **Sprinting** | **6x** *(7x with Runner)* | 180 ft *(210 ft)* | **-8 penalty** | **Athletics DC 15+** (every min, cum. -1) |',
      '| **Crawl** | **1/2x** | 15 ft / 6s | **+2 stealth**; gains **Prone** | None |',
      '| **Slow Crawl** | **1/4x** | 7.5 ft / 6s | **+4 stealth**; gains **Prone** | None |',
      '',
      '---',
      '',
      '## 2. Flying Movement Matrix',
      '',
      '| Maneuver | Speed Multiplier | Medium Speed (60 ft fly) | Action Modifiers | Skill Check / Maneuver DC |',
      '| :--- | :---: | :---: | :---: | :--- |',
      '| **Flight** | **1x Fly (2x Walk)** | 60 ft / 6s | Standard flyer baseline | None |',
      '| **Sail** | **2x Fly (4x Walk)** | 120 ft / 6s | **-2 penalty** | None |',
      '| **Surge / Soar** | **4x Fly (8x Walk)** *(5x with Soar)* | 240 ft *(300 ft)* | **-4 penalty** | **Acrobatics DC 10+** (every min, cum. -1) |',
      '| **Diving** | **2x Current Speed** *(9x with Soar)* | Up to 480+ ft | **-4 penalty** | **Acrobatics DC 15+** |',
      '| **Gliding** | Maintains speed, drops 1ft per 5ft horiz | 60 ft horiz / 12 ft fall | **+2 bonus** | **Acrobatics DC 10+** |',
      '| **Hover / Controlled Descent** | **1/2 Fly or less** | 30 ft or static | Observation ready | **Acrobatics DC 15+** |',
      '',
      '### Aerial Combat Rules',
      '- **High Ground Bonus**: Airborne combatants above grounded foes gain **+2 Strike** and **+2 Critical Threat Range**.',
      '- **Aerial Ram Formula**: $\\text{Ram Damage} = +1d \\text{ per Stage} + 1 \\text{ Impact Damage per 10 ft Speed}$ to all involved parties.',
      '',
      '---',
      '',
      '## 3. Swimming Movement Matrix',
      '',
      '| Pace | Speed Multiplier | Medium Speed (15 ft base) | Action Modifiers | Skill Check |',
      '| :--- | :---: | :---: | :---: | :--- |',
      '| **Swimming** | **1x Swim (1/2 Walk)** | 15 ft / 6s (3 kph) | Standard swim | None |',
      '| **Glide** | **2x Swim (1x Walk)** | 30 ft / 6s | **-2 penalty** | **Athletics (Swim) DC 10+** |',
      '| **Stroke** | **4x Swim (2x Walk)** | 60 ft / 6s | **-4 penalty** | **Athletics (Swim) DC 15+** |',
      '| **Treading** | **1/2 Swim or less** | 7.5 ft / 6s | **+2 bonus** | **Athletics (Swim) DC 5+** |',
      '*(Swimming Feature elevates rates to: 1x Walk [30 ft] Swim, 2x Walk [60 ft] Glide, 3x Walk [90 ft] Stroke).*',
      '',
      '---',
      '',
      '## 4. Climbing Movement Matrix',
      '',
      '| Pace | Base Speed Ratio | Medium Speed | Action Modifiers | Skill Check |',
      '| :--- | :---: | :---: | :---: | :--- |',
      '| **Easy Climb (DC 10+)** | **1/2 Walk** | 15 ft / 6s | Standard climb | **Athletics (Climb)** vs DC 10 |',
      '| **Moderate Climb (DC 15+)**| **1/4 Walk** | 7.5 ft / 6s | Challenging surface | **Athletics (Climb)** vs DC 15 |',
      '| **Difficult Climb (DC 20+)** | **1/10 Walk** | 3 ft / 6s | Sheer wall / ice | **Athletics (Climb)** vs DC 20 |',
      '| **Scaling** | **1x Walk** | 30 ft / 6s | **-2 penalty** | Athletics (Climb) at **-5** |',
      '| **Fast Ascent** | **2x Walk** | 60 ft / 6s | **-4 penalty** | Athletics (Climb) at **-10** |',
      '| **Fast Descent** | **4x Walk** | 120 ft / 6s | **-4 penalty** | **DC 20** or Athletics at **-10** |',
      '*(Climbing Feature elevates rates to: 1x Walk Climb, 2x Scale, 3x Fast Ascent, 6x Fast Descent).*',
      '',
      '---',
      '',
      '## 5. Burrowing Movement Matrix',
      '',
      '| Pace | Speed Ratio | Medium Speed | Action Modifiers | Practical Application |',
      '| :--- | :---: | :---: | :---: | :--- |',
      '| **Burrowing** | **1/4x Walk** | 7.5 ft / 6s | Displaces earth/sand | Standard underground movement |',
      '| **Tunneling** | **2x Burrow (1/2 Walk)** | 15 ft / 6s | **-2 penalty** | Escape tunnels, offensive breaching |',
      '| **Excavation** | **1/8x Walk** | 3.75 ft / 6s | Shoring & reinforcement | Pit traps, bunker construction |',
      '',
      '---',
      '',
      '## 6. Movement Fatigue & Exhaustion Rules',
      '',
      '- **Trigger**: Sprinting for **5 consecutive combat rounds** or **10 minutes of hurried travel** triggers a **Stamina-based Fortitude Check (DC 15)**.',
      '- **Check Progression**: Checked every minute with a **cumulative -1 penalty** per successive roll.',
      '- **Failure Penalty**: On failure, take **1 point of non-lethal damage per 5 points missed** below the DC (or 5 flat points on standard failure).',
      '- **Exhaustion State**: If Vitality is reduced to 0, take **2 physical Health damage** and gain the **Exhausted** condition (**-2 to all active checks and half movement speed**) until taking a **Light Rest (Nap)**.'
    ].join('\n'),
    mechanic: 'GroundPaces: Walk(1x), Jog(2x), Run(4x/5x), Sprint(6x/7x)\nAerialRam: +1d per FlightStage + 1 Impact per 10ft Speed\nExhausted: -2 to all checks, Movement Speed halved',
    guide: 'Track pace multiples during movement actions and prompt Fortitude DC 15 checks upon sustained sprint triggers.',
    note: 'Running, Swimming, Climbing, and Soar features augment speed multiples without increasing subtlety penalties.'
  }
];
